const fs = require('fs');
let code = fs.readFileSync('lib/screens/home_map_screen.dart', 'utf8');
code = code.replace(/\r\n/g, '\n');

// Replace the entire AnimationLimiter+ListView.separated block with PremiumParkCard+FeaturedBanner
const oldBlock = `AnimationLimiter(\n                child: ListView.separated(\n                padding: const EdgeInsets.symmetric(vertical: 6),\n                itemCount: _filtered.length,\n                separatorBuilder: (_, __) =>\n                    const Divider(height: 1, indent: 16, endIndent: 16),\n                itemBuilder: (_, i) {\n                  final p = _filtered[i];\n                  return AnimationConfiguration.staggeredList(\n                    position: i,\n                    duration: const Duration(milliseconds: 375),\n                    child: SlideAnimation(\n                      verticalOffset: 28.0,\n                      child: FadeInAnimation(\n                        child: ListTile(\n                    leading: Hero(\n                      tag: 'park_hero_\${p.id}',\n                      child: ClipRRect(\n                        borderRadius: BorderRadius.circular(8),\n                        child: (p.thumbnail ?? '').isNotEmpty\n                            ? ParkImage(image: p.thumbnail!, width: 56, height: 56, fit: BoxFit.cover)\n                            : Container(\n                                width: 56, height: 56,\n                                color: cs.primaryContainer,\n                                child: Center(child: Text(\n                                  p.name.isNotEmpty ? p.name[0].toUpperCase() : '?',\n                                  style: TextStyle(color: cs.onPrimaryContainer, fontWeight: FontWeight.w900),\n                                )),\n                              ),\n                      ),\n                    ),\n                    title: Text(p.name,\n                        style: const TextStyle(fontWeight: FontWeight.w800)),\n                    subtitle: Text(\n                        [p.city, p.country]\n                            .where((s) => (s ?? '').isNotEmpty)\n                            .join(', '),\n                        style: TextStyle(color: Colors.grey.shade600)),\n                    trailing: Text(p.type.name,\n                        style: TextStyle(\n                            fontSize: 11,\n                            color: cs.primary,\n                            fontWeight: FontWeight.w700)),\n                    onTap: () {\n                      HapticFeedback.lightImpact();\n                      _controller?.animateCamera(\n                          CameraUpdate.newLatLngZoom(\n                              LatLng(p.lat, p.lng), 12));\n                      _openPark(p);\n                    },\n                        ),  // ListTile\n                        ),  // FadeInAnimation\n                      ),  // SlideAnimation\n                    );  // AnimationConfiguration\n                },\n                ),  // ListView\n              ),  // AnimationLimiter`;

const newBlock = `AnimationLimiter(\n                child: ListView.builder(\n                  padding: const EdgeInsets.only(bottom: 16),\n                  itemCount: _hasActiveFilters\n                      ? _filtered.length\n                      : _filtered.length + 1,\n                  itemBuilder: (_, i) {\n                    if (!_hasActiveFilters && i == 0) {\n                      return FeaturedParksBanner(\n                        parks: _allParks.take(8).toList(),\n                        onTap: _openPark,\n                      );\n                    }\n                    final idx = _hasActiveFilters ? i : i - 1;\n                    final p = _filtered[idx];\n                    return AnimationConfiguration.staggeredList(\n                      position: idx,\n                      duration: const Duration(milliseconds: 375),\n                      child: SlideAnimation(\n                        verticalOffset: 28.0,\n                        child: FadeInAnimation(\n                          child: PremiumParkCard(\n                            park: p,\n                            onTap: () {\n                              _controller?.animateCamera(\n                                  CameraUpdate.newLatLngZoom(\n                                      LatLng(p.lat, p.lng), 12));\n                              _openPark(p);\n                            },\n                          ),\n                        ),\n                      ),\n                    );\n                  },\n                ),  // ListView\n              ),  // AnimationLimiter`;

if (code.includes(oldBlock)) {
  code = code.replace(oldBlock, newBlock);
  console.log('✓ List replaced with PremiumParkCard + FeaturedBanner');
} else {
  console.warn('⚠ Block not found — dumping 50 chars around AnimationLimiter for debug:');
  const idx = code.indexOf('AnimationLimiter');
  console.log(JSON.stringify(code.substring(idx, idx + 600)));
}

fs.writeFileSync('lib/screens/home_map_screen.dart', code, 'utf8');
console.log('Done');