const fs=require('fs');
const d=[
{id:'wizarding_world_of_harry_potter',name:'The Wizarding World of Harry Potter',description:'One of the most celebrated theme park zones ever created — The Wizarding World of Harry Potter at Universal Studios Japan is a masterpiece of immersive theming that transports visitors into the world of Hogwarts with breathtaking architectural detail, the iconic Harry Potter and the Forbidden Journey ride, Ollivanders wand shop, Butterbeer and the complete Hogsmeade village experience. The most visited and beloved attraction at USJ and one of the greatest theme park zones in the world. Suitable for all ages.',image:'assets/images/universal_studios_japan/wizarding_world_of_harry_potter.png',category:'family',topPick:true,lat:34.6654,lng:135.4323,liveWaitMinutes:90,rating:4.9,speedKmh:0,heightM:0,inversions:0,openedYear:2014,minHeightCm:0,temporarilyClosed:false},
{id:'mario_kart_koopas_challenge',name:'Mario Kart: Koopa\'s Challenge',description:'The most technologically advanced theme park ride in Japan — Mario Kart Koopa\'s Challenge in Super Nintendo World uses augmented reality headsets and physical track to place riders inside the actual world of Mario Kart in a groundbreaking and utterly unique ride experience. Super Nintendo World itself is one of the most elaborately themed zones in theme park history. Min 107cm.',image:'assets/images/universal_studios_japan/mario_kart_koopas_challenge.png',category:'family',topPick:true,lat:34.6656,lng:135.4325,liveWaitMinutes:120,rating:4.9,speedKmh:0,heightM:0,inversions:0,openedYear:2021,minHeightCm:107,temporarilyClosed:false},
{id:'flying_dinosaur',name:'The Flying Dinosaur',description:'The longest and most spectacular flying coaster in Asia — The Flying Dinosaur places riders in a prone flying position and sends them soaring through a massive layout with incredible speed, sweeping inversions and breathtaking near-miss elements. One of the greatest flying coasters ever built and the most thrilling ride at Universal Studios Japan. Min 132cm.',image:'assets/images/universal_studios_japan/flying_dinosaur.png',category:'thrill',topPick:true,lat:34.6658,lng:135.4327,liveWaitMinutes:100,rating:4.8,speedKmh:100,heightM:37,inversions:4,openedYear:2016,minHeightCm:132,temporarilyClosed:false},
{id:'hollywood_dream_the_ride',name:'Hollywood Dream The Ride',description:'A legendary Japanese theme park coaster — Hollywood Dream delivers a unique music-themed coaster experience where riders select their own soundtrack for the ride. Features powerful launches, significant airtime moments and spectacular park views. Also operates as a backward-facing version called The Backdrop. Min 122cm.',image:'assets/images/universal_studios_japan/hollywood_dream_the_ride.png',category:'thrill',topPick:true,lat:34.6660,lng:135.4329,liveWaitMinutes:70,rating:4.7,speedKmh:90,heightM:43,inversions:0,openedYear:2000,minHeightCm:122,temporarilyClosed:false},
{id:'jurassic_world_ride',name:'Jurassic World The Ride',description:'A spectacular water ride adventure through the Jurassic World island environment — featuring extraordinary animatronic dinosaurs, dramatic near-miss encounters and a breathtaking final plunge that delivers one of the most exciting and impressive water ride experiences in Asia. Min 122cm.',image:'assets/images/universal_studios_japan/jurassic_world_ride.png',category:'family',topPick:true,lat:34.6662,lng:135.4331,liveWaitMinutes:75,rating:4.6,speedKmh:0,heightM:25,inversions:0,openedYear:2022,minHeightCm:122,temporarilyClosed:false},
{id:'space_fantasy_the_ride',name:'Space Fantasy The Ride',description:'A uniquely Japanese omni-mover dark ride through a spectacular cosmic space environment — Space Fantasy is one of the most beloved and uniquely USJ attractions featuring beautiful cosmic theming, spinning vehicles and a genuinely magical atmosphere. A USJ original not found at any other Universal park. Min 107cm.',image:'assets/images/universal_studios_japan/space_fantasy_the_ride.png',category:'family',topPick:true,lat:34.6664,lng:135.4333,liveWaitMinutes:60,rating:4.6,speedKmh:0,heightM:0,inversions:0,openedYear:2009,minHeightCm:107,temporarilyClosed:false},
{id:'waterworld',name:'WaterWorld',description:'The most spectacular live stunt show at any theme park in Asia — WaterWorld delivers an enormous Hollywood-style live action water stunt show with explosive pyrotechnics, jet ski stunts, seaplane crashes and incredible water effects performed by professional stunt performers multiple times daily. Suitable for all ages.',image:'assets/images/universal_studios_japan/waterworld.png',category:'family',topPick:true,lat:34.6652,lng:135.4321,liveWaitMinutes:20,rating:4.7,speedKmh:0,heightM:0,inversions:0,openedYear:2001,minHeightCm:0,temporarilyClosed:false},
{id:'jaws',name:'Jaws',description:'A classic and beloved USJ original — the Jaws ride takes guests on a boat tour through Amity Island that is repeatedly attacked by the legendary great white shark in an atmospheric and genuinely entertaining attraction that has become one of the most nostalgic and beloved rides at USJ. Min 107cm.',image:'assets/images/universal_studios_japan/jaws.png',category:'family',topPick:false,lat:34.6648,lng:135.4317,liveWaitMinutes:35,rating:4.4,speedKmh:0,heightM:0,inversions:0,openedYear:2001,minHeightCm:107,temporarilyClosed:false},
{id:'backdraft',name:'Backdraft',description:'An intense walk-through fire effects attraction recreating the explosive behind-the-scenes world of the Hollywood film Backdraft — featuring dramatic fire and explosion special effects in a theatrical presentation that remains one of the most viscerally impressive attractions at USJ. Suitable for all ages.',image:'assets/images/universal_studios_japan/backdraft.png',category:'family',topPick:false,lat:34.6646,lng:135.4315,liveWaitMinutes:15,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:2001,minHeightCm:0,temporarilyClosed:false},
{id:'amity_village',name:'Amity Village',description:'The atmospheric Jaws-themed waterfront zone at Universal Studios Japan — recreating the seaside town of Amity Island from the Spielberg classic with detailed New England coastal architecture, Amity Landing restaurant and the original Jaws ride. One of the most beautifully themed zones at USJ. Suitable for all ages.',image:'assets/images/universal_studios_japan/amity_village.png',category:'family',topPick:false,lat:34.6644,lng:135.4313,liveWaitMinutes:0,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2001,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/universal_studios_japan/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('attractions.json done, entries:',d.length);