const fs=require('fs');
const d=[
{id:'crystal_wing',name:'Crystal Wing',description:'The premier roller coaster at Happy Valley Beijing — Crystal Wing is a spectacular suspended wing coaster where riders sit in open wing-shaped vehicles with nothing above or below them, delivering breathtaking inversions and high-speed sweeping turns with extraordinary views over the park and Beijing skyline. The most thrilling and visually stunning coaster in the Happy Valley chain. Min 130cm.',image:'assets/images/happy_valley_beijing/crystal_wing.png',category:'thrill',topPick:true,lat:39.8956,lng:116.4732,liveWaitMinutes:60,rating:4.8,speedKmh:100,heightM:38,inversions:5,openedYear:2018,minHeightCm:130,temporarilyClosed:false},
{id:'desperado',name:'Desperado',description:'A high-speed launched steel coaster themed to the Wild West — Desperado delivers rapid acceleration through a dynamic layout of twists, turns and near-miss elements in one of the most exciting and rerideable coaster experiences at Happy Valley Beijing. Min 130cm.',image:'assets/images/happy_valley_beijing/desperado.png',category:'thrill',topPick:true,lat:39.8958,lng:116.4734,liveWaitMinutes:45,rating:4.6,speedKmh:95,heightM:30,inversions:3,openedYear:2006,minHeightCm:130,temporarilyClosed:false},
{id:'tornado',name:'Tornado',description:'A classic suspended looping coaster delivering intense inversions and high-speed sweeping turns — Tornado is a beloved thrill institution at Happy Valley Beijing and one of the most popular coasters in the park. Min 130cm.',image:'assets/images/happy_valley_beijing/tornado.png',category:'thrill',topPick:false,lat:39.8960,lng:116.4736,liveWaitMinutes:40,rating:4.4,speedKmh:90,heightM:32,inversions:4,openedYear:2006,minHeightCm:130,temporarilyClosed:false},
{id:'sky_drop',name:'Sky Drop',description:'A towering free-fall drop tower delivering breathtaking views over Happy Valley Beijing and the surrounding landscape — riders are raised to the summit and then released in a sudden and exhilarating free fall. One of the most popular thrill attractions at the park. Min 130cm.',image:'assets/images/happy_valley_beijing/sky_drop.png',category:'thrill',topPick:false,lat:39.8962,lng:116.4738,liveWaitMinutes:30,rating:4.3,speedKmh:0,heightM:45,inversions:0,openedYear:2006,minHeightCm:130,temporarilyClosed:false},
{id:'himalayan_eagle',name:'Himalayan Eagle',description:'A massive high-speed pendulum swing ride themed to the mountains and wilderness of the Himalayas — delivering soaring thrills with spectacular panoramic views over the park. One of the most dramatic flat rides at Happy Valley Beijing. Min 130cm.',image:'assets/images/happy_valley_beijing/himalayan_eagle.png',category:'thrill',topPick:false,lat:39.8964,lng:116.4740,liveWaitMinutes:25,rating:4.3,speedKmh:0,heightM:28,inversions:0,openedYear:2006,minHeightCm:130,temporarilyClosed:false},
{id:'pirate_ship',name:'Pirate Ship',description:'A classic Viking ship pendulum ride swinging to increasing heights — a beloved family thrill experience and one of the most popular accessible attractions at Happy Valley Beijing. Min 120cm.',image:'assets/images/happy_valley_beijing/pirate_ship.png',category:'thrill',topPick:false,lat:39.8966,lng:116.4742,liveWaitMinutes:20,rating:4.1,speedKmh:0,heightM:20,inversions:0,openedYear:2006,minHeightCm:120,temporarilyClosed:false},
{id:'mayan_ruins',name:'Mayan Ruins',description:'An elaborately themed dark ride adventure through the ancient Mayan civilisation — featuring impressive temple environments, mysterious chambers and dramatic special effects that make it one of the most atmospheric dark rides in Beijing. Suitable for all ages.',image:'assets/images/happy_valley_beijing/mayan_ruins.png',category:'family',topPick:true,lat:39.8954,lng:116.4730,liveWaitMinutes:35,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2006,minHeightCm:0,temporarilyClosed:false},
{id:'canyon_splash',name:'Canyon Splash',description:'A thrilling log flume and water ride adventure through dramatic canyon landscapes — Canyon Splash delivers exciting drops and guaranteed soakings in a spectacular outdoor water ride that is the most popular summer attraction at Happy Valley Beijing. Min 110cm.',image:'assets/images/happy_valley_beijing/canyon_splash.png',category:'family',topPick:true,lat:39.8952,lng:116.4728,liveWaitMinutes:45,rating:4.5,speedKmh:0,heightM:18,inversions:0,openedYear:2006,minHeightCm:110,temporarilyClosed:false},
{id:'proslide',name:'ProSlide Water Attraction',description:'A spectacular collection of high-speed water slides and water rides in the Happy Valley water park zone — featuring slides of varying intensity including speed slides, family raft rides and the iconic tunnel slide. The most popular water attraction complex at Happy Valley Beijing. Min 110cm.',image:'assets/images/happy_valley_beijing/proslide.png',category:'family',topPick:true,lat:39.8950,lng:116.4726,liveWaitMinutes:40,rating:4.4,speedKmh:0,heightM:15,inversions:0,openedYear:2010,minHeightCm:110,temporarilyClosed:false},
{id:'ice_world',name:'Ice World',description:'A uniquely magical indoor winter wonderland attraction at Happy Valley Beijing — featuring an elaborately decorated indoor ice environment with ice sculptures, frozen landscapes and interactive ice experiences. One of the most visually spectacular and uniquely Chinese theme park experiences in Beijing. Suitable for all ages.',image:'assets/images/happy_valley_beijing/ice_world.png',category:'family',topPick:true,lat:39.8948,lng:116.4724,liveWaitMinutes:20,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2012,minHeightCm:0,temporarilyClosed:false},
{id:'jungle_racing',name:'Jungle Racing',description:'An exciting family coaster themed to jungle adventure — Jungle Racing winds through elaborate tropical forest scenery delivering fun family thrills suitable for children and adults. One of the most popular family coasters at Happy Valley Beijing. Min 110cm.',image:'assets/images/happy_valley_beijing/jungle_racing.png',category:'family',topPick:false,lat:39.8946,lng:116.4722,liveWaitMinutes:30,rating:4.2,speedKmh:65,heightM:15,inversions:0,openedYear:2006,minHeightCm:110,temporarilyClosed:false},
{id:'goldmine_train',name:'Goldmine Train',description:'A classic mine train roller coaster winding through elaborately themed gold mine environments — a gentle but genuinely fun family coaster delivering accessible thrills for all generations. One of the most beloved family attractions at Happy Valley Beijing. Min 100cm.',image:'assets/images/happy_valley_beijing/goldmine_train.png',category:'family',topPick:false,lat:39.8944,lng:116.4720,liveWaitMinutes:25,rating:4.1,speedKmh:50,heightM:12,inversions:0,openedYear:2006,minHeightCm:100,temporarilyClosed:false},
{id:'carousel_kingdom',name:'Carousel Kingdom',description:'A grand and beautifully decorated traditional carousel in the heart of Happy Valley Beijing — a charming and timeless family attraction that is one of the most photographed and beloved experiences in the park. Suitable for all ages.',image:'assets/images/happy_valley_beijing/carousel_kingdom.png',category:'family',topPick:false,lat:39.8942,lng:116.4718,liveWaitMinutes:10,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:2006,minHeightCm:0,temporarilyClosed:false},
{id:'bumper_cars',name:'Bumper Cars',description:'Classic dodgem bumper cars delivering endless fun for all ages — one of the most popular and accessible attractions at Happy Valley Beijing, loved by visitors of every age group. Suitable for all ages.',image:'assets/images/happy_valley_beijing/bumper_cars.png',category:'family',topPick:false,lat:39.8940,lng:116.4716,liveWaitMinutes:15,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:2006,minHeightCm:0,temporarilyClosed:false},
{id:'ferris_wheel',name:'Ferris Wheel',description:'A magnificent large observation wheel delivering sweeping panoramic views over Happy Valley Beijing and the surrounding city — the most scenic attraction in the park and the best vantage point for surveying the entire Happy Valley landscape. Suitable for all ages.',image:'assets/images/happy_valley_beijing/ferris_wheel.png',category:'family',topPick:false,lat:39.8938,lng:116.4714,liveWaitMinutes:15,rating:4.3,speedKmh:0,heightM:50,inversions:0,openedYear:2006,minHeightCm:0,temporarilyClosed:false},
{id:'haunt_house',name:'Haunted House',description:'A spooky walk-through haunted house attraction featuring elaborately themed horror rooms, atmospheric lighting and startling special effects — the most popular Halloween and scare attraction at Happy Valley Beijing. Min 12 years.',image:'assets/images/happy_valley_beijing/haunt_house.png',category:'thrill',topPick:false,lat:39.8936,lng:116.4712,liveWaitMinutes:25,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:2008,minHeightCm:0,temporarilyClosed:false},
{id:'happy_valley_show',name:'Happy Valley Live Show',description:'A spectacular live entertainment show at Happy Valley Beijing featuring professional performers, elaborate costumes and stunning visual effects — the most popular daily show at the park and an essential part of the Happy Valley Beijing experience. Suitable for all ages.',image:'assets/images/happy_valley_beijing/carousel_kingdom.png',category:'family',topPick:false,lat:39.8934,lng:116.4710,liveWaitMinutes:0,rating:4.3,speedKmh:0,heightM:0,inversions:0,openedYear:2006,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/happy_valley_beijing/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('attractions.json done, entries:',d.length);