const fs=require('fs');
const d=[
{id:'velociraptor',name:'Velociraptor',description:'The fastest roller coaster in the Middle East — Velociraptor launches riders from 0 to 100 km/h in under 2.5 seconds in a breathtaking outdoor launch coaster experience. A record-breaking thrill attraction and the undisputed crown jewel of IMG Worlds of Adventure. Min 130cm.',image:'assets/images/img_worlds/velociraptor.png',category:'thrill',topPick:true,lat:25.0723,lng:55.2880,liveWaitMinutes:55,rating:4.8,speedKmh:100,heightM:20,inversions:0,openedYear:2016,minHeightCm:130,temporarilyClosed:false},
{id:'predator',name:'Predator',description:'A thrilling high-speed spinning coaster that hurls riders through a dynamic layout of twists, turns and inversions — Predator is the premier indoor thrill coaster at IMG Worlds of Adventure delivering intense forces and exciting surprises in complete darkness. Min 120cm.',image:'assets/images/img_worlds/predator.png',category:'thrill',topPick:true,lat:25.0724,lng:55.2881,liveWaitMinutes:45,rating:4.5,speedKmh:80,heightM:16,inversions:2,openedYear:2016,minHeightCm:120,temporarilyClosed:false},
{id:'avengers_flight_of_the_quinjets',name:'Avengers Flight of the Quinjets',description:'A spectacular family suspended coaster themed to the Avengers — guests soar through the Marvel universe in Quinjet vehicles alongside Iron Man, Captain America and Thor in a thrilling aerial adventure. One of the most popular attractions in the Marvel zone at IMG Worlds. Min 105cm.',image:'assets/images/img_worlds/avengers_flight_of_the_quinjets.png',category:'thrill',topPick:true,lat:25.0725,lng:55.2882,liveWaitMinutes:50,rating:4.6,speedKmh:60,heightM:14,inversions:0,openedYear:2016,minHeightCm:105,temporarilyClosed:false},
{id:'spiderman_doc_ocks_revenge',name:'Spider-Man Doc Ock\'s Revenge',description:'A thrilling spinning dark ride that puts guests inside a Spider-Man adventure as Doc Ock unleashes chaos on New York City — featuring elaborate sets, special effects and the unique spinning ride system that keeps guests constantly rotating through the action. Min 102cm.',image:'assets/images/img_worlds/spiderman_doc_ocks_revenge.png',category:'thrill',topPick:true,lat:25.0726,lng:55.2883,liveWaitMinutes:40,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2016,minHeightCm:102,temporarilyClosed:false},
{id:'hulk_epsilon_base_3d',name:'Hulk Epsilon Base 3D',description:'A dynamic 4D motion simulator that puts guests inside a Hulk adventure — featuring powerful seat motion, HD visuals and special effects as guests are transported into an epic battle alongside the Incredible Hulk. One of the most immersive simulator experiences in the Middle East. Min 102cm.',image:'assets/images/img_worlds/hulk_epsilon_base_3d.png',category:'thrill',topPick:false,lat:25.0727,lng:55.2884,liveWaitMinutes:30,rating:4.3,speedKmh:0,heightM:0,inversions:0,openedYear:2016,minHeightCm:102,temporarilyClosed:false},
{id:'lost_valley_dinosaur_safari',name:'Lost Valley Dinosaur Safari',description:'An extraordinary dark ride safari through a prehistoric Lost Valley teeming with life-size animatronic dinosaurs — guests journey through dense jungle encountering T-Rex, Triceratops, Brachiosaurus and dozens of other dinosaur species in one of the most elaborate and immersive dark rides in the Middle East. Suitable for all ages.',image:'assets/images/img_worlds/lost_valley_dinosaur_safari.png',category:'family',topPick:true,lat:25.0728,lng:55.2885,liveWaitMinutes:35,rating:4.6,speedKmh:0,heightM:0,inversions:0,openedYear:2016,minHeightCm:0,temporarilyClosed:false},
{id:'haunted_hotel',name:'Haunted Hotel',description:'A terrifying walk-through haunted attraction set inside an abandoned hotel filled with jump scares, elaborately themed horror rooms and genuine fright experiences — the most popular scare attraction in Dubai and one of the most intense walk-through horror experiences in the Middle East. Min 12 years.',image:'assets/images/img_worlds/haunted_hotel.png',category:'thrill',topPick:true,lat:25.0729,lng:55.2886,liveWaitMinutes:40,rating:4.7,speedKmh:0,heightM:0,inversions:0,openedYear:2016,minHeightCm:0,temporarilyClosed:false},
{id:'forbidden_territory',name:'Forbidden Territory',description:'A high-intensity haunted walk-through experience in a dark and atmospheric zone of IMG Worlds — featuring elaborate scare zones, live actors and genuinely frightening environments that make it one of the most intense horror experiences in the Middle East. Min 12 years.',image:'assets/images/img_worlds/forbidden_territory.png',category:'thrill',topPick:false,lat:25.0730,lng:55.2887,liveWaitMinutes:25,rating:4.4,speedKmh:0,heightM:0,inversions:0,openedYear:2016,minHeightCm:0,temporarilyClosed:false},
{id:'cartoon_network_amazone',name:'Cartoon Network Amazone',description:'A spectacular Cartoon Network themed zone featuring rides and attractions themed to Ben 10, Adventure Time, The Powerpuff Girls and more — the most colourful and family-friendly zone at IMG Worlds of Adventure and a paradise for younger visitors. Suitable for all ages.',image:'assets/images/img_worlds/cartoon_network_amazone.png',category:'family',topPick:true,lat:25.0731,lng:55.2888,liveWaitMinutes:20,rating:4.4,speedKmh:0,heightM:0,inversions:0,openedYear:2016,minHeightCm:0,temporarilyClosed:false},
{id:'dino_carousel',name:'Dino Carousel',description:'A beautifully themed carousel in the Lost Valley zone featuring dinosaur-shaped ride vehicles instead of traditional horses — a charming and uniquely themed family attraction beloved by young children at IMG Worlds of Adventure. Suitable for all ages.',image:'assets/images/img_worlds/dino_carousel.png',category:'family',topPick:false,lat:25.0732,lng:55.2889,liveWaitMinutes:10,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:2016,minHeightCm:0,temporarilyClosed:false},
{id:'img_boulevard',name:'IMG Boulevard',description:'The spectacular main entrance boulevard of IMG Worlds of Adventure — a grand retail and entertainment promenade featuring Marvel, Cartoon Network and Dinosaur themed shops, merchandise outlets and character meet and greet locations. The most photographed area of the park. Suitable for all ages.',image:'assets/images/img_worlds/img_boulevard.png',category:'family',topPick:false,lat:25.0722,lng:55.2879,liveWaitMinutes:0,rating:4.3,speedKmh:0,heightM:0,inversions:0,openedYear:2016,minHeightCm:0,temporarilyClosed:false},
{id:'avengers_team_thor',name:'Avengers: Battle of Ultron',description:'An immersive 4D cinema experience placing guests in the heart of an epic Avengers battle against Ultron — featuring powerful motion seats, surround sound and spectacular visual effects that make this one of the most entertaining superhero theatre experiences in the Middle East. Suitable for all ages.',image:'assets/images/img_worlds/avengers_flight_of_the_quinjets.png',category:'family',topPick:false,lat:25.0725,lng:55.2882,liveWaitMinutes:15,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:2016,minHeightCm:0,temporarilyClosed:false},
{id:'marvel_character_experience',name:'Marvel Character Experience',description:'An exclusive Marvel character meet and greet experience where guests can meet Spider-Man, Iron Man, Captain America and other Marvel superheroes for photos and autographs — the most popular character experience in Dubai and one of the only places in the Middle East to meet official Marvel characters. Suitable for all ages.',image:'assets/images/img_worlds/spiderman_doc_ocks_revenge.png',category:'family',topPick:false,lat:25.0726,lng:55.2883,liveWaitMinutes:25,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2016,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/img_worlds/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('attractions.json done, entries:',d.length);