const fs=require('fs');
const d=[
{id:'goliath_la_ronde',name:'Goliath',description:'The tallest and most thrilling roller coaster in Quebec — Goliath is a spectacular hyper coaster soaring 53 metres above La Ronde with a breathtaking first drop and a high-speed layout of airtime hills and sweeping turns offering extraordinary views over Montreal and the St. Lawrence River. The most acclaimed and beloved coaster at any Quebec theme park. Min 137cm.',image:'assets/images/la_ronde/goliath_la_ronde.png',category:'thrill',topPick:true,lat:45.5088,lng:-73.5330,liveWaitMinutes:60,rating:4.8,speedKmh:110,heightM:53,inversions:0,openedYear:2006,minHeightCm:137,temporarilyClosed:false},
{id:'vampire',name:'Vampire',description:'A thrilling and beloved inverted roller coaster at La Ronde — Vampire sends riders through multiple inversions in suspended hanging vehicles through a dramatic layout with spectacular views over the St. Lawrence River. One of the most popular and rerideable coasters at La Ronde. Min 130cm.',image:'assets/images/la_ronde/vampire.png',category:'thrill',topPick:true,lat:45.5085,lng:-73.5325,liveWaitMinutes:45,rating:4.6,speedKmh:90,heightM:32,inversions:5,openedYear:2000,minHeightCm:130,temporarilyClosed:false},
{id:'super_manege',name:'Super Manège',description:'A classic and iconic looping roller coaster at La Ronde — Super Manège is one of the most beloved and historically significant coasters in Quebec, delivering classic loop and corkscrew inversions in a spectacular riverside setting. A La Ronde institution since 1985. Min 130cm.',image:'assets/images/la_ronde/super_manege.png',category:'thrill',topPick:true,lat:45.5082,lng:-73.5335,liveWaitMinutes:35,rating:4.4,speedKmh:88,heightM:30,inversions:3,openedYear:1985,minHeightCm:130,temporarilyClosed:false},
{id:'boomerang_la_ronde',name:'Boomerang',description:'A classic and thrilling boomerang shuttle coaster at La Ronde delivering forward and backward passes through three inversions — one of the most popular and accessible thrill coasters at the park. Min 122cm.',image:'assets/images/la_ronde/boomerang_la_ronde.png',category:'thrill',topPick:false,lat:45.5090,lng:-73.5328,liveWaitMinutes:30,rating:4.2,speedKmh:80,heightM:26,inversions:3,openedYear:1995,minHeightCm:122,temporarilyClosed:false},
{id:'vol_ultime',name:'Vol Ultime',description:'A spectacular floorless roller coaster at La Ronde delivering multiple inversions in an open floorless vehicle — Vol Ultime is one of the most intense and thrilling coaster experiences at any Canadian theme park. Min 137cm.',image:'assets/images/la_ronde/vol_ultime.png',category:'thrill',topPick:true,lat:45.5086,lng:-73.5332,liveWaitMinutes:40,rating:4.5,speedKmh:95,heightM:34,inversions:6,openedYear:2009,minHeightCm:137,temporarilyClosed:false},
{id:'cobra',name:'Cobra',description:'A classic stand-up roller coaster at La Ronde delivering loops and inversions in a unique upright riding position — Cobra is one of the most unusual and memorable coaster experiences at any Quebec theme park. Min 137cm.',image:'assets/images/la_ronde/cobra.png',category:'thrill',topPick:false,lat:45.5083,lng:-73.5338,liveWaitMinutes:25,rating:4.1,speedKmh:80,heightM:28,inversions:4,openedYear:1991,minHeightCm:137,temporarilyClosed:false},
{id:'spirale',name:'Spirale',description:'A thrilling and unique spiral drop tower at La Ronde that rotates as it descends — Spirale is one of the most distinctive and memorable non-coaster thrill experiences at any Canadian theme park. Min 122cm.',image:'assets/images/la_ronde/spirale.png',category:'thrill',topPick:false,lat:45.5091,lng:-73.5322,liveWaitMinutes:20,rating:4.2,speedKmh:0,heightM:45,inversions:0,openedYear:2001,minHeightCm:122,temporarilyClosed:false},
{id:'ednor',name:'Ednor',description:'A beloved and thrilling log flume ride at La Ronde plunging riders down a dramatic waterfall finale — Ednor is one of the most popular and refreshing water attractions at La Ronde and a classic Quebec theme park institution. Min 107cm.',image:'assets/images/la_ronde/ednor.png',category:'family',topPick:false,lat:45.5079,lng:-73.5340,liveWaitMinutes:35,rating:4.3,speedKmh:0,heightM:18,inversions:0,openedYear:1978,minHeightCm:107,temporarilyClosed:false},
{id:'aqua_twist',name:'Aqua Twist',description:'A fun and splashy spinning water ride at La Ronde — Aqua Twist spins riders in rotating boats through a series of water jets and rapids for a thoroughly refreshing and rerideable experience. Suitable for all ages.',image:'assets/images/la_ronde/aqua_twist.png',category:'family',topPick:false,lat:45.5080,lng:-73.5342,liveWaitMinutes:25,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:2005,minHeightCm:0,temporarilyClosed:false},
{id:'chaos',name:'Chaos',description:'A classic and wildly spinning flat ride at La Ronde delivering disorienting rotations and inversions — Chaos is one of the most popular and entertaining flat rides at any Quebec theme park. Min 122cm.',image:'assets/images/la_ronde/chaos.png',category:'thrill',topPick:false,lat:45.5088,lng:-73.5320,liveWaitMinutes:20,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:1998,minHeightCm:122,temporarilyClosed:false},
{id:'le_monstre',name:'Le Monstre',description:'A classic and beloved twin-tracked wooden roller coaster at La Ronde and one of the most iconic wooden coasters in Canada — Le Monstre has delivered classic wooden coaster thrills since 1985 and is one of the most cherished and nostalgic attractions at any Quebec theme park. Min 122cm.',image:'assets/images/la_ronde/le_monstre.png',category:'thrill',topPick:true,lat:45.5077,lng:-73.5345,liveWaitMinutes:30,rating:4.3,speedKmh:88,heightM:30,inversions:0,openedYear:1985,minHeightCm:122,temporarilyClosed:false},
{id:'roue_grande',name:'La Grande Roue',description:'A spectacular giant Ferris wheel at La Ronde offering breathtaking panoramic views over Montreal, the St. Lawrence River and the surrounding landscape — La Grande Roue is the most scenic and atmospheric attraction at La Ronde. Suitable for all ages.',image:'assets/images/la_ronde/roue_grande.png',category:'family',topPick:true,lat:45.5092,lng:-73.5318,liveWaitMinutes:15,rating:4.5,speedKmh:0,heightM:45,inversions:0,openedYear:2000,minHeightCm:0,temporarilyClosed:false},
{id:'minirail',name:'Minirail',description:'A charming and scenic elevated train ride around La Ronde — the Minirail offers beautiful views over the park and the St. Lawrence River and is one of the most relaxing and atmospheric rides at La Ronde. Suitable for all ages.',image:'assets/images/la_ronde/minirail.png',category:'family',topPick:false,lat:45.5084,lng:-73.5315,liveWaitMinutes:10,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:1967,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/la_ronde/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('La Ronde attractions done:',d.length);