const fs=require('fs');
function readJson(p){let r=fs.readFileSync(p,'utf8');if(r.charCodeAt(0)===0xFEFF)r=r.slice(1);return JSON.parse(r);}

const food=[
{id:'food_mooseburger',name:'Mooseburger Lodge',description:'The most popular and beloved restaurant at Six Flags Great America — Mooseburger Lodge is a wonderfully themed Canadian lodge-style restaurant serving enormous and delicious burgers, loaded fries and classic American comfort food in a fun and atmospheric setting.',topPick:true,type:'American Lodge Burgers',image:'assets/images/six_flags_great_america/food_mooseburger.png',lat:42.3708,lng:-87.9368,rating:4.4,items:[{name:'Mooseburger',description:'The legendary double Mooseburger with special sauce and fries',price:18},{name:'Loaded Fries',description:'Thick fries with cheese sauce, bacon and jalapeños',price:10},{name:'Onion Rings',description:'Classic beer-battered onion rings',price:8},{name:'Milkshake',description:'Hand-spun milkshake in classic flavours',price:9}]},
{id:'food_garden_state_grill',name:'Garden State Grill',description:'A popular and convenient grill restaurant at Six Flags Great America serving classic American grilled dishes including burgers, chicken and classic sides. One of the most satisfying quick-service options at the park.',topPick:false,type:'American Grill',image:'assets/images/six_flags_great_america/food_garden_state_grill.png',lat:42.3712,lng:-87.9372,rating:4.1,items:[{name:'Classic Burger',description:'Classic beef burger with cheese, lettuce and tomato',price:16},{name:'Grilled Chicken',description:'Classic grilled chicken sandwich with fries',price:15},{name:'Corn on the Cob',description:'Grilled sweet corn with butter',price:5},{name:'Soft Drink',description:'Large fountain drink',price:4}]},
{id:'food_waterin_hole',name:"Waterin' Hole",description:'A fun and popular Western-themed quick-service restaurant at Six Flags Great America serving classic American comfort food including hot dogs, nachos and classic snacks in an entertaining atmosphere.',topPick:false,type:'American Western',image:'assets/images/six_flags_great_america/food_waterin_hole.png',lat:42.3700,lng:-87.9360,rating:3.9,items:[{name:'Hot Dog',description:'Classic beef hot dog with mustard and relish',price:10},{name:'Nachos',description:'Classic cheese nachos with jalapeños and salsa',price:10},{name:'Corn Dog',description:'Classic deep-fried corn dog',price:8},{name:'Lemonade',description:'Fresh squeezed lemonade',price:5}]},
{id:'food_panda_express',name:'Panda Express',description:'A popular and convenient Panda Express at Six Flags Great America serving classic Chinese-American dishes. One of the most accessible dining options at the park.',topPick:false,type:'Chinese-American',image:'assets/images/six_flags_great_america/food_panda_express.png',lat:42.3695,lng:-87.9365,rating:3.9,items:[{name:'Orange Chicken Bowl',description:'Classic Panda Express orange chicken with fried rice',price:13},{name:'Beijing Beef',description:'Crispy beef with sweet and spicy sauce',price:13},{name:'Chow Mein',description:'Classic chow mein noodles',price:8},{name:'Soft Drink',description:'Large fountain drink',price:4}]},
{id:'food_funnel_cake',name:'Funnel Cake Palace',description:'The most beloved sweet treat destination at Six Flags Great America — Funnel Cake Palace serves the legendary deep-fried funnel cakes with powdered sugar, strawberries or Nutella that are the quintessential American theme park dessert experience.',topPick:true,type:'American Desserts',image:'assets/images/six_flags_great_america/food_funnel_cake.png',lat:42.3718,lng:-87.9360,rating:4.5,items:[{name:'Classic Funnel Cake',description:'Classic deep-fried funnel cake with powdered sugar',price:9},{name:'Strawberry Funnel Cake',description:'Funnel cake with fresh strawberry topping',price:11},{name:'Nutella Funnel Cake',description:'Funnel cake with Nutella and powdered sugar',price:12},{name:'Lemonade',description:'Fresh squeezed lemonade',price:5}]}
];
fs.writeFileSync('assets/data/parks/six_flags_great_america/food.json',JSON.stringify(food,null,2),'utf8');
console.log('SFGAM food done:',food.length);

const hotels=[
{id:'hotel_great_wolf_lodge_gurnee',name:'Great Wolf Lodge Gurnee',description:'The most extraordinary and beloved family resort near Six Flags Great America — Great Wolf Lodge Gurnee is a magnificent indoor waterpark resort with an enormous indoor waterpark, themed family suites and outstanding family entertainment. The best family resort experience near any Chicago-area theme park.',image:'assets/images/six_flags_great_america/hotel_great_wolf_lodge_gurnee.png',lat:42.3723,lng:-87.9421,rating:4.7,topPick:true,website:'https://www.greatwolf.com/gurnee',rooms:[{key:'standard_suite',name:'Standard Suite',description:'Themed family suite sleeping up to 6 with waterpark access.',pricePerNight:300,breakfastIncluded:false},{key:'themed_suite',name:'Wolf Den Suite',description:'Premium themed den suite with bunk area.',pricePerNight:400,breakfastIncluded:false},{key:'premium_suite',name:'Premium Suite',description:'Magnificent suite with panoramic views.',pricePerNight:550,breakfastIncluded:false}]},
{id:'hotel_marriott_gurnee',name:'Marriott Chicago/Gurnee',description:'A comfortable and convenient Marriott hotel just minutes from Six Flags Great America — offering modern rooms, a pool and excellent value for Great America visitors.',image:'assets/images/six_flags_great_america/hotel_marriott_gurnee.png',lat:42.3701,lng:-87.9389,rating:4.3,topPick:false,website:'https://www.marriott.com',rooms:[{key:'standard_room',name:'Standard Room',description:'Modern room with free WiFi and pool access.',pricePerNight:150,breakfastIncluded:false},{key:'king_room',name:'King Room',description:'Spacious king room with upgraded bedding.',pricePerNight:180,breakfastIncluded:false},{key:'suite',name:'Suite',description:'Spacious suite with living area.',pricePerNight:270,breakfastIncluded:true}]},
{id:'hotel_hilton_garden_gurnee',name:'Hilton Garden Inn Gurnee',description:'A comfortable and family-friendly Hilton Garden Inn conveniently located near Six Flags Great America with indoor pool and complimentary breakfast.',image:'assets/images/six_flags_great_america/hotel_hilton_garden_gurnee.png',lat:42.3698,lng:-87.9395,rating:4.2,topPick:false,website:'https://www.hilton.com',rooms:[{key:'standard_room',name:'Standard Room',description:'Comfortable room with free WiFi, pool access and breakfast.',pricePerNight:140,breakfastIncluded:true},{key:'king_room',name:'King Room',description:'Spacious king room with breakfast.',pricePerNight:170,breakfastIncluded:true},{key:'suite',name:'Suite',description:'Spacious suite with living area and breakfast.',pricePerNight:250,breakfastIncluded:true}]},
{id:'hotel_hampton_inn_gurnee',name:'Hampton Inn Gurnee',description:'A reliable and affordable Hampton Inn near Six Flags Great America offering comfortable rooms, complimentary breakfast and easy access to the park. The best budget option for Great America visitors.',image:'assets/images/six_flags_great_america/hotel_hampton_inn_gurnee.png',lat:42.3695,lng:-87.9401,rating:4.1,topPick:false,website:'https://www.hilton.com',rooms:[{key:'standard_room',name:'Standard Room',description:'Comfortable room with free WiFi and breakfast.',pricePerNight:120,breakfastIncluded:true},{key:'king_room',name:'King Room',description:'Spacious king room with breakfast.',pricePerNight:145,breakfastIncluded:true},{key:'suite',name:'Suite',description:'Spacious suite with breakfast.',pricePerNight:210,breakfastIncluded:true}]}
];
fs.writeFileSync('assets/data/parks/six_flags_great_america/hotels.json',JSON.stringify(hotels,null,2),'utf8');
console.log('SFGAM hotels done:',hotels.length);

const pe={id:"six_flags_great_america",thumbnailAsset:"assets/images/six_flags_great_america/park_thumbnail.png",tailAsset:"",name:"Six Flags Great America",type:"Theme Park",entryPrice:{child:59,adult:74},currency:"USD",openingHours:"10:30 - 21:00",lng:-87.9364,country:"USA",city:"Gurnee, Illinois",ticketsUrl:"https://www.sixflags.com/greatamerica/tickets",queueTimesId:0};
const ie={id:"six_flags_great_america",name:"Six Flags Great America",city:"Gurnee, Illinois",country:"USA",type:"Theme Park",lat:42.3703,lng:-87.9364,thumbnail:"assets/images/six_flags_great_america/park_thumbnail.png",website:"https://www.sixflags.com/greatamerica",ticketsUrl:"https://www.sixflags.com/greatamerica/tickets",detailAsset:"",openingHours:"10:30 - 21:00",entryPrices:{adult:74,child:59},currency:"USD",queueTimesId:0};
const parks=readJson('assets/data/parks.json');
if(!parks.find(p=>p.id==='six_flags_great_america')){parks.push(pe);fs.writeFileSync('assets/data/parks.json',JSON.stringify(parks,null,4),'utf8');console.log('parks.json:',parks.length);}
const index=readJson('assets/data/parks/parks_index.json');
if(!index.find(p=>p.id==='six_flags_great_america')){index.push(ie);fs.writeFileSync('assets/data/parks/parks_index.json',JSON.stringify(index,null,4),'utf8');console.log('parks_index.json:',index.length);}