const fs=require('fs');
const d=[
{id:'takabisha',name:'Takabisha',description:'The world steepest roller coaster featuring a record-breaking 121-degree beyond-vertical drop — Takabisha holds the Guinness World Record and delivers one of the most terrifying and exhilarating drop experiences on earth. A Fuji-Q Highland icon with extraordinary views of Mount Fuji. Min 130cm.',image:'assets/images/fujiq_highland/takabisha.png',category:'thrill',topPick:true,lat:35.4895,lng:138.7822,liveWaitMinutes:90,rating:4.9,speedKmh:100,heightM:43,inversions:7,openedYear:2011,minHeightCm:130,temporarilyClosed:false},
{id:'eejanaika',name:'Eejanaika',description:'A world record-breaking fourth dimension coaster where both the train and individual seats rotate 360 degrees independently — creating a completely unpredictable and utterly disorientating ride experience unlike anything else in Japan. Held the world record for most inversions. Min 130cm.',image:'assets/images/fujiq_highland/eejanaika.png',category:'thrill',topPick:true,lat:35.4897,lng:138.7824,liveWaitMinutes:80,rating:4.8,speedKmh:126,heightM:76,inversions:14,openedYear:2006,minHeightCm:130,temporarilyClosed:false},
{id:'fujiyama',name:'Fujiyama',description:'The King of Coasters — Fujiyama was once the world tallest and fastest roller coaster when it opened in 1996 and remains an iconic symbol of Fuji-Q Highland. Delivers breathtaking views of Mount Fuji throughout the ride and a towering 79-metre drop. A true coaster legend. Min 130cm.',image:'assets/images/fujiq_highland/fujiyama.png',category:'thrill',topPick:true,lat:35.4893,lng:138.7820,liveWaitMinutes:70,rating:4.7,speedKmh:130,heightM:79,inversions:0,openedYear:1996,minHeightCm:130,temporarilyClosed:false},
{id:'dodonpa',name:'Do-Dodonpa',description:'The world fastest accelerating roller coaster — Do-Dodonpa blasts riders from 0 to 180 km/h in just 1.56 seconds using compressed air launch technology, then launches riders into a massive 360-degree loop. One of the most intense and physically demanding coaster experiences in the world. Min 130cm.',image:'assets/images/fujiq_highland/dodonpa.png',category:'thrill',topPick:true,lat:35.4899,lng:138.7826,liveWaitMinutes:75,rating:4.8,speedKmh:180,heightM:49,inversions:1,openedYear:2017,minHeightCm:130,temporarilyClosed:false},
{id:'haunted_hospital',name:'Haunted Hospital',description:'Japan most famous and terrifying haunted attraction — the Haunted Hospital is a legendary walk-through horror experience set inside a vast abandoned hospital complex with elaborately themed rooms, professional scare actors and genuinely disturbing encounters. One of the most extreme haunted attractions in the world. Min 13 years.',image:'assets/images/fujiq_highland/haunted_hospital.png',category:'thrill',topPick:true,lat:35.4901,lng:138.7828,liveWaitMinutes:60,rating:4.8,speedKmh:0,heightM:0,inversions:0,openedYear:2000,minHeightCm:0,temporarilyClosed:false},
{id:'zokkon',name:'Zokkon',description:'An intense and disorientating indoor coaster experience that combines high-speed launches with complete darkness and elaborate horror theming — Zokkon is one of the most uniquely unsettling coaster experiences in Japan. Min 120cm.',image:'assets/images/fujiq_highland/zokkon.png',category:'thrill',topPick:false,lat:35.4903,lng:138.7830,liveWaitMinutes:40,rating:4.3,speedKmh:75,heightM:18,inversions:0,openedYear:2020,minHeightCm:120,temporarilyClosed:false},
{id:'red_tower',name:'Red Tower',description:'A towering free-fall drop tower rising 55 metres above the Fuji-Q park with breathtaking panoramic views of Mount Fuji and the Fuji Five Lakes — the most spectacular drop tower view in Japan. Min 120cm.',image:'assets/images/fujiq_highland/red_tower.png',category:'thrill',topPick:false,lat:35.4891,lng:138.7818,liveWaitMinutes:25,rating:4.4,speedKmh:0,heightM:55,inversions:0,openedYear:2003,minHeightCm:120,temporarilyClosed:false},
{id:'nagashimasuka',name:'Nagashimasuka',description:'A classic log flume water ride through scenic waterways with a dramatic splashing final drop — a beloved family favourite and perfect refreshment on warm days at Fuji-Q Highland. Min 100cm.',image:'assets/images/fujiq_highland/nagashimasuka.png',category:'family',topPick:false,lat:35.4889,lng:138.7816,liveWaitMinutes:30,rating:4.1,speedKmh:0,heightM:12,inversions:0,openedYear:1980,minHeightCm:100,temporarilyClosed:false},
{id:'tondemina',name:'Tondemina',description:'A classic pendulum swing ride delivering soaring thrills with spectacular views of Mount Fuji at the apex of each swing — one of the most scenic flat rides in Japan with the iconic mountain as the backdrop. Min 120cm.',image:'assets/images/fujiq_highland/tondemina.png',category:'thrill',topPick:false,lat:35.4905,lng:138.7832,liveWaitMinutes:20,rating:4.2,speedKmh:0,heightM:22,inversions:0,openedYear:1985,minHeightCm:120,temporarilyClosed:false},
{id:'paniclock',name:'Panic Clock',description:'A giant double-sided swing that rotates while spinning passengers simultaneously — delivering intense disorienting thrills with spectacular panoramic views of Mount Fuji. One of the most popular flat rides at Fuji-Q Highland. Min 120cm.',image:'assets/images/fujiq_highland/paniclock.png',category:'thrill',topPick:false,lat:35.4907,lng:138.7834,liveWaitMinutes:25,rating:4.2,speedKmh:0,heightM:25,inversions:0,openedYear:2005,minHeightCm:120,temporarilyClosed:false},
{id:'tetenkomai',name:'Tetenkomai',description:'A gentle and charming family air ride where guests soar above the park in hang-glider vehicles with stunning views of Mount Fuji — one of the most scenic and relaxing family attractions at Fuji-Q Highland. Min 100cm.',image:'assets/images/fujiq_highland/tetenkomai.png',category:'family',topPick:false,lat:35.4887,lng:138.7814,liveWaitMinutes:15,rating:4.1,speedKmh:0,heightM:15,inversions:0,openedYear:2002,minHeightCm:100,temporarilyClosed:false},
{id:'evangelion_world',name:'Evangelion World',description:'A spectacular Evangelion themed attraction celebrating the iconic Japanese anime franchise — featuring life-size recreations of EVA units, elaborate themed environments and exclusive Evangelion merchandise. A pilgrimage destination for anime fans worldwide visiting Fuji-Q Highland. Suitable for all ages.',image:'assets/images/fujiq_highland/evangelion_world.png',category:'family',topPick:true,lat:35.4909,lng:138.7836,liveWaitMinutes:20,rating:4.6,speedKmh:0,heightM:0,inversions:0,openedYear:2012,minHeightCm:0,temporarilyClosed:false},
{id:'mount_fuji_view',name:'Mount Fuji Panorama View',description:'The most extraordinary natural backdrop of any theme park in the world — Fuji-Q Highland sits directly at the foot of Mount Fuji and on clear days every attraction in the park is framed by the perfect snow-capped cone of Japan most iconic mountain. The ultimate destination for Mount Fuji photography. Suitable for all ages.',image:'assets/images/fujiq_highland/mount_fuji_view.png',category:'family',topPick:true,lat:35.4885,lng:138.7812,liveWaitMinutes:0,rating:4.9,speedKmh:0,heightM:0,inversions:0,openedYear:1961,minHeightCm:0,temporarilyClosed:false},
{id:'fujisan_station_hotel',name:'Fujisan Station Hotel Experience',description:'A unique hotel experience directly inside the Fuji-Q Highland park — the Fujisan Station Hotel is a charmingly converted former Fuji-Q railway station building offering guests the extraordinary experience of sleeping inside a theme park, waking up to Mount Fuji views and having first access to the rides. Suitable for all ages.',image:'assets/images/fujiq_highland/fujisan_station_hotel.png',category:'family',topPick:false,lat:35.4883,lng:138.7810,liveWaitMinutes:0,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2015,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/fujiq_highland/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('attractions.json done, entries:',d.length);