const fs=require('fs');
const d=[
{id:'formula_rossa',name:'Formula Rossa',description:'The fastest roller coaster on earth — Formula Rossa launches riders from 0 to 240 km/h in 4.9 seconds, replicating the acceleration of a Ferrari Formula 1 car. At 240 km/h it is the only coaster in the world to require riders to wear protective goggles. The defining ride of Ferrari World Abu Dhabi and one of the most extraordinary theme park experiences on the planet. Min 140cm.',image:'assets/images/ferrari_world/formula_rossa.png',category:'thrill',topPick:true,lat:24.4836,lng:54.6081,liveWaitMinutes:90,rating:4.9,speedKmh:240,heightM:52,inversions:0,openedYear:2010,minHeightCm:140,temporarilyClosed:false},
{id:'turbo_track',name:'Turbo Track',description:'A spectacular vertical launch coaster that fires riders straight up through the iconic Ferrari World roof at 105 km/h before reaching a moment of weightlessness at the apex and plunging back down. The most visually dramatic coaster at Ferrari World and unmissable from anywhere in Yas Island. Min 120cm.',image:'assets/images/ferrari_world/turbo_track.png',category:'thrill',topPick:true,lat:24.4838,lng:54.6083,liveWaitMinutes:60,rating:4.7,speedKmh:105,heightM:63,inversions:0,openedYear:2017,minHeightCm:120,temporarilyClosed:false},
{id:'flying_aces',name:'Flying Aces',description:'A record-breaking coaster featuring the world tallest non-inverting loop at 52 metres and the world steepest drop at 120 degrees — themed to the story of Francesco Baracca, the World War I flying ace whose prancing horse emblem inspired the Ferrari logo. One of the finest coasters in the Middle East. Min 130cm.',image:'assets/images/ferrari_world/flying_aces.png',category:'thrill',topPick:true,lat:24.4837,lng:54.6082,liveWaitMinutes:55,rating:4.8,speedKmh:120,heightM:52,inversions:0,openedYear:2016,minHeightCm:130,temporarilyClosed:false},
{id:'fiorano_gt_challenge',name:'Fiorano GT Challenge',description:'Twin racing coasters that pit two riders against each other in a head-to-head race around a Ferrari-themed circuit — modelled on the legendary Fiorano test track in Maranello where Ferrari test their road and race cars. A uniquely competitive and thrilling experience. Min 120cm.',image:'assets/images/ferrari_world/fiorano_gt_challenge.png',category:'thrill',topPick:true,lat:24.4839,lng:54.6084,liveWaitMinutes:45,rating:4.6,speedKmh:95,heightM:18,inversions:0,openedYear:2010,minHeightCm:120,temporarilyClosed:false},
{id:'bell_italia',name:'Bell Italia',description:'A stunning indoor scenic drive experience where guests ride in replica Ferrari vehicles through a beautiful recreation of the Italian countryside, villages and landmarks — one of the most atmospheric and uniquely Ferrari experiences at the park. Suitable for all ages.',image:'assets/images/ferrari_world/bell_italia.png',category:'family',topPick:true,lat:24.4835,lng:54.6080,liveWaitMinutes:30,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2010,minHeightCm:0,temporarilyClosed:false},
{id:'maranello_race',name:'Maranello Race',description:'A high-speed family racing simulator that puts riders in the seat of a Ferrari as they race through Maranello — combining motion simulation with stunning Ferrari racing visuals in one of the most immersive family experiences at Ferrari World. Min 105cm.',image:'assets/images/ferrari_world/maranello_race.png',category:'family',topPick:false,lat:24.4840,lng:54.6085,liveWaitMinutes:35,rating:4.3,speedKmh:0,heightM:0,inversions:0,openedYear:2010,minHeightCm:105,temporarilyClosed:false},
{id:'scuderia_challenge',name:'Scuderia Challenge',description:'An authentic Ferrari F1 driving simulator where guests experience the precise handling and power of a genuine Formula 1 car on iconic racing circuits. The most technically impressive simulator experience at Ferrari World Abu Dhabi. Min 110cm.',image:'assets/images/ferrari_world/scuderia_challenge.png',category:'family',topPick:true,lat:24.4841,lng:54.6086,liveWaitMinutes:25,rating:4.4,speedKmh:0,heightM:0,inversions:0,openedYear:2010,minHeightCm:110,temporarilyClosed:false},
{id:'junior_gt',name:'Junior GT',description:'A junior driving experience where children can drive their own small Ferrari GT car around a dedicated track — one of the most special childhood experiences available at any theme park in the world. Min 100cm.',image:'assets/images/ferrari_world/junior_gt.png',category:'family',topPick:false,lat:24.4842,lng:54.6087,liveWaitMinutes:20,rating:4.4,speedKmh:0,heightM:0,inversions:0,openedYear:2010,minHeightCm:100,temporarilyClosed:false},
{id:'bennos_great_race',name:'Benno\'s Great Race',description:'A delightful interactive dark ride for families following the adventures of Benno the Ferrari mechanic through classic Italian racing scenes with colourful animation and gentle thrills. Perfect for families with young children. Suitable for all ages.',image:'assets/images/ferrari_world/bennos_great_race.png',category:'family',topPick:false,lat:24.4843,lng:54.6088,liveWaitMinutes:20,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:2010,minHeightCm:0,temporarilyClosed:false},
{id:'rc_challenge',name:'RC Challenge',description:'A fun interactive RC car racing experience where guests race remote-controlled Ferrari cars against each other on a purpose-built track — one of the most entertaining and competitive family experiences at Ferrari World. Suitable for all ages.',image:'assets/images/ferrari_world/rc_challenge.png',category:'family',topPick:false,lat:24.4844,lng:54.6089,liveWaitMinutes:15,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:2010,minHeightCm:0,temporarilyClosed:false},
{id:'tyre_twist',name:'Tyre Twist',description:'A spinning family ride themed to Ferrari pit stop tyres — riders in tyre-shaped vehicles spin and twist in a fun and accessible experience perfect for younger visitors to Ferrari World. Min 90cm.',image:'assets/images/ferrari_world/tyre_twist.png',category:'family',topPick:false,lat:24.4845,lng:54.6090,liveWaitMinutes:15,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:2010,minHeightCm:90,temporarilyClosed:false},
{id:'paddock_stage_show',name:'Paddock Stage Show',description:'A spectacular live entertainment show in the Ferrari World paddock area featuring stunt driving, pyrotechnics and Ferrari performance sequences — one of the most exciting live shows at any theme park in the Middle East. Suitable for all ages.',image:'assets/images/ferrari_world/paddock_stage_show.png',category:'family',topPick:true,lat:24.4846,lng:54.6091,liveWaitMinutes:0,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2010,minHeightCm:0,temporarilyClosed:false},
{id:'ferrari_gallery',name:'Ferrari Gallery',description:'The world most comprehensive exhibition of Ferrari road cars, racing cars and memorabilia — spanning the entire history of Ferrari from the first cars built by Enzo Ferrari in 1947 to the latest hypercars. An unmissable experience for any Ferrari enthusiast. Suitable for all ages.',image:'assets/images/ferrari_world/ferrari_gallery.png',category:'family',topPick:true,lat:24.4847,lng:54.6092,liveWaitMinutes:0,rating:4.7,speedKmh:0,heightM:0,inversions:0,openedYear:2010,minHeightCm:0,temporarilyClosed:false},
{id:'gallery',name:'Speed of Magic',description:'A 4D flying theatre experience that takes riders on a magical journey through the world of Ferrari — combining motion simulation with stunning visual effects and the Ferrari story in a family-friendly immersive cinema experience. Min 105cm.',image:'assets/images/ferrari_world/gallery.png',category:'family',topPick:false,lat:24.4848,lng:54.6093,liveWaitMinutes:25,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:2010,minHeightCm:105,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/ferrari_world/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('attractions.json done, entries:',d.length);