const fs=require('fs');
const d=[
{id:'goliath',name:'Goliath',description:'The most thrilling and beloved roller coaster at Six Flags Over Georgia — Goliath is a spectacular B&M hyper coaster delivering extraordinary airtime over a breathtaking 61-metre first drop and a series of exhilarating speed hills. One of the finest and most rerideable hyper coasters in the southeastern United States. Min 137cm.',image:'assets/images/six_flags_over_georgia/goliath.png',category:'thrill',topPick:true,lat:33.7717,lng:-84.5513,liveWaitMinutes:55,rating:4.7,speedKmh:124,heightM:61,inversions:0,openedYear:2006,minHeightCm:137,temporarilyClosed:false},
{id:'twisted_cyclone',name:'Twisted Cyclone',description:'A spectacular RMC hybrid wooden coaster at Six Flags Over Georgia converting the classic Cyclone with extraordinary new steel track delivering multiple inversions and intense airtime. One of the most exciting and rerideable hybrid coasters in the southeastern United States. Min 122cm.',image:'assets/images/six_flags_over_georgia/twisted_cyclone.png',category:'thrill',topPick:true,lat:33.7722,lng:-84.5520,liveWaitMinutes:45,rating:4.6,speedKmh:96,heightM:30,inversions:3,openedYear:2018,minHeightCm:122,temporarilyClosed:false},
{id:'mindbender',name:'Mindbender',description:'A legendary and beloved triple-loop steel coaster at Six Flags Over Georgia — Mindbender is a classic Schwarzkopf coaster delivering three consecutive loops with extraordinary smoothness and intensity. One of the most historically significant and beloved classic coasters in the American South. Min 137cm.',image:'assets/images/six_flags_over_georgia/mindbender.png',category:'thrill',topPick:true,lat:33.7712,lng:-84.5508,liveWaitMinutes:40,rating:4.5,speedKmh:105,heightM:34,inversions:3,openedYear:1978,minHeightCm:137,temporarilyClosed:false},
{id:'superman',name:'Superman: Ultimate Flight',description:'A spectacular flying coaster at Six Flags Over Georgia placing riders in a prone flying position through breathtaking maneuvers and the legendary pretzel loop inversion. One of the most unique and exhilarating coaster experiences in the Atlanta area. Min 137cm.',image:'assets/images/six_flags_over_georgia/superman.png',category:'thrill',topPick:true,lat:33.7726,lng:-84.5525,liveWaitMinutes:50,rating:4.4,speedKmh:80,heightM:34,inversions:3,openedYear:2004,minHeightCm:137,temporarilyClosed:false},
{id:'batman_the_ride',name:'Batman The Ride',description:'A classic and beloved Batman-themed inverted coaster at Six Flags Over Georgia delivering five inversions at 80 km/h through a spectacular themed layout. One of the most popular and rerideable inverted coasters in Georgia. Min 137cm.',image:'assets/images/six_flags_over_georgia/batman_the_ride.png',category:'thrill',topPick:false,lat:33.7730,lng:-84.5530,liveWaitMinutes:35,rating:4.4,speedKmh:80,heightM:30,inversions:5,openedYear:1997,minHeightCm:137,temporarilyClosed:false},
{id:'scorcher',name:'Georgia Scorcher',description:'The tallest and fastest stand-up roller coaster on the East Coast — Georgia Scorcher delivers six inversions in the unique upright standing position through a spectacular layout. One of the last remaining stand-up coasters in the southeastern United States. Min 137cm.',image:'assets/images/six_flags_over_georgia/scorcher.png',category:'thrill',topPick:false,lat:33.7715,lng:-84.5515,liveWaitMinutes:25,rating:4.3,speedKmh:96,heightM:41,inversions:6,openedYear:1999,minHeightCm:137,temporarilyClosed:false},
{id:'acrophobia',name:'Acrophobia',description:'One of the most terrifying drop tower experiences at any American theme park — Acrophobia lifts riders to 61 metres before releasing them in an open floorless drop seat that tilts riders face-down before the plunge. The most intense drop tower in the American South. Min 122cm.',image:'assets/images/six_flags_over_georgia/acrophobia.png',category:'thrill',topPick:true,lat:33.7708,lng:-84.5505,liveWaitMinutes:30,rating:4.6,speedKmh:0,heightM:61,inversions:0,openedYear:2001,minHeightCm:122,temporarilyClosed:false},
{id:'ninja',name:'Ninja',description:'A beloved and classic suspended swinging coaster at Six Flags Over Georgia swinging riders through a dramatic layout over the Georgia landscape. A beloved park institution since 1992. Min 107cm.',image:'assets/images/six_flags_over_georgia/ninja.png',category:'thrill',topPick:false,lat:33.7720,lng:-84.5522,liveWaitMinutes:20,rating:4.1,speedKmh:72,heightM:21,inversions:0,openedYear:1992,minHeightCm:107,temporarilyClosed:false},
{id:'pandemonium',name:'Pandemonium',description:'A fun and popular spinning wild mouse coaster at Six Flags Over Georgia — riders spin freely in rotating cars through a series of tight turns and drops in a fun and unpredictable experience. Suitable for families. Min 107cm.',image:'assets/images/six_flags_over_georgia/pandemonium.png',category:'family',topPick:false,lat:33.7726,lng:-84.5516,liveWaitMinutes:25,rating:4.1,speedKmh:48,heightM:18,inversions:0,openedYear:2006,minHeightCm:107,temporarilyClosed:false},
{id:'gold_rush',name:'Gold Rush',description:'A classic and charming mine train coaster at Six Flags Over Georgia weaving through the Georgia landscape. A beloved park institution and one of the most accessible family coasters at any Atlanta area theme park. Min 107cm.',image:'assets/images/six_flags_over_georgia/gold_rush.png',category:'family',topPick:false,lat:33.7730,lng:-84.5510,liveWaitMinutes:15,rating:4.0,speedKmh:64,heightM:18,inversions:0,openedYear:1967,minHeightCm:107,temporarilyClosed:false},
{id:'dahlonega_mine_train',name:'Dahlonega Mine Train',description:'A classic and beloved mine train coaster at Six Flags Over Georgia and one of the most charming family coasters in Georgia. The Dahlonega Mine Train has been thrilling families since 1967 and is a cherished park classic. Min 107cm.',image:'assets/images/six_flags_over_georgia/dahlonega_mine_train.png',category:'family',topPick:false,lat:33.7718,lng:-84.5508,liveWaitMinutes:15,rating:4.0,speedKmh:56,heightM:15,inversions:0,openedYear:1967,minHeightCm:107,temporarilyClosed:false},
{id:'great_american_scream_machine',name:'Great American Scream Machine',description:'A beloved classic wooden roller coaster at Six Flags Over Georgia and one of the most historically significant wooden coasters in the American South. The Great American Scream Machine has thrilled visitors since 1973 with classic wooden coaster charm. Min 107cm.',image:'assets/images/six_flags_over_georgia/great_american_scream_machine.png',category:'thrill',topPick:false,lat:33.7712,lng:-84.5518,liveWaitMinutes:20,rating:4.1,speedKmh:88,heightM:30,inversions:0,openedYear:1973,minHeightCm:107,temporarilyClosed:false},
{id:'splashwater_falls',name:'Splashwater Falls',description:'A classic and refreshing log flume ride at Six Flags Over Georgia splashing guests through a dramatic waterfall finale. One of the most popular and beloved water rides in the Atlanta area. Min 107cm.',image:'assets/images/six_flags_over_georgia/splashwater_falls.png',category:'family',topPick:false,lat:33.7705,lng:-84.5512,liveWaitMinutes:25,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:1967,minHeightCm:107,temporarilyClosed:false},
{id:'riverview_carousel',name:'Riverview Carousel',description:'A magnificent and historically significant antique carousel at Six Flags Over Georgia — one of the most beautiful and lovingly preserved carousels at any American theme park. Suitable for all ages.',image:'assets/images/six_flags_over_georgia/riverview_carousel.png',category:'family',topPick:false,lat:33.7715,lng:-84.5505,liveWaitMinutes:5,rating:4.3,speedKmh:0,heightM:0,inversions:0,openedYear:1967,minHeightCm:0,temporarilyClosed:false},
{id:'monster_mansion',name:'Monster Plantation',description:'A beloved and iconic indoor dark ride at Six Flags Over Georgia taking guests through a whimsical swamp filled with friendly monsters and memorable characters. One of the most charming and unique dark rides at any American theme park. Suitable for all ages.',image:'assets/images/six_flags_over_georgia/gold_rush.png',category:'family',topPick:true,lat:33.7720,lng:-84.5515,liveWaitMinutes:15,rating:4.4,speedKmh:0,heightM:0,inversions:0,openedYear:1967,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/six_flags_over_georgia/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('SFOG attractions done:',d.length);