const fs=require('fs');
const d=[
{id:'food_johnny_rockets_north',name:"Johnny Rockets North",description:'The most popular full-service dining experience at Fantasilandia — Johnny Rockets serves classic American burgers, milkshakes, fries and hot dogs in a vibrant 1950s diner atmosphere. The most recognised and beloved restaurant brand at Chile\'s largest theme park.',topPick:true,type:'American Diner',image:'assets/images/fantasilandia/food_johnny_rockets_north.png',lat:-33.4674,lng:-70.6506,rating:4.3,items:[{name:'Classic Burger',description:'Classic beef burger with lettuce, tomato and Johnny\'s special sauce',price:8200},{name:'Milkshake',description:'Creamy thick milkshake in chocolate, vanilla or strawberry',price:4800},{name:'Loaded Fries',description:'Crispy fries with cheese sauce and toppings',price:4200},{name:'Hot Dog',description:'Classic American hot dog in a toasted bun',price:5500}]},
{id:'food_johnny_rockets_south',name:"Johnny Rockets South",description:'The second Johnny Rockets location at Fantasilandia serving the same beloved American diner classics including burgers, milkshakes and fries — conveniently located in the southern zone of the park near the major thrill rides.',topPick:false,type:'American Diner',image:'assets/images/fantasilandia/food_johnny_rockets_south.png',lat:-33.4680,lng:-70.6512,rating:4.2,items:[{name:'Double Patty Burger',description:'Double beef patty burger with cheese and pickles',price:9200},{name:'Onion Rings',description:'Classic crispy onion rings with dipping sauce',price:3800},{name:'Chicken Burger',description:'Crispy chicken burger with coleslaw and mayonnaise',price:7800},{name:'Soft Drink',description:'Selection of cold beverages',price:2200}]},
{id:'food_el_rancho',name:'El Rancho',description:'A popular Chilean grill restaurant at Fantasilandia serving traditional Chilean cuisine including completo hot dogs, chorrillana and classic Chilean comfort food. The most authentic Chilean dining experience at the park.',topPick:true,type:'Chilean Grill',image:'assets/images/fantasilandia/food_el_rancho.png',lat:-33.4676,lng:-70.6508,rating:4.2,items:[{name:'Completo',description:'Classic Chilean completo hot dog with avocado, tomato and mayonnaise',price:3800},{name:'Chorrillana',description:'Iconic Chilean dish of fries with beef, onions and fried eggs',price:6500},{name:'Empanada de Pino',description:'Traditional Chilean baked empanada with beef filling',price:2800},{name:'Jugo Natural',description:'Freshly squeezed fruit juice',price:2200}]},
{id:'food_palacio',name:'Palacio Restaurant',description:'An elegant full-service restaurant at Fantasilandia offering a diverse menu of Chilean and international dishes in a comfortable and relaxed atmosphere. The best option for families wanting a sit-down meal during their visit to Chile\'s largest theme park.',topPick:false,type:'Chilean International',image:'assets/images/fantasilandia/food_palacio.png',lat:-33.4678,lng:-70.6510,rating:4.1,items:[{name:'Lomo a lo Pobre',description:'Chilean steak with fries, fried onions and eggs',price:9800},{name:'Pasta al Pesto',description:'Spaghetti with fresh basil pesto and parmesan',price:7200},{name:'Ensalada Chilena',description:'Classic Chilean tomato and onion salad',price:3200},{name:'Cola de Mono',description:'Traditional Chilean holiday drink',price:2800}]},
{id:'food_don_burro',name:'Don Burro',description:'A fun and casual Mexican-themed quick-service restaurant at Fantasilandia serving tacos, burritos and Mexican snacks. A popular and flavourful dining option for visitors wanting something different at Chile\'s premier theme park.',topPick:false,type:'Mexican Quick Service',image:'assets/images/fantasilandia/food_don_burro.png',lat:-33.4682,lng:-70.6514,rating:4.0,items:[{name:'Tacos Mixtos',description:'Three corn tacos with choice of beef or chicken filling',price:5800},{name:'Burrito Grande',description:'Large flour tortilla with rice, beans and choice of protein',price:6800},{name:'Nachos Especiales',description:'Tortilla chips with cheese, jalapeños and guacamole',price:4500},{name:'Agua de Horchata',description:'Refreshing Mexican horchata rice drink',price:2200}]},
{id:'food_daytona',name:'Daytona Snacks',description:'A high-energy racing-themed snack bar at Fantasilandia serving churros, popcorn, cotton candy and classic fairground snacks. The most popular quick-service sweet treat option at Chile\'s largest theme park.',topPick:false,type:'Snacks and Sweets',image:'assets/images/fantasilandia/food_daytona.png',lat:-33.4684,lng:-70.6516,rating:3.9,items:[{name:'Churros',description:'Classic fried churros with dulce de leche dipping sauce',price:2800},{name:'Popcorn',description:'Freshly popped butter popcorn',price:2200},{name:'Algodón de Azúcar',description:'Classic cotton candy in various colours',price:1800},{name:'Helado',description:'Ice cream cone in various flavours',price:2500}]}
];
fs.writeFileSync('assets/data/parks/fantasilandia/food.json',JSON.stringify(d,null,2),'utf8');
console.log('food.json done, entries:',d.length);