const fs=require('fs');
const d=[
{id:'food_billy_the_beef_restaurant',name:'Billy the Beef Restaurant',description:'The premier dining destination at Beto Carrero World — Billy the Beef is a vibrant Brazilian churrascaria-style restaurant serving generous grilled meats, traditional Brazilian sides and classic South American cuisine. The most popular full-service dining experience at Brazil\'s largest theme park.',topPick:true,type:'Brazilian Churrascaria',image:'assets/images/beto_carrero_world/food_billy_the_beef_restaurant.png',lat:-26.7814,lng:-48.6453,rating:4.4,items:[{name:'Picanha Grilled',description:'Classic Brazilian picanha steak grilled over charcoal with farofa',price:58},{name:'Frango Assado',description:'Whole roasted chicken with Brazilian vinaigrette and rice',price:45},{name:'Pao de Queijo',description:'Classic Brazilian cheese bread rolls',price:12},{name:'Guarana',description:'Classic Brazilian Guarana soft drink',price:8}]},
{id:'food_deck_hot_wheels_restaurant',name:'Deck Hot Wheels Restaurant',description:'A vibrant racing-themed restaurant at Beto Carrero World in partnership with the iconic Hot Wheels brand — serving burgers, hot dogs and fast food favourites in a colourful and energetic atmosphere loved by children and families.',topPick:true,type:'Hot Wheels Themed Fast Food',image:'assets/images/beto_carrero_world/food_deck_hot_wheels_restaurant.png',lat:-26.7816,lng:-48.6455,rating:4.2,items:[{name:'Hot Wheels Burger',description:'Classic beef burger with cheese and special Hot Wheels sauce',price:32},{name:'Racing Hot Dog',description:'Grilled frankfurter in a toasted bun with mustard and ketchup',price:22},{name:'Combo Fries',description:'Crispy fries with ketchup and mayonnaise',price:18},{name:'Milkshake',description:'Creamy milkshake in chocolate or strawberry',price:20}]},
{id:'food_nerf_restaurant',name:'Nerf Restaurant',description:'A fun action-themed restaurant at Beto Carrero World in partnership with the Nerf brand — serving sandwiches, snacks and quick-service meals in an energetic and colourful setting popular with younger visitors.',topPick:false,type:'Nerf Themed Quick Service',image:'assets/images/beto_carrero_world/food_nerf_restaurant.png',lat:-26.7818,lng:-48.6457,rating:4.0,items:[{name:'Nerf Sandwich',description:'Toasted ham and cheese sandwich',price:18},{name:'Chicken Strips',description:'Crispy chicken strips with dipping sauce',price:22},{name:'Nachos',description:'Tortilla chips with cheese sauce and jalapeños',price:16},{name:'Juice',description:'Fresh tropical fruit juice',price:9}]},
{id:'food_fritz_fritas_restaurant',name:'Fritz Fritas Restaurant',description:'A classic German-Brazilian themed snack restaurant at Beto Carrero World serving the beloved Brazilian street food classic pastel, coxinha, fries and traditional Brazilian snacks. One of the most authentic and popular quick-service options at the park.',topPick:false,type:'Brazilian Street Food',image:'assets/images/beto_carrero_world/food_fritz_fritas_restaurant.png',lat:-26.7820,lng:-48.6459,rating:4.1,items:[{name:'Pastel de Queijo',description:'Classic Brazilian deep-fried pastry with cheese filling',price:12},{name:'Coxinha',description:'Beloved Brazilian chicken croquette',price:10},{name:'Batata Frita',description:'Crispy thick-cut fries with ketchup',price:14},{name:'Suco de Maracuja',description:'Fresh Brazilian passion fruit juice',price:9}]},
{id:'food_10_pasteis_restaurant',name:'10 Pasteis Restaurant',description:'A beloved Brazilian snack bar at Beto Carrero World specialising in the iconic Brazilian pastel — offering a huge variety of fillings from savoury to sweet. The most authentic and popular snack experience at Brazil\'s largest theme park.',topPick:false,type:'Brazilian Pastel Bar',image:'assets/images/beto_carrero_world/food_10_pasteis_restaurant.png',lat:-26.7822,lng:-48.6461,rating:4.2,items:[{name:'Pastel de Carne',description:'Classic Brazilian pastel with seasoned beef filling',price:11},{name:'Pastel de Frango',description:'Brazilian pastel with spiced chicken filling',price:11},{name:'Pastel Doce',description:'Sweet pastel with banana and chocolate filling',price:12},{name:'Caldo de Cana',description:'Fresh Brazilian sugarcane juice',price:8}]},
{id:'food_fini_restaurant',name:'Fini Candy Restaurant',description:'A delightful candy and dessert bar at Beto Carrero World in partnership with the Fini confectionery brand — serving gummies, sweets, ice cream and Brazilian desserts. The most popular sweet treat destination at Brazil\'s largest theme park.',topPick:false,type:'Candy and Desserts',image:'assets/images/beto_carrero_world/food_fini_restaurant.png',lat:-26.7824,lng:-48.6463,rating:4.3,items:[{name:'Fini Gummies Mix',description:'Selection of Fini gummy candies in assorted flavours',price:14},{name:'Soft Serve',description:'Creamy soft serve ice cream in chocolate or vanilla',price:10},{name:'Brigadeiro',description:'Classic Brazilian chocolate truffle',price:6},{name:'Cotton Candy',description:'Freshly made cotton candy',price:8}]}
];
fs.writeFileSync('assets/data/parks/beto_carrero_world/food.json',JSON.stringify(d,null,2),'utf8');
console.log('food.json done, entries:',d.length);