const fs=require('fs');
const d=[
{id:'french_revolution',name:'French Revolution',description:'The flagship roller coaster of Lotte World — French Revolution is a classic looping coaster that sends riders through inversions at speed in the outdoor Adventure area. One of the most iconic and beloved coasters in Korean theme park history and a Lotte World institution since 1989. Min 130cm.',image:'assets/images/lotte_world/french_revolution.png',category:'thrill',topPick:true,lat:37.5111,lng:127.0982,liveWaitMinutes:60,rating:4.6,speedKmh:90,heightM:32,inversions:1,openedYear:1989,minHeightCm:130,temporarilyClosed:false},
{id:'gyro_drop',name:'Gyro Drop',description:'One of the tallest drop towers in Asia — Gyro Drop hoists riders 70 metres above Seoul before releasing them in a terrifying free fall with breathtaking panoramic views of the Lotte World complex and the Han River. A Seoul skyline icon. Min 130cm.',image:'assets/images/lotte_world/gyro_drop.png',category:'thrill',topPick:true,lat:37.5113,lng:127.0984,liveWaitMinutes:50,rating:4.7,speedKmh:0,heightM:70,inversions:0,openedYear:1996,minHeightCm:130,temporarilyClosed:false},
{id:'gyro_swing',name:'Gyro Swing',description:'A massive pendulum swing ride that sends riders soaring back and forth in a full 360-degree arc at thrilling speed — one of the most popular outdoor thrill rides at Lotte World with spectacular views over Seoul. Min 130cm.',image:'assets/images/lotte_world/gyro_swing.png',category:'thrill',topPick:true,lat:37.5114,lng:127.0985,liveWaitMinutes:45,rating:4.5,speedKmh:0,heightM:25,inversions:0,openedYear:1996,minHeightCm:130,temporarilyClosed:false},
{id:'atlantis_adventure',name:'Atlantis Adventure',description:'A thrilling indoor dark ride adventure through the lost city of Atlantis — combining high-speed drops, water effects and elaborate underwater theming in one of the most immersive and exciting indoor attractions in Korean theme park history. Min 120cm.',image:'assets/images/lotte_world/atlantis_adventure.png',category:'thrill',topPick:true,lat:37.5110,lng:127.0981,liveWaitMinutes:55,rating:4.7,speedKmh:0,heightM:0,inversions:0,openedYear:1996,minHeightCm:120,temporarilyClosed:false},
{id:'comet_express',name:'Comet Express',description:'A classic indoor roller coaster that hurtles through the Lotte World Magic Island dome at speed — one of the most beloved family coaster experiences in Korea and a must-ride for first-time visitors to Lotte World. Min 110cm.',image:'assets/images/lotte_world/comet_express.png',category:'thrill',topPick:false,lat:37.5109,lng:127.0980,liveWaitMinutes:40,rating:4.3,speedKmh:70,heightM:20,inversions:0,openedYear:1989,minHeightCm:110,temporarilyClosed:false},
{id:'flume_ride',name:'Flume Ride',description:'A classic log flume water ride that winds through scenic outdoor waterways before a splashing final drop — perfect for warm Seoul days and one of the most relaxing and enjoyable water attractions at Lotte World. Min 100cm.',image:'assets/images/lotte_world/flume_ride.png',category:'family',topPick:false,lat:37.5115,lng:127.0986,liveWaitMinutes:30,rating:4.1,speedKmh:0,heightM:10,inversions:0,openedYear:1989,minHeightCm:100,temporarilyClosed:false},
{id:'pharaohs_fury',name:'Pharaoh\'s Fury',description:'A dramatic indoor boat ride adventure through ancient Egypt — guests sail through elaborate pharaoh tomb scenes, hieroglyphic corridors and dramatic special effects in one of the most atmospheric dark rides at Lotte World. Min 100cm.',image:'assets/images/lotte_world/pharaohs_fury.png',category:'family',topPick:true,lat:37.5108,lng:127.0979,liveWaitMinutes:35,rating:4.4,speedKmh:0,heightM:0,inversions:0,openedYear:1989,minHeightCm:100,temporarilyClosed:false},
{id:'sindbads_adventure',name:'Sindbad\'s Adventure',description:'A magical indoor boat journey through the legendary adventures of Sindbad — featuring colourful animatronic scenes, exotic landscapes and enchanting storytelling in one of the most charming family attractions at Lotte World. Suitable for all ages.',image:'assets/images/lotte_world/sindbads_adventure.png',category:'family',topPick:false,lat:37.5107,lng:127.0978,liveWaitMinutes:25,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:1989,minHeightCm:0,temporarilyClosed:false},
{id:'camelot_carousel',name:'Camelot Carousel',description:'A grand and beautifully decorated classic carousel in the heart of Lotte World Magic Island — one of the most photographed and iconic attractions in the entire park, beloved by families and visitors of all ages. Suitable for all ages.',image:'assets/images/lotte_world/camelot_carousel.png',category:'family',topPick:false,lat:37.5106,lng:127.0977,liveWaitMinutes:15,rating:4.3,speedKmh:0,heightM:0,inversions:0,openedYear:1989,minHeightCm:0,temporarilyClosed:false},
{id:'balloon',name:'Balloon',description:'A gentle hot air balloon ride that lifts guests high above the Lotte World indoor Magic Island dome for breathtaking panoramic views of the entire park from above — one of the most unique and unforgettable perspectives in any theme park in Asia. Suitable for all ages.',image:'assets/images/lotte_world/balloon.png',category:'family',topPick:true,lat:37.5105,lng:127.0976,liveWaitMinutes:20,rating:4.5,speedKmh:0,heightM:30,inversions:0,openedYear:1989,minHeightCm:0,temporarilyClosed:false},
{id:'bumper_cars',name:'Bumper Cars',description:'Classic dodgem bumper cars in the Lotte World indoor area — endlessly entertaining for all ages and one of the most popular family attractions in the park. Perfect for families with children of all ages.',image:'assets/images/lotte_world/bumper_cars.png',category:'family',topPick:false,lat:37.5104,lng:127.0975,liveWaitMinutes:20,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:1989,minHeightCm:0,temporarilyClosed:false},
{id:'ghost_house',name:'Ghost House',description:'A classic haunted house walk-through attraction featuring elaborate spooky scenes, startling special effects and atmospheric horror theming — one of the most popular and talked-about family scare attractions at Lotte World. Min 110cm.',image:'assets/images/lotte_world/ghost_house.png',category:'family',topPick:false,lat:37.5103,lng:127.0974,liveWaitMinutes:25,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:1989,minHeightCm:110,temporarilyClosed:false},
{id:'the_conquistador',name:'The Conquistador',description:'A classic Viking ship pendulum ride that swings guests back and forth at increasing height in one of the most accessible and popular thrill rides at Lotte World. Min 120cm.',image:'assets/images/lotte_world/the_conquistador.png',category:'thrill',topPick:false,lat:37.5116,lng:127.0987,liveWaitMinutes:30,rating:4.2,speedKmh:0,heightM:20,inversions:0,openedYear:1989,minHeightCm:120,temporarilyClosed:false},
{id:'magic_town_parade',name:'Magic Town Parade',description:'The most spectacular daily parade at any Korean theme park — Magic Town Parade features dozens of elaborate floats, costumed performers, music and dancing through the Lotte World Magic Island indoor dome in a breathtaking celebration of colour and spectacle. Suitable for all ages.',image:'assets/images/lotte_world/magic_town_parade.png',category:'family',topPick:true,lat:37.5105,lng:127.0976,liveWaitMinutes:0,rating:4.8,speedKmh:0,heightM:0,inversions:0,openedYear:1989,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/lotte_world/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('attractions.json done, entries:',d.length);