const fs=require('fs');
const d=[
{id:'big_dipper',name:'Big Dipper',description:'The centrepiece thrill coaster at Luna Park Sydney — a classic wooden roller coaster delivering genuine old-school thrills with a spectacular backdrop of Sydney Harbour, the Harbour Bridge and the Opera House. Riding a wooden coaster with one of the most iconic views in the world is an experience unique to Luna Park Sydney. Min 130cm.',image:'assets/images/luna_park_sydney/big_dipper.png',category:'thrill',topPick:true,lat:-33.8484,lng:151.2100,liveWaitMinutes:35,rating:4.6,speedKmh:75,heightM:24,inversions:0,openedYear:2004,minHeightCm:130,temporarilyClosed:false},
{id:'sledgehammer',name:'Sledgehammer',description:'The most intense thrill ride at Luna Park Sydney — Sledgehammer is a spectacular high-speed over-the-top swing ride that launches riders over and around a central tower delivering breathtaking Sydney Harbour views at the apex of each swing. One of the most dramatic flat rides in Australia. Min 130cm.',image:'assets/images/luna_park_sydney/sledgehammer.png',category:'thrill',topPick:true,lat:-33.8486,lng:151.2102,liveWaitMinutes:25,rating:4.7,speedKmh:0,heightM:35,inversions:0,openedYear:2010,minHeightCm:130,temporarilyClosed:false},
{id:'boomerang',name:'Boomerang',description:'A high-intensity suspended looping coaster that sends riders forward and backward through a complete loop and corkscrew — delivering intense inversions and powerful forces in a compact and surprisingly ferocious layout. One of the most popular thrill coasters at Luna Park Sydney. Min 130cm.',image:'assets/images/luna_park_sydney/boomerang.png',category:'thrill',topPick:true,lat:-33.8488,lng:151.2104,liveWaitMinutes:30,rating:4.5,speedKmh:80,heightM:26,inversions:6,openedYear:2004,minHeightCm:130,temporarilyClosed:false},
{id:'spider',name:'Spider',description:'A classic spinning flat ride delivering intense rotational forces as riders are whirled in multiple spinning gondolas on extending arms — one of the most popular and reliable thrill attractions at Luna Park Sydney with spectacular harbour views. Min 130cm.',image:'assets/images/luna_park_sydney/spider.png',category:'thrill',topPick:false,lat:-33.8490,lng:151.2106,liveWaitMinutes:20,rating:4.2,speedKmh:0,heightM:14,inversions:0,openedYear:2004,minHeightCm:130,temporarilyClosed:false},
{id:'ranger',name:'Ranger',description:'A classic pendulum swing ride delivering soaring thrills with spectacular Sydney Harbour views at the apex of each swing — one of the most scenic flat rides in Australia with the iconic Harbour Bridge as the backdrop. Min 120cm.',image:'assets/images/luna_park_sydney/ranger.png',category:'thrill',topPick:false,lat:-33.8492,lng:151.2108,liveWaitMinutes:20,rating:4.3,speedKmh:0,heightM:22,inversions:0,openedYear:2004,minHeightCm:120,temporarilyClosed:false},
{id:'rotor',name:'Rotor',description:'A legendary spinning drum ride that pins riders to the walls through centrifugal force as the floor drops away — the Rotor is a true fairground classic and one of the last operating Rotor rides in Australia. A uniquely disorientating and unforgettable experience. Min 120cm.',image:'assets/images/luna_park_sydney/rotor.png',category:'thrill',topPick:true,lat:-33.8494,lng:151.2110,liveWaitMinutes:20,rating:4.5,speedKmh:0,heightM:8,inversions:0,openedYear:1935,minHeightCm:120,temporarilyClosed:false},
{id:'wild_mouse',name:'Wild Mouse',description:'A classic wild mouse coaster delivering sharp unexpected turns and sudden drops in a compact layout — Wild Mouse is a deceptively thrilling coaster that surprises first-time riders with its intensity. A beloved Luna Park institution. Min 120cm.',image:'assets/images/luna_park_sydney/wild_mouse.png',category:'thrill',topPick:false,lat:-33.8496,lng:151.2112,liveWaitMinutes:25,rating:4.3,speedKmh:55,heightM:12,inversions:0,openedYear:2004,minHeightCm:120,temporarilyClosed:false},
{id:'ferris_wheel',name:'Ferris Wheel',description:'A beautiful observation wheel delivering the most spectacular views of Sydney Harbour available at any theme park in the world — the Luna Park Ferris Wheel with the Harbour Bridge and Opera House as the backdrop creates the ultimate Sydney photography experience. Suitable for all ages.',image:'assets/images/luna_park_sydney/ferris_wheel.png',category:'family',topPick:true,lat:-33.8482,lng:151.2098,liveWaitMinutes:15,rating:4.8,speedKmh:0,heightM:35,inversions:0,openedYear:2004,minHeightCm:0,temporarilyClosed:false},
{id:'harbourview_carousel',name:'Harbourview Carousel',description:'A magnificently restored heritage carousel with breathtaking views of Sydney Harbour — the most beautiful and atmospheric carousel in Australia, set against the backdrop of the Harbour Bridge and city skyline. A truly unique and memorable experience for all ages. Suitable for all ages.',image:'assets/images/luna_park_sydney/harbourview_carousel.png',category:'family',topPick:true,lat:-33.8480,lng:151.2096,liveWaitMinutes:10,rating:4.6,speedKmh:0,heightM:0,inversions:0,openedYear:1935,minHeightCm:0,temporarilyClosed:false},
{id:'coney_island',name:'Coney Island',description:'Luna Park Sydney\'s legendary heritage fun house — a magnificent heritage-listed attraction that has entertained visitors since 1935 featuring the Rotor, slides, distorting mirrors, moving obstacles and classic fairground fun. Coney Island is the soul of Luna Park and one of the most historically significant amusement attractions in Australia. Suitable for all ages.',image:'assets/images/luna_park_sydney/coney_island.png',category:'family',topPick:true,lat:-33.8484,lng:151.2100,liveWaitMinutes:15,rating:4.7,speedKmh:0,heightM:0,inversions:0,openedYear:1935,minHeightCm:0,temporarilyClosed:false},
{id:'house_of_mirrors',name:'House of Mirrors',description:'A classic fairground house of mirrors delivering endless fun and laughter as guests navigate through elaborate mirror mazes and distorting reflection rooms — one of the most popular and photogenic attractions at Luna Park Sydney. Suitable for all ages.',image:'assets/images/luna_park_sydney/house_of_mirrors.png',category:'family',topPick:false,lat:-33.8486,lng:151.2102,liveWaitMinutes:10,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:1935,minHeightCm:0,temporarilyClosed:false},
{id:'tango_train',name:'Tango Train',description:'A classic family coaster delivering gentle but fun hills and turns — one of the most popular and accessible coasters for families with older children at Luna Park Sydney. Min 100cm.',image:'assets/images/luna_park_sydney/tango_train.png',category:'family',topPick:false,lat:-33.8488,lng:151.2104,liveWaitMinutes:20,rating:4.1,speedKmh:45,heightM:10,inversions:0,openedYear:2004,minHeightCm:100,temporarilyClosed:false},
{id:'tumblebug',name:'Tumblebug',description:'A charming vintage spinning family ride — the Tumblebug is a heritage attraction that has delighted generations of Luna Park visitors and remains one of the most beloved and nostalgic rides in the park. Min 90cm.',image:'assets/images/luna_park_sydney/tumblebug.png',category:'family',topPick:false,lat:-33.8490,lng:151.2106,liveWaitMinutes:10,rating:4.1,speedKmh:0,heightM:5,inversions:0,openedYear:1935,minHeightCm:90,temporarilyClosed:false},
{id:'tea_cups',name:'Tea Cups',description:'Classic spinning teacup ride where guests control the spin of their own cup — a universally loved family attraction that has been entertaining visitors at Luna Park for generations. Suitable for all ages.',image:'assets/images/luna_park_sydney/tea_cups.png',category:'family',topPick:false,lat:-33.8492,lng:151.2108,liveWaitMinutes:10,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:2004,minHeightCm:0,temporarilyClosed:false},
{id:'dodgem_cars',name:'Dodgem Cars',description:'Classic electric dodgem bumper cars delivering endless fun — one of the most universally enjoyed and accessible attractions at Luna Park Sydney. Suitable for all ages.',image:'assets/images/luna_park_sydney/dodgem_cars.png',category:'family',topPick:false,lat:-33.8494,lng:151.2110,liveWaitMinutes:15,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:2004,minHeightCm:0,temporarilyClosed:false},
{id:'little_nipper',name:'Little Nipper',description:'A dedicated young children\'s zone featuring gentle rides scaled perfectly for the youngest visitors — Little Nipper is a beloved and essential part of the Luna Park Sydney experience for families with toddlers and young children. Suitable for all ages.',image:'assets/images/luna_park_sydney/little_nipper.png',category:'family',topPick:false,lat:-33.8496,lng:151.2112,liveWaitMinutes:5,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:2004,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/luna_park_sydney/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('attractions.json done, entries:',d.length);