const fs=require('fs');
function readJson(p){let r=fs.readFileSync(p,'utf8');if(r.charCodeAt(0)===0xFEFF)r=r.slice(1);return JSON.parse(r);}

const attractions=[
{id:'titan',name:'Titan',description:'The most dominant and beloved roller coaster at Six Flags Over Texas — Titan is a spectacular Morgan hyper coaster reaching 174 km/h down a breathtaking 68-metre first drop through a dramatic layout of helices, speed hills and banking turns. One of the tallest and fastest roller coasters in Texas and a must-ride at any Arlington theme park visit. Min 137cm.',image:'assets/images/six_flags_over_texas/titan.png',category:'thrill',topPick:true,lat:32.7572,lng:-97.0694,liveWaitMinutes:60,rating:4.7,speedKmh:174,heightM:68,inversions:0,openedYear:2001,minHeightCm:137,temporarilyClosed:false},
{id:'mr_freeze',name:'Mr. Freeze: Reverse Blast',description:'A legendary launched coaster at Six Flags Over Texas launching riders backwards at 96 km/h through a spectacular twisted layout and a towering vertical spike. One of the most intense and unique launched coasters in Texas. Min 137cm.',image:'assets/images/six_flags_over_texas/mr_freeze.png',category:'thrill',topPick:true,lat:32.7568,lng:-97.0689,liveWaitMinutes:45,rating:4.6,speedKmh:96,heightM:55,inversions:0,openedYear:1998,minHeightCm:137,temporarilyClosed:false},
{id:'shockwave',name:'Shockwave',description:'A classic and beloved stand-up loop coaster at Six Flags Over Texas delivering one of the largest loops of any stand-up coaster in the world. A beloved Texas coaster institution since 1978 and one of the most historically significant coasters in the Lone Star State. Min 137cm.',image:'assets/images/six_flags_over_texas/shockwave.png',category:'thrill',topPick:false,lat:32.7576,lng:-97.0698,liveWaitMinutes:25,rating:4.2,speedKmh:96,heightM:40,inversions:2,openedYear:1978,minHeightCm:137,temporarilyClosed:false},
{id:'batman_the_ride',name:'Batman The Ride',description:'A classic and beloved Batman-themed inverted coaster at Six Flags Over Texas delivering five inversions at 80 km/h through a spectacular themed layout. One of the most popular and rerideable inverted coasters in the Dallas-Fort Worth area. Min 137cm.',image:'assets/images/six_flags_over_texas/batman_the_ride.png',category:'thrill',topPick:false,lat:32.7580,lng:-97.0702,liveWaitMinutes:30,rating:4.4,speedKmh:80,heightM:30,inversions:5,openedYear:1999,minHeightCm:137,temporarilyClosed:false},
{id:'joker',name:'The Joker',description:'A spectacular free-fly coaster at Six Flags Over Texas where seats rotate independently through a twisted layout. A uniquely disorienting and entertaining coaster experience in Arlington. Min 122cm.',image:'assets/images/six_flags_over_texas/joker.png',category:'thrill',topPick:false,lat:32.7565,lng:-97.0685,liveWaitMinutes:35,rating:4.4,speedKmh:80,heightM:30,inversions:4,openedYear:2016,minHeightCm:122,temporarilyClosed:false},
{id:'tormenta',name:'Tormenta',description:'A spectacular new-generation spinning coaster at Six Flags Over Texas delivering intense spinning through dramatic banking turns and drops. One of the newest and most exciting additions to the Texas coaster lineup. Min 122cm.',image:'assets/images/six_flags_over_texas/tormenta.png',category:'thrill',topPick:true,lat:32.7562,lng:-97.0682,liveWaitMinutes:40,rating:4.5,speedKmh:80,heightM:25,inversions:0,openedYear:2023,minHeightCm:122,temporarilyClosed:false},
{id:'superman_tower',name:'Superman Tower of Power',description:'A terrifying open-air drop tower at Six Flags Over Texas lifting riders to the top before plunging them back down at terrifying speed with extraordinary views over Arlington and the Dallas-Fort Worth skyline. Min 122cm.',image:'assets/images/six_flags_over_texas/superman_tower.png',category:'thrill',topPick:false,lat:32.7578,lng:-97.0695,liveWaitMinutes:20,rating:4.3,speedKmh:0,heightM:61,inversions:0,openedYear:2000,minHeightCm:122,temporarilyClosed:false},
{id:'sky_screamer',name:'Texas SkyScreamer',description:'The tallest swing ride in the world at Six Flags Over Texas — Texas SkyScreamer lifts riders 122 metres above the ground for breathtaking panoramic views over Arlington, Dallas and Fort Worth. The most scenic attraction at any Texas theme park. Min 122cm.',image:'assets/images/six_flags_over_texas/sky_screamer.png',category:'thrill',topPick:true,lat:32.7560,lng:-97.0680,liveWaitMinutes:25,rating:4.5,speedKmh:0,heightM:122,inversions:0,openedYear:2013,minHeightCm:122,temporarilyClosed:false},
{id:'pandemonium',name:'Pandemonium',description:'A fun and popular spinning wild mouse coaster at Six Flags Over Texas with freely rotating cars through tight turns and drops. A fun unpredictable family experience. Min 107cm.',image:'assets/images/six_flags_over_texas/pandemonium.png',category:'family',topPick:false,lat:32.7572,lng:-97.0678,liveWaitMinutes:20,rating:4.1,speedKmh:48,heightM:18,inversions:0,openedYear:2006,minHeightCm:107,temporarilyClosed:false},
{id:'runaway_mine_train',name:'Runaway Mine Train',description:'A classic and beloved mine train coaster at Six Flags Over Texas and one of the most charming and historically significant family coasters in the Dallas-Fort Worth area. The Runaway Mine Train has been thrilling Texas families since 1966. Min 107cm.',image:'assets/images/six_flags_over_texas/runaway_mine_train.png',category:'family',topPick:false,lat:32.7580,lng:-97.0688,liveWaitMinutes:15,rating:4.1,speedKmh:72,heightM:21,inversions:0,openedYear:1966,minHeightCm:107,temporarilyClosed:false},
{id:'judge_roy_scream',name:'Judge Roy Scream',description:'A beloved classic wooden roller coaster at Six Flags Over Texas and one of the most charming and entertaining wooden coasters in Texas. Judge Roy Scream has been delighting Dallas-Fort Worth families since 1980. Min 107cm.',image:'assets/images/six_flags_over_texas/judge_roy_scream.png',category:'thrill',topPick:false,lat:32.7575,lng:-97.0692,liveWaitMinutes:20,rating:4.1,speedKmh:88,heightM:27,inversions:0,openedYear:1980,minHeightCm:107,temporarilyClosed:false},
{id:'oil_derrick',name:'Oil Derrick',description:'A classic observation tower at Six Flags Over Texas offering spectacular panoramic views over Arlington and the Dallas-Fort Worth Metroplex. One of the most scenic and photogenic attractions at any Texas theme park. Suitable for all ages.',image:'assets/images/six_flags_over_texas/oil_derrick.png',category:'family',topPick:false,lat:32.7565,lng:-97.0697,liveWaitMinutes:10,rating:4.2,speedKmh:0,heightM:61,inversions:0,openedYear:1969,minHeightCm:0,temporarilyClosed:false},
{id:'looney_tunes_usa',name:'Looney Tunes USA',description:'A beloved and extensively themed Looney Tunes children and family area at Six Flags Over Texas featuring Bugs Bunny, Tweety Bird, Daffy Duck and friends across multiple family rides, shows and character meet-and-greets. Suitable for all ages.',image:'assets/images/six_flags_over_texas/looney_tunes_usa.png',category:'family',topPick:true,lat:32.7582,lng:-97.0705,liveWaitMinutes:0,rating:4.3,speedKmh:0,heightM:0,inversions:0,openedYear:1989,minHeightCm:0,temporarilyClosed:false},
{id:'yosemite_sams',name:"Yosemite Sam's Gold River Adventure",description:'A beloved classic dark boat ride at Six Flags Over Texas featuring Yosemite Sam and Bugs Bunny through a fun Western-themed adventure. A beloved park classic and one of the most charming dark rides at any Texas theme park. Suitable for all ages.',image:'assets/images/six_flags_over_texas/yosemite_sams.png',category:'family',topPick:false,lat:32.7578,lng:-97.0700,liveWaitMinutes:15,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:1971,minHeightCm:0,temporarilyClosed:false},
{id:'anti_gravity',name:'Anti-Gravity',description:'A thrilling spinning flat ride at Six Flags Over Texas delivering wild spinning rotations at high speed. One of the most intense flat rides in the Dallas-Fort Worth area. Min 107cm.',image:'assets/images/six_flags_over_texas/superman_tower.png',category:'thrill',topPick:false,lat:32.7570,lng:-97.0690,liveWaitMinutes:15,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:2005,minHeightCm:107,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/six_flags_over_texas/attractions.json',JSON.stringify(attractions,null,2),'utf8');
console.log('SFOT attractions done:',attractions.length);

const food=[
{id:'food_jbs_smokehouse_barbeque',name:"JB's Smokehouse Barbeque",description:'The most popular and beloved dining destination at Six Flags Over Texas — JBs Smokehouse Barbeque is a magnificent Texas BBQ restaurant serving authentic smoked brisket, ribs and sausage with classic Texas sides. The most satisfying and quintessentially Texan dining experience at any Arlington theme park.',topPick:true,type:'Texas BBQ',image:'assets/images/six_flags_over_texas/food_jbs_smokehouse_barbeque.png',lat:32.7572,lng:-97.0692,rating:4.5,items:[{name:'Smoked Brisket Plate',description:'Classic Texas smoked brisket with beans and coleslaw',price:20},{name:'Pork Ribs',description:'Classic slow-smoked pork ribs with BBQ sauce',price:22},{name:'Combo Plate',description:'Brisket and sausage combo with two classic Texas sides',price:22},{name:'Sweet Tea',description:'Classic Southern sweet iced tea',price:4}]},
{id:'food_grannys_grill',name:"Granny's Grill",description:'A beloved and charming home-cooking themed restaurant at Six Flags Over Texas serving classic American comfort food including chicken tenders, burgers and classic sides in a warm and welcoming atmosphere.',topPick:false,type:'American Home Cooking',image:'assets/images/six_flags_over_texas/food_grannys_grill.png',lat:32.7576,lng:-97.0696,rating:4.2,items:[{name:'Chicken Tenders',description:'Classic crispy chicken tenders with honey mustard and fries',price:15},{name:'Classic Burger',description:'Classic beef burger with cheese, lettuce and tomato',price:15},{name:'Mac and Cheese',description:'Classic creamy mac and cheese',price:10},{name:'Lemonade',description:'Fresh squeezed lemonade',price:5}]},
{id:'food_dry_hole_charlies',name:"Dry Hole Charlie's",description:'A fun and popular Western-themed quick-service restaurant at Six Flags Over Texas serving classic Texan comfort food including nachos, corn dogs and classic Texas snacks in an entertaining atmosphere.',topPick:false,type:'Texas Western',image:'assets/images/six_flags_over_texas/food_dry_hole_charlies.png',lat:32.7568,lng:-97.0688,rating:4.0,items:[{name:'Nachos',description:'Classic loaded nachos with cheese jalapeños and salsa',price:11},{name:'Corn Dog',description:'Classic deep-fried corn dog',price:8},{name:'Chili Cheese Fries',description:'Thick fries with chili and melted cheese',price:10},{name:'Soft Drink',description:'Large fountain drink',price:4}]},
{id:'food_all_american_cafe',name:'All American Cafe',description:'A classic and popular American quick-service cafe at Six Flags Over Texas serving burgers, chicken sandwiches and classic American comfort food. One of the most convenient and frequently visited dining destinations at the park.',topPick:false,type:'American Quick Service',image:'assets/images/six_flags_over_texas/food_all_american_cafe.png',lat:32.7580,lng:-97.0700,rating:4.1,items:[{name:'Classic Burger',description:'Classic beef burger with cheese, lettuce and tomato',price:15},{name:'Chicken Sandwich',description:'Classic crispy chicken sandwich with fries',price:14},{name:'Hot Dog',description:'Classic beef hot dog with mustard and relish',price:9},{name:'Soft Drink',description:'Large fountain drink',price:4}]},
{id:'food_funnel_cakes',name:'Funnel Cakes',description:'The most beloved sweet treat at Six Flags Over Texas — classic deep-fried funnel cakes with powdered sugar, strawberries or Nutella. The quintessential American theme park dessert experience.',topPick:true,type:'American Desserts',image:'assets/images/six_flags_over_texas/food_funnel_cakes.png',lat:32.7565,lng:-97.0694,rating:4.4,items:[{name:'Classic Funnel Cake',description:'Classic deep-fried funnel cake with powdered sugar',price:9},{name:'Strawberry Funnel Cake',description:'Funnel cake with fresh strawberry topping',price:11},{name:'Nutella Funnel Cake',description:'Funnel cake with Nutella and powdered sugar',price:12},{name:'Lemonade',description:'Fresh squeezed lemonade',price:5}]}
];
fs.writeFileSync('assets/data/parks/six_flags_over_texas/food.json',JSON.stringify(food,null,2),'utf8');
console.log('SFOT food done:',food.length);

const hotels=[
{id:'hotel_live_oak_marriott',name:'Live Oak Marriott Arlington',description:'A magnificent and recently renovated Marriott hotel directly adjacent to Six Flags Over Texas — the Live Oak Marriott Arlington offers elegant rooms, a spectacular pool and the finest hotel experience steps from the park.',image:'assets/images/six_flags_over_texas/hotel_live_oak_marriott.png',lat:32.7548,lng:-97.0712,rating:4.5,topPick:true,website:'https://www.marriott.com',rooms:[{key:'standard_room',name:'Standard Room',description:'Elegant room with free WiFi and pool access.',pricePerNight:180,breakfastIncluded:false},{key:'king_room',name:'King Room',description:'Premium king room with upgraded views.',pricePerNight:220,breakfastIncluded:false},{key:'suite',name:'Suite',description:'Spacious suite with living area and breakfast.',pricePerNight:360,breakfastIncluded:true}]},
{id:'hotel_sheraton_arlington',name:'Sheraton Arlington Hotel',description:'A magnificent and well-regarded Sheraton hotel in Arlington near Six Flags Over Texas — offering elegant rooms, a spectacular pool, outstanding dining and excellent access to both Six Flags and the Dallas Cowboys AT&T Stadium.',image:'assets/images/six_flags_over_texas/hotel_sheraton_arlington.png',lat:32.7365,lng:-97.1081,rating:4.4,topPick:true,website:'https://www.marriott.com/hotels/travel/dalarar-sheraton-arlington-hotel/',rooms:[{key:'standard_room',name:'Standard Room',description:'Classic room with free WiFi and pool access.',pricePerNight:160,breakfastIncluded:false},{key:'deluxe_room',name:'Deluxe Room',description:'Premium room with upgraded views.',pricePerNight:200,breakfastIncluded:false},{key:'suite',name:'Suite',description:'Spacious suite with living area.',pricePerNight:320,breakfastIncluded:true}]},
{id:'hotel_hyatt_place_arlington',name:'Hyatt Place Arlington',description:'A comfortable and convenient Hyatt Place hotel near Six Flags Over Texas offering modern rooms, free breakfast and easy access to both the park and the Dallas Cowboys AT&T Stadium.',image:'assets/images/six_flags_over_texas/hotel_hyatt_place_arlington.png',lat:32.7425,lng:-97.0982,rating:4.2,topPick:false,website:'https://www.hyatt.com',rooms:[{key:'standard_room',name:'Standard Room',description:'Modern room with free WiFi and breakfast.',pricePerNight:140,breakfastIncluded:true},{key:'king_room',name:'King Room',description:'Spacious king room with breakfast.',pricePerNight:165,breakfastIncluded:true},{key:'suite',name:'Suite',description:'Spacious suite with living area and breakfast.',pricePerNight:240,breakfastIncluded:true}]},
{id:'hotel_hilton_arlington',name:'Hilton Arlington',description:'A reliable and comfortable Hilton hotel near Six Flags Over Texas offering pleasant rooms, a pool and easy access to the park, AT&T Stadium and the Dallas-Fort Worth entertainment district.',image:'assets/images/six_flags_over_texas/hotel_hilton_arlington.png',lat:32.7352,lng:-97.1025,rating:4.2,topPick:false,website:'https://www.hilton.com',rooms:[{key:'standard_room',name:'Standard Room',description:'Comfortable room with free WiFi and pool access.',pricePerNight:130,breakfastIncluded:false},{key:'king_room',name:'King Room',description:'Spacious king room with upgraded views.',pricePerNight:155,breakfastIncluded:false},{key:'suite',name:'Suite',description:'Spacious suite with living area.',pricePerNight:240,breakfastIncluded:true}]}
];
fs.writeFileSync('assets/data/parks/six_flags_over_texas/hotels.json',JSON.stringify(hotels,null,2),'utf8');
console.log('SFOT hotels done:',hotels.length);

const pe={id:"six_flags_over_texas",thumbnailAsset:"assets/images/six_flags_over_texas/park_thumbnail.png",tailAsset:"",name:"Six Flags Over Texas",type:"Theme Park",entryPrice:{child:59,adult:74},currency:"USD",openingHours:"10:30 - 21:00",lng:-97.0694,country:"USA",city:"Arlington, Texas",ticketsUrl:"https://www.sixflags.com/overtexas/tickets",queueTimesId:0};
const ie={id:"six_flags_over_texas",name:"Six Flags Over Texas",city:"Arlington, Texas",country:"USA",type:"Theme Park",lat:32.7572,lng:-97.0694,thumbnail:"assets/images/six_flags_over_texas/park_thumbnail.png",website:"https://www.sixflags.com/overtexas",ticketsUrl:"https://www.sixflags.com/overtexas/tickets",detailAsset:"",openingHours:"10:30 - 21:00",entryPrices:{adult:74,child:59},currency:"USD",queueTimesId:0};
const parks=readJson('assets/data/parks.json');
if(!parks.find(p=>p.id==='six_flags_over_texas')){parks.push(pe);fs.writeFileSync('assets/data/parks.json',JSON.stringify(parks,null,4),'utf8');console.log('parks.json:',parks.length);}
const index=readJson('assets/data/parks/parks_index.json');
if(!index.find(p=>p.id==='six_flags_over_texas')){index.push(ie);fs.writeFileSync('assets/data/parks/parks_index.json',JSON.stringify(index,null,4),'utf8');console.log('parks_index.json:',index.length);}