const fs=require('fs');
const d=[
{id:'stratosfear',name:'Stratosfear',description:'The most thrilling ride at Rainbow\'s End — Stratosfear is a towering 40-metre giant swing that spins riders at high speed while simultaneously swinging them back and forth, delivering breathtaking views over Auckland and the surrounding landscape. One of the most intense flat rides in New Zealand. Min 130cm.',image:'assets/images/rainbows_end/stratosfear.png',category:'thrill',topPick:true,lat:-36.9001,lng:174.8613,liveWaitMinutes:30,rating:4.7,speedKmh:0,heightM:40,inversions:0,openedYear:2008,minHeightCm:130,temporarilyClosed:false},
{id:'fearfall',name:'Fear Fall',description:'A classic drop tower rising 25 metres above Rainbow\'s End — riders are raised to the top and then released in a sudden free fall delivering a burst of adrenaline and spectacular views over South Auckland. One of the most popular thrill attractions in New Zealand. Min 130cm.',image:'assets/images/rainbows_end/fearfall.png',category:'thrill',topPick:true,lat:-36.9003,lng:174.8615,liveWaitMinutes:25,rating:4.5,speedKmh:0,heightM:25,inversions:0,openedYear:1994,minHeightCm:130,temporarilyClosed:false},
{id:'corkscrew_coaster',name:'Corkscrew Coaster',description:'New Zealand\'s only corkscrew roller coaster — a classic looping coaster delivering two corkscrew inversions and genuine thrill sensations. The Corkscrew has been the iconic centrepiece of Rainbow\'s End since 1994 and remains the most loved coaster in New Zealand. Min 130cm.',image:'assets/images/rainbows_end/corkscrew_coaster.png',category:'thrill',topPick:true,lat:-36.9005,lng:174.8617,liveWaitMinutes:35,rating:4.6,speedKmh:75,heightM:22,inversions:2,openedYear:1994,minHeightCm:130,temporarilyClosed:false},
{id:'invader',name:'Invader',description:'A high-speed spinning coaster that delivers intense rotational forces through a dynamic layout — Invader is one of the most popular thrill coasters at Rainbow\'s End and a firm favourite with adrenaline seekers visiting New Zealand\'s premier theme park. Min 120cm.',image:'assets/images/rainbows_end/invader.png',category:'thrill',topPick:false,lat:-36.9007,lng:174.8619,liveWaitMinutes:25,rating:4.3,speedKmh:70,heightM:16,inversions:0,openedYear:2005,minHeightCm:120,temporarilyClosed:false},
{id:'power_surge',name:'Power Surge',description:'An intense spinning flat ride delivering powerful rotational forces as riders are spun in multiple axes simultaneously — one of the most disorienting and thrilling flat rides at Rainbow\'s End and popular with thrill-seeking teenagers. Min 130cm.',image:'assets/images/rainbows_end/power_surge.png',category:'thrill',topPick:false,lat:-36.9009,lng:174.8621,liveWaitMinutes:20,rating:4.2,speedKmh:0,heightM:12,inversions:0,openedYear:2000,minHeightCm:130,temporarilyClosed:false},
{id:'gold_rush',name:'Gold Rush',description:'An exciting and fast family coaster themed to the New Zealand gold rush — Gold Rush whisks riders through a dynamic layout of hills and turns delivering genuine family thrills that are accessible to older children. One of the most popular family coasters at Rainbow\'s End. Min 110cm.',image:'assets/images/rainbows_end/gold_rush.png',category:'thrill',topPick:false,lat:-36.9011,lng:174.8623,liveWaitMinutes:20,rating:4.2,speedKmh:60,heightM:14,inversions:0,openedYear:1994,minHeightCm:110,temporarilyClosed:false},
{id:'log_flume',name:'Log Flume',description:'A classic log flume water ride through scenic waterways with a splashing final drop — a beloved New Zealand family institution at Rainbow\'s End. Perfect for hot Auckland days and one of the most popular rides in the park for all ages. Min 100cm.',image:'assets/images/rainbows_end/log_flume.png',category:'family',topPick:true,lat:-36.9013,lng:174.8625,liveWaitMinutes:30,rating:4.4,speedKmh:0,heightM:12,inversions:0,openedYear:1994,minHeightCm:100,temporarilyClosed:false},
{id:'motion_master',name:'Motion Master',description:'An immersive 4D motion simulator theatre taking audiences on exciting adventures — featuring moving seats, surround sound and spectacular visual effects that make it one of the most entertaining all-ages experiences at Rainbow\'s End. Suitable for all ages.',image:'assets/images/rainbows_end/motion_master.png',category:'family',topPick:false,lat:-36.9015,lng:174.8627,liveWaitMinutes:15,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:1997,minHeightCm:0,temporarilyClosed:false},
{id:'pirate_ship',name:'Pirate Ship',description:'A classic Viking ship pendulum ride swinging to increasing heights — a beloved family thrill experience and one of the most accessible and popular attractions at Rainbow\'s End. Min 110cm.',image:'assets/images/rainbows_end/pirate_ship.png',category:'thrill',topPick:false,lat:-36.9017,lng:174.8629,liveWaitMinutes:15,rating:4.1,speedKmh:0,heightM:18,inversions:0,openedYear:1994,minHeightCm:110,temporarilyClosed:false},
{id:'wave_swinger',name:'Wave Swinger',description:'A classic flying chairs swing ride lifting guests high into the air on spinning chains — one of the most joyful and iconic family rides at Rainbow\'s End. Min 110cm.',image:'assets/images/rainbows_end/wave_swinger.png',category:'family',topPick:false,lat:-36.9019,lng:174.8631,liveWaitMinutes:15,rating:4.1,speedKmh:0,heightM:14,inversions:0,openedYear:1994,minHeightCm:110,temporarilyClosed:false},
{id:'bumper_boats',name:'Bumper Boats',description:'A fun and splashy bumper boat experience where guests navigate small motorised boats and attempt to drench each other — one of the most popular summer attractions for families with children at Rainbow\'s End. Min 100cm.',image:'assets/images/rainbows_end/bumper_boats.png',category:'family',topPick:false,lat:-36.9021,lng:174.8633,liveWaitMinutes:20,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:1994,minHeightCm:100,temporarilyClosed:false},
{id:'dodgem_cars',name:'Dodgem Cars',description:'Classic electric dodgem bumper cars delivering endless fun for all ages — one of the most universally enjoyed and accessible attractions at Rainbow\'s End, loved by visitors of every generation. Suitable for all ages.',image:'assets/images/rainbows_end/dodgem_cars.png',category:'family',topPick:false,lat:-36.9023,lng:174.8635,liveWaitMinutes:10,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:1994,minHeightCm:0,temporarilyClosed:false},
{id:'enchanted_forest',name:'Enchanted Forest',description:'A magical and beautifully themed dark ride journey through an enchanted fairy tale forest — featuring elaborate animatronic characters, whimsical scenes and gentle movement that makes it the most beloved family ride for young children at Rainbow\'s End. Suitable for all ages.',image:'assets/images/rainbows_end/enchanted_forest.png',category:'family',topPick:true,lat:-36.9025,lng:174.8637,liveWaitMinutes:20,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:1994,minHeightCm:0,temporarilyClosed:false},
{id:'little_legends_zone',name:'Little Legends Zone',description:'A dedicated toddler and young children\'s zone featuring gentle rides, soft play areas and interactive activities scaled perfectly for the youngest visitors — the most family-friendly area at Rainbow\'s End and an essential destination for families with children under 6. Suitable for all ages.',image:'assets/images/rainbows_end/little_legends_zone.png',category:'family',topPick:false,lat:-36.9027,lng:174.8639,liveWaitMinutes:0,rating:4.3,speedKmh:0,heightM:0,inversions:0,openedYear:2005,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/rainbows_end/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('attractions.json done, entries:',d.length);