const fs=require('fs');
function readJson(p){let r=fs.readFileSync(p,'utf8');if(r.charCodeAt(0)===0xFEFF)r=r.slice(1);return JSON.parse(r);}

const attractions=[
{id:'iron_rattler',name:'Iron Rattler',description:'The most spectacular and beloved roller coaster at Six Flags Fiesta Texas — Iron Rattler is a legendary RMC hybrid coaster built on the skeleton of the original Rattler wooden coaster, delivering an extraordinary beyond-vertical drop into a quarry wall and relentless airtime through a breathtaking layout. Consistently voted one of the greatest hybrid coasters in the world. Min 122cm.',image:'assets/images/six_flags_fiesta_texas/iron_rattler.png',category:'thrill',topPick:true,lat:29.6025,lng:-98.6109,liveWaitMinutes:65,rating:4.9,speedKmh:111,heightM:54,inversions:1,openedYear:2013,minHeightCm:122,temporarilyClosed:false},
{id:'superman_krypton',name:'Superman: Krypton Coaster',description:'A spectacular and beloved floorless coaster at Six Flags Fiesta Texas delivering six inversions at 112 km/h over a dramatic quarry landscape. One of the finest floorless coasters in the United States and a must-ride at any San Antonio theme park visit. Min 137cm.',image:'assets/images/six_flags_fiesta_texas/superman_krypton.png',category:'thrill',topPick:true,lat:29.6030,lng:-98.6115,liveWaitMinutes:50,rating:4.7,speedKmh:112,heightM:51,inversions:6,openedYear:2000,minHeightCm:137,temporarilyClosed:false},
{id:'wonder_woman',name:'Wonder Woman Golden Lasso Coaster',description:'A spectacular single-rail coaster at Six Flags Fiesta Texas — Wonder Woman Golden Lasso Coaster is the first single-rail coaster in the world, delivering an extraordinary riding experience through a unique layout where riders straddle a single rail with legs dangling freely. One of the most innovative and unique coasters at any American theme park. Min 122cm.',image:'assets/images/six_flags_fiesta_texas/wonder_woman.png',category:'thrill',topPick:true,lat:29.6018,lng:-98.6105,liveWaitMinutes:55,rating:4.6,speedKmh:90,heightM:30,inversions:0,openedYear:2018,minHeightCm:122,temporarilyClosed:false},
{id:'poltergeist',name:'Poltergeist',description:'A legendary launched coaster at Six Flags Fiesta Texas launching riders from 0 to 107 km/h in 3.8 seconds through a spectacular tightly packed layout of loops, corkscrews and zero-G rolls. One of the most intense and rerideable launched coasters in Texas. Min 137cm.',image:'assets/images/six_flags_fiesta_texas/poltergeist.png',category:'thrill',topPick:true,lat:29.6022,lng:-98.6112,liveWaitMinutes:40,rating:4.5,speedKmh:107,heightM:30,inversions:6,openedYear:1999,minHeightCm:137,temporarilyClosed:false},
{id:'batman_the_ride',name:'Batman The Ride',description:'A classic and beloved Batman-themed inverted coaster at Six Flags Fiesta Texas delivering five inversions at 80 km/h through a spectacular themed layout. One of the most popular and rerideable inverted coasters in Texas. Min 137cm.',image:'assets/images/six_flags_fiesta_texas/batman_the_ride.png',category:'thrill',topPick:false,lat:29.6035,lng:-98.6120,liveWaitMinutes:30,rating:4.4,speedKmh:80,heightM:30,inversions:5,openedYear:1993,minHeightCm:137,temporarilyClosed:false},
{id:'scream',name:'Scream',description:'A terrifying open-air drop tower at Six Flags Fiesta Texas lifting riders to the top of the quarry wall before plunging them back down at terrifying speed. One of the most scenic and terrifying drop tower experiences in Texas with extraordinary views over San Antonio. Min 122cm.',image:'assets/images/six_flags_fiesta_texas/scream.png',category:'thrill',topPick:false,lat:29.6028,lng:-98.6118,liveWaitMinutes:25,rating:4.3,speedKmh:0,heightM:61,inversions:0,openedYear:1996,minHeightCm:122,temporarilyClosed:false},
{id:'sky_screamer',name:'Sky Screamer',description:'A spectacular giant swing ride at Six Flags Fiesta Texas swinging riders at the top of the quarry wall with breathtaking panoramic views over San Antonio. One of the most scenic and exhilarating swing rides at any Texas theme park. Min 122cm.',image:'assets/images/six_flags_fiesta_texas/sky_screamer.png',category:'thrill',topPick:false,lat:29.6015,lng:-98.6108,liveWaitMinutes:20,rating:4.4,speedKmh:0,heightM:73,inversions:0,openedYear:2012,minHeightCm:122,temporarilyClosed:false},
{id:'joker',name:'The Joker',description:'A spectacular free-fly coaster at Six Flags Fiesta Texas where seats rotate independently through a twisted layout of inversions. A uniquely disorienting and entertaining coaster experience. Min 122cm.',image:'assets/images/six_flags_fiesta_texas/joker.png',category:'thrill',topPick:false,lat:29.6032,lng:-98.6106,liveWaitMinutes:35,rating:4.4,speedKmh:80,heightM:30,inversions:4,openedYear:2020,minHeightCm:122,temporarilyClosed:false},
{id:'boomerang',name:'Boomerang',description:'A classic and beloved boomerang shuttle coaster at Six Flags Fiesta Texas delivering three inversions forwards and then backwards through the same layout. A fun and accessible thrill coaster for all ages. Min 122cm.',image:'assets/images/six_flags_fiesta_texas/boomerang.png',category:'thrill',topPick:false,lat:29.6020,lng:-98.6102,liveWaitMinutes:20,rating:4.0,speedKmh:80,heightM:30,inversions:3,openedYear:1992,minHeightCm:122,temporarilyClosed:false},
{id:'pandemonium',name:'Pandemonium',description:'A fun and popular spinning wild mouse coaster at Six Flags Fiesta Texas with freely rotating cars through tight turns and drops. A fun unpredictable family experience. Min 107cm.',image:'assets/images/six_flags_fiesta_texas/pandemonium.png',category:'family',topPick:false,lat:29.6026,lng:-98.6097,liveWaitMinutes:25,rating:4.1,speedKmh:48,heightM:18,inversions:0,openedYear:2007,minHeightCm:107,temporarilyClosed:false},
{id:'tony_hawks_big_spin',name:"Tony Hawk's Big Spin",description:'A fun and popular spinning coaster at Six Flags Fiesta Texas themed to skateboarding legend Tony Hawk. Riders spin through a compact layout in fun rotating cars. Min 107cm.',image:'assets/images/six_flags_fiesta_texas/tony_hawks_big_spin.png',category:'family',topPick:false,lat:29.6023,lng:-98.6094,liveWaitMinutes:20,rating:4.0,speedKmh:56,heightM:15,inversions:0,openedYear:2007,minHeightCm:107,temporarilyClosed:false},
{id:'rio_loco',name:'Rio Loco',description:'A beloved and refreshing river rapids ride at Six Flags Fiesta Texas themed to the Texas Hill Country — riders drift through turbulent rapids and dramatic waterfalls in a fun circular raft. One of the most popular water rides in San Antonio. Min 107cm.',image:'assets/images/six_flags_fiesta_texas/rio_loco.png',category:'family',topPick:true,lat:29.6018,lng:-98.6115,liveWaitMinutes:30,rating:4.3,speedKmh:0,heightM:0,inversions:0,openedYear:1992,minHeightCm:107,temporarilyClosed:false},
{id:'bugs_white_water',name:"Bugs' White Water Rapids",description:'A classic and refreshing white water rapids ride at Six Flags Fiesta Texas featuring Bugs Bunny and friends through splashing rapids and fun special effects. One of the most entertaining water rides for families in Texas. Min 107cm.',image:'assets/images/six_flags_fiesta_texas/bugs_white_water.png',category:'family',topPick:false,lat:29.6015,lng:-98.6112,liveWaitMinutes:25,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:1992,minHeightCm:107,temporarilyClosed:false},
{id:'road_runner',name:'Road Runner Express',description:'A classic and beloved mine train coaster at Six Flags Fiesta Texas featuring Road Runner and Wile E. Coyote through a charming Texas desert landscape. The perfect first coaster for young riders. Min 107cm.',image:'assets/images/six_flags_fiesta_texas/road_runner.png',category:'family',topPick:false,lat:29.6035,lng:-98.6098,liveWaitMinutes:15,rating:4.0,speedKmh:56,heightM:15,inversions:0,openedYear:1992,minHeightCm:107,temporarilyClosed:false},
{id:'superman_krypton_tower',name:'Tower of Power',description:'A thrilling drop and launch tower experience at Six Flags Fiesta Texas combining upward launches and stomach-dropping falls with spectacular quarry views. Min 107cm.',image:'assets/images/six_flags_fiesta_texas/scream.png',category:'thrill',topPick:false,lat:29.6029,lng:-98.6110,liveWaitMinutes:15,rating:4.1,speedKmh:0,heightM:46,inversions:0,openedYear:2000,minHeightCm:107,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/six_flags_fiesta_texas/attractions.json',JSON.stringify(attractions,null,2),'utf8');
console.log('SFFT attractions done:',attractions.length);

const food=[
{id:'food_canyon_smokehouse',name:'Canyon Smokehouse',description:'The most popular and atmospheric restaurant at Six Flags Fiesta Texas — Canyon Smokehouse is a spectacular Texas BBQ restaurant serving authentic smoked brisket, ribs and sausage in a magnificent quarry-wall setting. The most satisfying and quintessentially Texan dining experience at any San Antonio theme park.',topPick:true,type:'Texas BBQ',image:'assets/images/six_flags_fiesta_texas/food_canyon_smokehouse.png',lat:29.6025,lng:-98.6110,rating:4.5,items:[{name:'Smoked Brisket Plate',description:'Classic Texas smoked brisket with jalapeño cornbread and coleslaw',price:20},{name:'Pork Ribs',description:'Classic slow-smoked pork ribs with BBQ sauce and fries',price:22},{name:'Texas Sausage Link',description:'Classic grilled Texas sausage with pickles and onions',price:14},{name:'Sweet Tea',description:'Classic Southern sweet iced tea',price:4}]},
{id:'food_fatburger',name:'Fatburger',description:'The legendary California burger chain at Six Flags Fiesta Texas serving the famous Fatburger made to order with fresh ingredients. One of the most satisfying burger experiences at any San Antonio theme park.',topPick:true,type:'California Burgers',image:'assets/images/six_flags_fiesta_texas/food_fatburger.png',lat:29.6030,lng:-98.6115,rating:4.4,items:[{name:'Fatburger',description:'The legendary thick beef patty Fatburger with all the trimmings',price:18},{name:'Skinny Fries',description:'Classic thin crispy Fatburger fries',price:7},{name:'Fat Shake',description:'Thick hand-spun milkshake',price:9},{name:'Onion Rings',description:'Classic crispy onion rings',price:7}]},
{id:'food_bubbas_cafe',name:"Bubba's Cafe",description:'A popular and fun Texas-themed cafe at Six Flags Fiesta Texas serving classic Texan comfort food including chicken tenders, nachos and classic American sides in a cheerful atmosphere.',topPick:false,type:'Texas Comfort Food',image:'assets/images/six_flags_fiesta_texas/food_bubbas_cafe.png',lat:29.6020,lng:-98.6105,rating:4.0,items:[{name:'Chicken Tenders',description:'Classic crispy chicken tenders with fries and dipping sauce',price:15},{name:'Nachos',description:'Classic loaded nachos with cheese jalapeños and salsa',price:11},{name:'Corn Dog',description:'Classic deep-fried corn dog',price:8},{name:'Lemonade',description:'Fresh squeezed lemonade',price:5}]},
{id:'food_chopsix',name:'ChopSix',description:'A popular Asian-inspired quick-service restaurant at Six Flags Fiesta Texas serving teriyaki bowls, fried rice and noodle dishes. One of the most diverse and satisfying quick-service options at the park.',topPick:false,type:'Asian-American',image:'assets/images/six_flags_fiesta_texas/food_chopsix.png',lat:29.6028,lng:-98.6108,rating:4.1,items:[{name:'Teriyaki Chicken Bowl',description:'Classic teriyaki chicken with fried rice and vegetables',price:14},{name:'Noodle Bowl',description:'Classic Asian noodle bowl with choice of protein',price:14},{name:'Egg Roll',description:'Classic crispy egg roll with sweet and sour sauce',price:6},{name:'Soft Drink',description:'Large fountain drink',price:4}]},
{id:'food_vip_lounge',name:'VIP Lounge & Dining',description:'The most prestigious dining experience at Six Flags Fiesta Texas — the VIP Lounge offers premium dining with spectacular quarry views, superior food quality and an exclusive atmosphere for guests seeking the finest park dining experience.',topPick:false,type:'Premium Dining',image:'assets/images/six_flags_fiesta_texas/food_vip_lounge.png',lat:29.6032,lng:-98.6112,rating:4.3,items:[{name:'Premium Burger',description:'Premium wagyu beef burger with gourmet toppings',price:22},{name:'Chicken Sandwich',description:'Premium grilled chicken sandwich with artisan bread',price:18},{name:'Loaded Nachos',description:'Premium loaded nachos with multiple toppings',price:14},{name:'Craft Lemonade',description:'Fresh house-made craft lemonade',price:6}]}
];
fs.writeFileSync('assets/data/parks/six_flags_fiesta_texas/food.json',JSON.stringify(food,null,2),'utf8');
console.log('SFFT food done:',food.length);

const hotels=[
{id:'hotel_jw_marriott_san_antonio',name:'JW Marriott San Antonio Hill Country',description:'The most magnificent and prestigious resort near Six Flags Fiesta Texas — the JW Marriott San Antonio Hill Country Resort and Spa is a spectacular luxury resort featuring two enormous waterparks, outstanding restaurants, a world-class spa and the finest resort experience near any Texas theme park.',image:'assets/images/six_flags_fiesta_texas/hotel_jw_marriott_san_antonio.png',lat:29.6052,lng:-98.6198,rating:4.9,topPick:true,website:'https://www.marriott.com/hotels/travel/satjw-jw-marriott-san-antonio-hill-country-resort-and-spa/',rooms:[{key:'standard_room',name:'Standard Room',description:'Elegant Hill Country room with resort and waterpark access.',pricePerNight:380,breakfastIncluded:false},{key:'deluxe_room',name:'Deluxe Room',description:'Premium room with Hill Country views.',pricePerNight:480,breakfastIncluded:false},{key:'suite',name:'Suite',description:'Magnificent suite with panoramic views and breakfast.',pricePerNight:850,breakfastIncluded:true}]},
{id:'hotel_hyatt_regency_san_antonio',name:'Hyatt Regency San Antonio Riverwalk',description:'A magnificent and iconic 4-star hotel on the famous San Antonio River Walk — the Hyatt Regency San Antonio is a spectacular hotel with extraordinary River Walk views, outstanding restaurants and the finest hotel experience in downtown San Antonio for Six Flags Fiesta Texas visitors.',image:'assets/images/six_flags_fiesta_texas/hotel_hyatt_regency_san_antonio.png',lat:29.4240,lng:-98.4927,rating:4.6,topPick:true,website:'https://www.hyatt.com/en-US/hotel/texas/hyatt-regency-san-antonio-riverwalk/satrs',rooms:[{key:'standard_room',name:'Standard Room',description:'Elegant room with River Walk views.',pricePerNight:280,breakfastIncluded:false},{key:'river_view',name:'River View Room',description:'Premium room with direct River Walk views.',pricePerNight:340,breakfastIncluded:false},{key:'suite',name:'Suite',description:'Spectacular suite with panoramic River Walk views.',pricePerNight:580,breakfastIncluded:true}]},
{id:'hotel_marriott_rivercenter',name:'San Antonio Marriott Rivercenter',description:'A magnificent and popular Marriott hotel on the San Antonio River Walk — the Marriott Rivercenter is a spectacular hotel with extraordinary River Walk and city views, multiple outstanding restaurants and excellent value for Six Flags Fiesta Texas visitors staying in downtown San Antonio.',image:'assets/images/six_flags_fiesta_texas/hotel_marriott_rivercenter.png',lat:29.4235,lng:-98.4880,rating:4.5,topPick:false,website:'https://www.marriott.com/hotels/travel/satmc-san-antonio-marriott-rivercenter/',rooms:[{key:'standard_room',name:'Standard Room',description:'Classic room with River Walk views.',pricePerNight:220,breakfastIncluded:false},{key:'deluxe_room',name:'Deluxe Room',description:'Premium room with upgraded city views.',pricePerNight:270,breakfastIncluded:false},{key:'suite',name:'Suite',description:'Spacious suite with River Walk views.',pricePerNight:440,breakfastIncluded:true}]},
{id:'hotel_emily_morgan',name:'Emily Morgan Hotel San Antonio',description:'A magnificent boutique hotel in the heart of downtown San Antonio adjacent to the famous Alamo — the Emily Morgan Hotel is a beautifully restored Gothic Revival building offering elegant rooms, outstanding service and the most atmospheric and historic hotel experience in San Antonio.',image:'assets/images/six_flags_fiesta_texas/hotel_emily_morgan.png',lat:29.4259,lng:-98.4861,rating:4.6,topPick:false,website:'https://www.emilymorganhotel.com/',rooms:[{key:'standard_room',name:'Standard Room',description:'Elegant boutique room with Alamo views and free WiFi.',pricePerNight:190,breakfastIncluded:false},{key:'deluxe_room',name:'Deluxe Room',description:'Premium room with upgraded Alamo views.',pricePerNight:240,breakfastIncluded:false},{key:'suite',name:'Suite',description:'Magnificent suite with panoramic Alamo views.',pricePerNight:380,breakfastIncluded:true}]}
];
fs.writeFileSync('assets/data/parks/six_flags_fiesta_texas/hotels.json',JSON.stringify(hotels,null,2),'utf8');
console.log('SFFT hotels done:',hotels.length);

const pe={id:"six_flags_fiesta_texas",thumbnailAsset:"assets/images/six_flags_fiesta_texas/park_thumbnail.png",tailAsset:"",name:"Six Flags Fiesta Texas",type:"Theme Park",entryPrice:{child:59,adult:74},currency:"USD",openingHours:"10:30 - 21:00",lng:-98.6109,country:"USA",city:"San Antonio, Texas",ticketsUrl:"https://www.sixflags.com/fiestatexas/tickets",queueTimesId:0};
const ie={id:"six_flags_fiesta_texas",name:"Six Flags Fiesta Texas",city:"San Antonio, Texas",country:"USA",type:"Theme Park",lat:29.6025,lng:-98.6109,thumbnail:"assets/images/six_flags_fiesta_texas/park_thumbnail.png",website:"https://www.sixflags.com/fiestatexas",ticketsUrl:"https://www.sixflags.com/fiestatexas/tickets",detailAsset:"",openingHours:"10:30 - 21:00",entryPrices:{adult:74,child:59},currency:"USD",queueTimesId:0};
const parks=readJson('assets/data/parks.json');
if(!parks.find(p=>p.id==='six_flags_fiesta_texas')){parks.push(pe);fs.writeFileSync('assets/data/parks.json',JSON.stringify(parks,null,4),'utf8');console.log('parks.json:',parks.length);}
const index=readJson('assets/data/parks/parks_index.json');
if(!index.find(p=>p.id==='six_flags_fiesta_texas')){index.push(ie);fs.writeFileSync('assets/data/parks/parks_index.json',JSON.stringify(index,null,4),'utf8');console.log('parks_index.json:',index.length);}