const fs=require('fs');
const d=[
{id:'x2',name:'X2',description:'The most unique and disorientating roller coaster in the world — X2 is a 4th-dimension coaster where seats rotate independently on a separate axis, spinning riders forward and backward throughout the layout while the coaster itself navigates a twisting track. There is literally nothing else like X2 anywhere on Earth. The most talked-about coaster at any American theme park. Min 122cm.',image:'assets/images/six_flags_magic_mountain/x2.png',category:'thrill',topPick:true,lat:34.4259,lng:-118.5970,liveWaitMinutes:90,rating:4.8,speedKmh:120,heightM:63,inversions:0,openedYear:2002,minHeightCm:122,temporarilyClosed:false},
{id:'tatsu',name:'Tatsu',description:'The tallest, fastest and longest flying coaster in the world — Tatsu at Six Flags Magic Mountain places riders in a prone flying position and takes them through an extraordinary layout of twisting turns and the legendary pretzel loop inversion high above the mountain terrain. One of the most breathtaking and rerideable coasters in California. Min 137cm.',image:'assets/images/six_flags_magic_mountain/tatsu.png',category:'thrill',topPick:true,lat:34.4255,lng:-118.5975,liveWaitMinutes:75,rating:4.7,speedKmh:105,heightM:54,inversions:5,openedYear:2006,minHeightCm:137,temporarilyClosed:false},
{id:'superman_escape',name:'Superman: Escape from Krypton',description:'One of the most iconic and historically significant coasters ever built — Superman: Escape from Krypton was the first coaster to break 100 mph when it opened in 1997, launching riders backwards at 161 km/h up a 126-metre tower before experiencing several seconds of weightlessness at the top. An extraordinary coaster landmark. Min 137cm.',image:'assets/images/six_flags_magic_mountain/superman_escape.png',category:'thrill',topPick:true,lat:34.4262,lng:-118.5965,liveWaitMinutes:60,rating:4.6,speedKmh:161,heightM:126,inversions:0,openedYear:1997,minHeightCm:137,temporarilyClosed:false},
{id:'full_throttle',name:'Full Throttle',description:'A spectacular and unique launched coaster at Six Flags Magic Mountain featuring the world\'s largest vertical loop at 44 metres — Full Throttle launches riders through the loop twice in both directions in one of the most visually dramatic coaster experiences at any California theme park. Min 122cm.',image:'assets/images/six_flags_magic_mountain/full_throttle.png',category:'thrill',topPick:true,lat:34.4248,lng:-118.5980,liveWaitMinutes:50,rating:4.5,speedKmh:112,heightM:44,inversions:3,openedYear:2013,minHeightCm:122,temporarilyClosed:false},
{id:'goliath',name:'Goliath',description:'A spectacular and beloved hyper coaster at Six Flags Magic Mountain soaring above the park on a breathtaking layout of airtime hills and sweeping turns — Goliath is one of the finest and most rerideable hyper coasters in California and a Magic Mountain institution since 2000. Min 137cm.',image:'assets/images/six_flags_magic_mountain/goliath.png',category:'thrill',topPick:true,lat:34.4252,lng:-118.5978,liveWaitMinutes:45,rating:4.6,speedKmh:137,heightM:73,inversions:0,openedYear:2000,minHeightCm:137,temporarilyClosed:false},
{id:'west_coast_racers',name:'West Coast Racers',description:'A spectacular racing dual-tracked coaster at Six Flags Magic Mountain themed to the West Coast Customs customisation culture — West Coast Racers is the most entertainingly themed coaster at Magic Mountain and one of the most fun and rerideable racing coasters in California. Min 122cm.',image:'assets/images/six_flags_magic_mountain/west_coast_racers.png',category:'thrill',topPick:true,lat:34.4245,lng:-118.5983,liveWaitMinutes:45,rating:4.5,speedKmh:105,heightM:34,inversions:4,openedYear:2020,minHeightCm:122,temporarilyClosed:false},
{id:'wonder_woman',name:'Wonder Woman Flight of Courage',description:'The world\'s tallest and longest single-rail coaster — Wonder Woman Flight of Courage at Six Flags Magic Mountain is an extraordinary single-rail RMC coaster delivering intense airtime and extraordinary agility on the most innovative coaster technology available. Min 137cm.',image:'assets/images/six_flags_magic_mountain/wonder_woman.png',category:'thrill',topPick:true,lat:34.4242,lng:-118.5985,liveWaitMinutes:55,rating:4.7,speedKmh:105,heightM:51,inversions:0,openedYear:2022,minHeightCm:137,temporarilyClosed:false},
{id:'riddlers_revenge',name:"Riddler's Revenge",description:'The tallest and fastest stand-up roller coaster in the world — Riddler\'s Revenge at Six Flags Magic Mountain delivers six inversions at 105 km/h in the unique upright stand-up riding position. One of the most extraordinary and unusual coaster experiences in California. Min 137cm.',image:'assets/images/six_flags_magic_mountain/riddlers_revenge.png',category:'thrill',topPick:false,lat:34.4256,lng:-118.5973,liveWaitMinutes:35,rating:4.4,speedKmh:105,heightM:41,inversions:6,openedYear:1998,minHeightCm:137,temporarilyClosed:false},
{id:'batman_the_ride',name:'Batman The Ride',description:'A classic and beloved Batman-themed inverted coaster at Six Flags Magic Mountain — Batman The Ride is a perfectly designed B&M inverted coaster delivering five inversions at 80 km/h through a spectacular themed layout. One of the most popular and rerideable inverted coasters in California. Min 137cm.',image:'assets/images/six_flags_magic_mountain/batman_the_ride.png',category:'thrill',topPick:false,lat:34.4260,lng:-118.5968,liveWaitMinutes:35,rating:4.4,speedKmh:80,heightM:30,inversions:5,openedYear:1994,minHeightCm:137,temporarilyClosed:false},
{id:'revolution',name:'Revolution',description:'A legendary and historically significant roller coaster — Revolution at Six Flags Magic Mountain was the world\'s first modern looping coaster when it opened in 1976 and appeared in the film Rollercoaster. A Magic Mountain institution and one of the most historically important attractions in theme park history. Min 122cm.',image:'assets/images/six_flags_magic_mountain/revolution.png',category:'thrill',topPick:false,lat:34.4264,lng:-118.5963,liveWaitMinutes:20,rating:4.0,speedKmh:88,heightM:34,inversions:1,openedYear:1976,minHeightCm:122,temporarilyClosed:false},
{id:'viper',name:'Viper',description:'A classic and beloved triple-loop steel coaster at Six Flags Magic Mountain — Viper has delivered classic loop, corkscrew and boomerang inversions since 1990 and is one of the most iconic and beloved classic coasters at any California theme park. Min 137cm.',image:'assets/images/six_flags_magic_mountain/viper.png',category:'thrill',topPick:false,lat:34.4258,lng:-118.5972,liveWaitMinutes:25,rating:4.2,speedKmh:105,heightM:50,inversions:7,openedYear:1990,minHeightCm:137,temporarilyClosed:false},
{id:'scream',name:'Scream',description:'A spectacular floorless roller coaster at Six Flags Magic Mountain delivering seven inversions at 105 km/h in an open floorless vehicle — Scream is one of the most intense and thrilling floorless coasters in California. Min 137cm.',image:'assets/images/six_flags_magic_mountain/scream.png',category:'thrill',topPick:false,lat:34.4250,lng:-118.5980,liveWaitMinutes:30,rating:4.3,speedKmh:105,heightM:50,inversions:7,openedYear:2003,minHeightCm:137,temporarilyClosed:false},
{id:'apocalypse',name:'Apocalypse',description:'A thrilling and beloved wooden roller coaster at Six Flags Magic Mountain — Apocalypse delivers classic wooden coaster thrills with genuine rough-and-tumble character and is one of the most popular and nostalgic attractions at Magic Mountain. Min 122cm.',image:'assets/images/six_flags_magic_mountain/apocalypse.png',category:'thrill',topPick:false,lat:34.4246,lng:-118.5982,liveWaitMinutes:20,rating:4.1,speedKmh:96,heightM:30,inversions:0,openedYear:2009,minHeightCm:122,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/six_flags_magic_mountain/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('SFMM attractions done:',d.length);