const fs=require('fs');
const d=[
{id:'desafio',name:'Desafío',description:'The most thrilling and beloved roller coaster at Parque de la Costa — Desafío is a spectacular inverted coaster delivering multiple inversions and high-speed thrills through a dramatic layout. The most popular and acclaimed coaster at Argentina\'s premier theme park. Min 130cm.',image:'assets/images/parque_de_la_costa/desafio.png',category:'thrill',topPick:true,lat:-34.4255,lng:-58.5768,liveWaitMinutes:50,rating:4.7,speedKmh:95,heightM:32,inversions:5,openedYear:1997,minHeightCm:130,temporarilyClosed:false},
{id:'captain_pirana',name:'Capitán Pirata',description:'A thrilling and spectacular pirate ship ride at Parque de la Costa swinging riders to extreme heights in a dramatically themed pirate galleon — Capitán Pirata is one of the most popular and entertaining thrill experiences at Argentina\'s premier theme park. Min 122cm.',image:'assets/images/parque_de_la_costa/captain_pirana.png',category:'thrill',topPick:true,lat:-34.4252,lng:-58.5772,liveWaitMinutes:35,rating:4.4,speedKmh:0,heightM:0,inversions:0,openedYear:1997,minHeightCm:122,temporarilyClosed:false},
{id:'la_mansion_del_terror',name:'La Mansión del Terror',description:'The most elaborate and terrifying dark ride at Parque de la Costa — La Mansión del Terror is a spectacular indoor dark ride experience through a haunted mansion filled with extraordinary horror effects, animatronics and theatrical scares. The most immersive and memorable dark ride at any Argentine theme park. Suitable for ages 12+.',image:'assets/images/parque_de_la_costa/la_mansion_del_terror.png',category:'thrill',topPick:true,lat:-34.4258,lng:-58.5765,liveWaitMinutes:40,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:1998,minHeightCm:0,temporarilyClosed:false},
{id:'acuatico',name:'Acuático',description:'The most refreshing and popular water attraction at Parque de la Costa — Acuático is a spectacular log flume ride plunging guests through a dramatic waterfall finale on a spectacular journey. One of the most popular and rerideable water rides at any Argentine theme park. Min 107cm.',image:'assets/images/parque_de_la_costa/acuatico.png',category:'family',topPick:true,lat:-34.4250,lng:-58.5775,liveWaitMinutes:40,rating:4.3,speedKmh:0,heightM:15,inversions:0,openedYear:1997,minHeightCm:107,temporarilyClosed:false},
{id:'boomerang',name:'Boomerang',description:'A classic and thrilling boomerang shuttle coaster at Parque de la Costa — delivering forward and backward passes through three inversions in one of the most popular and accessible thrill coasters at Argentina\'s premier theme park. Min 122cm.',image:'assets/images/parque_de_la_costa/boomerang.png',category:'thrill',topPick:false,lat:-34.4262,lng:-58.5762,liveWaitMinutes:30,rating:4.2,speedKmh:80,heightM:26,inversions:3,openedYear:1997,minHeightCm:122,temporarilyClosed:false},
{id:'pendulum',name:'Péndulo',description:'A spectacular giant pendulum thrill ride at Parque de la Costa swinging riders to extreme heights before completing full 360-degree rotations — Péndulo is one of the most intense and spectacular thrill experiences at any Argentine theme park. Min 122cm.',image:'assets/images/parque_de_la_costa/pendulum.png',category:'thrill',topPick:true,lat:-34.4265,lng:-58.5758,liveWaitMinutes:25,rating:4.5,speedKmh:0,heightM:30,inversions:0,openedYear:2001,minHeightCm:122,temporarilyClosed:false},
{id:'saltos_del_delta',name:'Saltos del Delta',description:'A thrilling and exhilarating whitewater rapids ride at Parque de la Costa taking guests through turbulent river rapids and dramatic water effects — Saltos del Delta is one of the most refreshing and popular family water attractions at Argentina\'s premier theme park. Min 107cm.',image:'assets/images/parque_de_la_costa/saltos_del_delta.png',category:'family',topPick:false,lat:-34.4248,lng:-58.5778,liveWaitMinutes:30,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:1997,minHeightCm:107,temporarilyClosed:false},
{id:'botes_en_el_nilo',name:'Botes en el Nilo',description:'A fun and popular bumper boat experience at Parque de la Costa themed to the Nile River — guests pilot individual boats through a water course in one of the most entertaining and family-friendly experiences at Argentina\'s premier theme park. Suitable for all ages.',image:'assets/images/parque_de_la_costa/botes_en_el_nilo.png',category:'family',topPick:false,lat:-34.4245,lng:-58.5782,liveWaitMinutes:20,rating:3.9,speedKmh:0,heightM:0,inversions:0,openedYear:1997,minHeightCm:0,temporarilyClosed:false},
{id:'botes_del_pantano',name:'Botes del Pantano',description:'A classic and charming pedal boat experience on the lagoon at Parque de la Costa — Botes del Pantano is one of the most relaxing and atmospheric family attractions at the park, offering a peaceful journey through the beautiful wetland environment. Suitable for all ages.',image:'assets/images/parque_de_la_costa/botes_del_pantano.png',category:'family',topPick:false,lat:-34.4242,lng:-58.5785,liveWaitMinutes:10,rating:3.8,speedKmh:0,heightM:0,inversions:0,openedYear:1997,minHeightCm:0,temporarilyClosed:false},
{id:'el_vigia',name:'El Vigía',description:'A spectacular observation tower at Parque de la Costa rising above the park to offer breathtaking panoramic views over the park, the Tigre Delta wetlands and the surrounding Buenos Aires suburban landscape. The most scenic attraction at Parque de la Costa. Suitable for all ages.',image:'assets/images/parque_de_la_costa/el_vigia.png',category:'family',topPick:true,lat:-34.4260,lng:-58.5760,liveWaitMinutes:15,rating:4.3,speedKmh:0,heightM:40,inversions:0,openedYear:1997,minHeightCm:0,temporarilyClosed:false},
{id:'torbellino',name:'Torbellino',description:'A classic spinning flat ride at Parque de la Costa delivering wildly entertaining disorienting rotations — Torbellino is one of the most popular and entertaining flat ride experiences at Argentina\'s premier theme park. Min 107cm.',image:'assets/images/parque_de_la_costa/torbellino.png',category:'thrill',topPick:false,lat:-34.4268,lng:-58.5755,liveWaitMinutes:20,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:1998,minHeightCm:107,temporarilyClosed:false},
{id:'desorbitados',name:'Desorbitados',description:'A thrilling and spectacular free-fall drop tower experience at Parque de la Costa — Desorbitados catapults riders skyward before a sudden freefall descent. One of the most intense thrill experiences at any Argentine theme park. Min 122cm.',image:'assets/images/parque_de_la_costa/desorbitados.png',category:'thrill',topPick:false,lat:-34.4255,lng:-58.5770,liveWaitMinutes:20,rating:4.2,speedKmh:0,heightM:30,inversions:0,openedYear:2000,minHeightCm:122,temporarilyClosed:false},
{id:'orcas_voladoras',name:'Orcas Voladoras',description:'A charming and fun flying orca-themed flat ride at Parque de la Costa — Orcas Voladoras is one of the most entertaining and accessible family attractions at the park, beloved by children and families. Suitable for all ages.',image:'assets/images/parque_de_la_costa/orcas_voladoras.png',category:'family',topPick:false,lat:-34.4243,lng:-58.5783,liveWaitMinutes:15,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:1997,minHeightCm:0,temporarilyClosed:false},
{id:'samba',name:'Samba',description:'A classic and beloved spinning carnival ride at Parque de la Costa — Samba delivers entertaining spinning and swinging motion in a festively themed environment and is one of the most popular family rides at Argentina\'s premier theme park. Min 107cm.',image:'assets/images/parque_de_la_costa/samba.png',category:'family',topPick:false,lat:-34.4270,lng:-58.5752,liveWaitMinutes:15,rating:3.9,speedKmh:0,heightM:0,inversions:0,openedYear:1997,minHeightCm:107,temporarilyClosed:false},
{id:'pulpo',name:'Pulpo',description:'A classic octopus-themed spinning flat ride at Parque de la Costa — Pulpo is one of the most charming and accessible children\'s rides at the park and a beloved classic attraction. Suitable for all ages.',image:'assets/images/parque_de_la_costa/pulpo.png',category:'family',topPick:false,lat:-34.4240,lng:-58.5788,liveWaitMinutes:10,rating:3.8,speedKmh:0,heightM:0,inversions:0,openedYear:1997,minHeightCm:0,temporarilyClosed:false},
{id:'vuelta_al_mundo',name:'Vuelta al Mundo',description:'A spectacular giant Ferris wheel at Parque de la Costa offering extraordinary panoramic views over the Tigre Delta wetlands, the surrounding Buenos Aires suburbs and on clear days the distant Rio de la Plata estuary. The most scenic and atmospheric attraction at Parque de la Costa. Suitable for all ages.',image:'assets/images/parque_de_la_costa/vuelta_al_mundo.png',category:'family',topPick:true,lat:-34.4238,lng:-58.5790,liveWaitMinutes:10,rating:4.4,speedKmh:0,heightM:40,inversions:0,openedYear:1997,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/parque_de_la_costa/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('Parque de la Costa attractions done:',d.length);