const fs=require('fs');
const d=[
{id:'hagrids_motorbike_adventure',name:"Hagrid's Magical Creatures Motorbike Adventure",description:"The greatest theme park attraction in the world — Hagrid's Magical Creatures Motorbike Adventure is a breathtaking outdoor roller coaster through the Forbidden Forest with magical creatures, multiple surprise elements, a backwards launch into Devil's Snare and Hagrid on his motorbike sidecar. The most beloved attraction at any theme park. Min 122cm.",image:'assets/images/islands_of_adventure/hagrids_motorbike_adventure.png',category:'thrill',topPick:true,lat:28.4722,lng:-81.4728,liveWaitMinutes:120,rating:5.0,speedKmh:80,heightM:25,inversions:0,openedYear:2019,minHeightCm:122,temporarilyClosed:false},
{id:'velocicoaster_ioa',name:'Jurassic World VelociCoaster',description:'The most intense roller coaster in Florida — VelociCoaster launches at 113 km/h with 12 seconds of airtime, a 150-degree banked turn and an iconic top hat inversion over the lagoon. The finest coaster at Universal Orlando. Min 122cm.',image:'assets/images/islands_of_adventure/velocicoaster.png',category:'thrill',topPick:true,lat:28.4728,lng:-81.4722,liveWaitMinutes:90,rating:4.9,speedKmh:113,heightM:46,inversions:4,openedYear:2021,minHeightCm:122,temporarilyClosed:false},
{id:'forbidden_journey',name:"Harry Potter and the Forbidden Journey",description:"The centrepiece of Hogsmeade and one of the most immersive dark rides ever built — Harry Potter and the Forbidden Journey takes guests on a soaring journey over Hogwarts castle alongside Harry, Ron and Hermione encountering Dementors, the Whomping Willow and a Quidditch match in a spectacular combination of physical sets and screen projection. Min 122cm.",image:'assets/images/islands_of_adventure/forbidden_journey.png',category:'family',topPick:true,lat:28.4722,lng:-81.4718,liveWaitMinutes:65,rating:4.8,speedKmh:0,heightM:0,inversions:0,openedYear:2010,minHeightCm:122,temporarilyClosed:false},
{id:'incredible_hulk_coaster',name:'The Incredible Hulk Coaster',description:'A classic and beloved launched steel roller coaster at Islands of Adventure — The Incredible Hulk Coaster launches riders from 0 to 64 km/h in two seconds through seven inversions in a spectacular Marvel Super Hero Island setting. One of the finest and most rerideable coasters in Florida. Min 137cm.',image:'assets/images/islands_of_adventure/incredible_hulk_coaster.png',category:'thrill',topPick:true,lat:28.4738,lng:-81.4708,liveWaitMinutes:55,rating:4.7,speedKmh:105,heightM:46,inversions:7,openedYear:1999,minHeightCm:137,temporarilyClosed:false},
{id:'skull_island_kong',name:'Skull Island: Reign of Kong',description:'A spectacular and terrifying dark ride through Skull Island — Skull Island: Reign of Kong places guests aboard a massive expedition vehicle for a journey through the jungle encountering enormous prehistoric creatures and the mighty King Kong in one of the most immersive and thrilling dark ride experiences at Universal. Min 102cm.',image:'assets/images/islands_of_adventure/skull_island_kong.png',category:'thrill',topPick:true,lat:28.4732,lng:-81.4718,liveWaitMinutes:45,rating:4.6,speedKmh:0,heightM:0,inversions:0,openedYear:2016,minHeightCm:102,temporarilyClosed:false},
{id:'jurassic_park_river',name:'Jurassic Park River Adventure',description:'A classic and thrilling log flume dark ride through Jurassic Park — guests board rafts for a gentle tour of the dinosaur habitats before an encounter with escaping Velociraptors and a T-Rex sends them plunging down an 85-foot waterfall. One of the most beloved and iconic water rides at any theme park. Min 107cm.',image:'assets/images/islands_of_adventure/jurassic_park_river.png',category:'family',topPick:true,lat:28.4718,lng:-81.4722,liveWaitMinutes:50,rating:4.6,speedKmh:0,heightM:26,inversions:0,openedYear:1999,minHeightCm:107,temporarilyClosed:false},
{id:'dr_doom',name:"Doctor Doom's Fearfall",description:"A towering drop tower experience in Marvel Super Hero Island — Doctor Doom's Fearfall blasts guests 60 metres skyward before dropping them in a series of terrifying bounces with spectacular views over Universal Orlando. One of the most intense drop tower experiences at any theme park. Min 122cm.",image:'assets/images/islands_of_adventure/dr_doom.png',category:'thrill',topPick:false,lat:28.4740,lng:-81.4706,liveWaitMinutes:30,rating:4.4,speedKmh:0,heightM:60,inversions:0,openedYear:1999,minHeightCm:122,temporarilyClosed:false},
{id:'flight_of_the_hippogriff',name:'Flight of the Hippogriff',description:"A fun and exciting outdoor roller coaster in Hogsmeade themed to Buckbeak the Hippogriff from Harry Potter — Flight of the Hippogriff offers spectacular aerial views over Hogsmeade and Hogwarts Castle and is the perfect family coaster introduction in the Wizarding World. Min 99cm.",image:'assets/images/islands_of_adventure/flight_of_the_hippogriff.png',category:'family',topPick:false,lat:28.4720,lng:-81.4716,liveWaitMinutes:35,rating:4.3,speedKmh:72,heightM:18,inversions:0,openedYear:2010,minHeightCm:99,temporarilyClosed:false},
{id:'dudley_do_right',name:"Dudley Do-Right's Ripsaw Falls",description:"A classic and beloved flume ride at Islands of Adventure — Dudley Do-Right's Ripsaw Falls is a wonderfully themed log flume through the cartoon world of Dudley Do-Right featuring multiple drops including a spectacular below-ground plunge through a waterfall. One of the most beloved water rides at Universal. Min 107cm.",image:'assets/images/islands_of_adventure/dudley_do_right.png',category:'family',topPick:false,lat:28.4734,lng:-81.4712,liveWaitMinutes:30,rating:4.3,speedKmh:0,heightM:15,inversions:0,openedYear:1999,minHeightCm:107,temporarilyClosed:false},
{id:'poseidons_fury',name:"Poseidon's Fury",description:"A spectacular walk-through live action show in the Lost Continent at Islands of Adventure — Poseidon's Fury features an extraordinary water vortex tunnel, large-scale live effects and a battle between Poseidon and an ancient evil in one of the most technically impressive theatrical experiences at any theme park. Suitable for all ages.",image:'assets/images/islands_of_adventure/poseidons_fury.png',category:'family',topPick:false,lat:28.4726,lng:-81.4710,liveWaitMinutes:20,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:1999,minHeightCm:0,temporarilyClosed:false},
{id:'pteranodon_flyers',name:'Pteranodon Flyers',description:'A gentle and scenic aerial gondola ride over Jurassic Park at Islands of Adventure — Pteranodon Flyers offers beautiful aerial views over the Jurassic World area and is one of the most charming and unique ride experiences at Universal Orlando. Suitable for accompanied children.',image:'assets/images/islands_of_adventure/pteranodon_flyers.png',category:'family',topPick:false,lat:28.4716,lng:-81.4724,liveWaitMinutes:25,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:1999,minHeightCm:0,temporarilyClosed:false},
{id:'high_in_the_sky_trolley',name:'The High in the Sky Seuss Trolley Train Ride',description:'A charming and delightful elevated train ride through Seuss Landing at Islands of Adventure — the Seuss Trolley Train offers beautiful aerial views over the colourful Seuss Landing area and is a wonderful gentle family ride through the world of Dr. Seuss. Suitable for all ages.',image:'assets/images/islands_of_adventure/high_in_the_sky_trolley.png',category:'family',topPick:false,lat:28.4742,lng:-81.4702,liveWaitMinutes:15,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:1999,minHeightCm:0,temporarilyClosed:false},
{id:'storm_force_accelatron',name:'Storm Force Accelatron',description:'A classic spinning cup ride in Marvel Super Hero Island themed to the X-Men character Storm — Storm Force Accelatron is a fun and accessible spinning attraction for the whole family. Suitable for all ages.',image:'assets/images/islands_of_adventure/storm_force_accelatron.png',category:'family',topPick:false,lat:28.4742,lng:-81.4704,liveWaitMinutes:15,rating:3.9,speedKmh:0,heightM:0,inversions:0,openedYear:1999,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/islands_of_adventure/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('IOA attractions done:',d.length);