const fs=require('fs');
const d=[
{id:'star_wars_rise_of_resistance',name:'Star Wars: Rise of the Resistance',description:'The most technologically ambitious and immersive theme park attraction ever built — Star Wars: Rise of the Resistance places guests inside a full-scale Star Destroyer with extraordinary room-scale sets, dozens of full-size stormtroopers, multiple ride systems and cinematic sequences featuring Rey, Kylo Ren and Finn. Widely regarded as the greatest theme park attraction of the 21st century. Min 102cm.',image:'assets/images/disneyland_park/star_wars_rise_of_resistance.png',category:'family',topPick:true,lat:33.8157,lng:-117.9228,liveWaitMinutes:90,rating:4.9,speedKmh:0,heightM:0,inversions:0,openedYear:2019,minHeightCm:102,temporarilyClosed:false},
{id:'indiana_jones_adventure',name:'Indiana Jones Adventure',description:'A legendary and beloved dark ride masterpiece — Indiana Jones Adventure at Disneyland is the original and greatest version of the attraction, featuring an extraordinary recreation of an ancient temple with towering animatronic figures, real flame effects, a life-size mechanised skeleton of the Mara idol and the most thrilling jeep-based dark ride experience at any Disney park. Min 117cm.',image:'assets/images/disneyland_park/indiana_jones.png',category:'thrill',topPick:true,lat:33.8115,lng:-117.9195,liveWaitMinutes:70,rating:4.9,speedKmh:0,heightM:0,inversions:0,openedYear:1995,minHeightCm:117,temporarilyClosed:false},
{id:'matterhorn_bobsleds',name:'Matterhorn Bobsleds',description:'The world\'s first tubular steel roller coaster and a Disneyland icon since 1959 — Matterhorn Bobsleds sends riders through a thrilling indoor mountain coaster with the legendary Yeti lurking in the caverns. One of the most historically significant and beloved coasters in theme park history. Min 107cm.',image:'assets/images/disneyland_park/matterhorn_bobsleds.png',category:'thrill',topPick:true,lat:33.8127,lng:-117.9183,liveWaitMinutes:55,rating:4.7,speedKmh:56,heightM:30,inversions:0,openedYear:1959,minHeightCm:107,temporarilyClosed:false},
{id:'radiator_springs_racers',name:'Radiator Springs Racers',description:'The most beloved attraction at Disney California Adventure and one of the finest ride experiences at any Disney park — Radiator Springs Racers takes guests on a scenic journey through the Cars world before a thrilling high-speed racing finale. The most popular attraction at the Disneyland Resort. Min 102cm.',image:'assets/images/disneyland_park/radiator_springs_racers.png',category:'family',topPick:true,lat:33.8057,lng:-117.9223,liveWaitMinutes:85,rating:4.9,speedKmh:88,heightM:0,inversions:0,openedYear:2012,minHeightCm:102,temporarilyClosed:false},
{id:'pirates_of_the_caribbean',name:'Pirates of the Caribbean',description:'The original and most beloved version of the greatest dark ride ever built — Disneyland\'s Pirates of the Caribbean is where it all began, featuring the authentic Blue Bayou Restaurant dining alongside the ride and the most complete and immersive version of the attraction. A Disneyland original since 1967. Suitable for all ages.',image:'assets/images/disneyland_park/pirates_of_the_carribean.png',category:'family',topPick:true,lat:33.8109,lng:-117.9213,liveWaitMinutes:30,rating:4.8,speedKmh:0,heightM:0,inversions:0,openedYear:1967,minHeightCm:0,temporarilyClosed:false},
{id:'haunted_mansion',name:'Haunted Mansion',description:'The original Haunted Mansion — Disneyland\'s version of this beloved classic features unique New Orleans Square theming and a slightly different experience to the Walt Disney World version, including the famous stretching room portraits and the iconic Doom Buggy vehicles. One of the greatest and most rerideable attractions in theme park history. Suitable for all ages.',image:'assets/images/disneyland_park/haunted_mansion.png',category:'family',topPick:true,lat:33.8113,lng:-117.9217,liveWaitMinutes:40,rating:4.9,speedKmh:0,heightM:0,inversions:0,openedYear:1969,minHeightCm:0,temporarilyClosed:false},
{id:'big_thunder_mountain',name:'Big Thunder Mountain Railroad',description:'The original and most beloved version of the wildest ride in the wilderness — Disneyland\'s Big Thunder Mountain Railroad features a spectacular island setting in the Rivers of America with a dramatic mine train layout through the haunted red rock canyons of the American Southwest. Min 102cm.',image:'assets/images/disneyland_park/big_thunder_mountain.png',category:'thrill',topPick:false,lat:33.8119,lng:-117.9221,liveWaitMinutes:45,rating:4.7,speedKmh:56,heightM:14,inversions:0,openedYear:1979,minHeightCm:102,temporarilyClosed:false},
{id:'space_mountain',name:'Space Mountain',description:'Disneyland\'s original and iconic Space Mountain — a classic indoor roller coaster through the cosmos in a distinctive twin-tracked configuration unique to Disneyland. A park icon since 1977 and one of the most beloved Disney attractions. Min 107cm.',image:'assets/images/disneyland_park/space_mountain.png',category:'thrill',topPick:false,lat:33.8143,lng:-117.9189,liveWaitMinutes:50,rating:4.6,speedKmh:45,heightM:18,inversions:0,openedYear:1977,minHeightCm:107,temporarilyClosed:false},
{id:'jungle_cruise',name:'Jungle Cruise',description:'The original Jungle Cruise — Disneyland\'s version of this beloved classic is the attraction that started it all, opening with the park in 1955. Features the classic live skipper narration, elaborate animatronic animals and the iconic terrible puns that have defined this attraction for 70 years. Suitable for all ages.',image:'assets/images/disneyland_park/jungle_cruise.png',category:'family',topPick:false,lat:33.8105,lng:-117.9209,liveWaitMinutes:30,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:1955,minHeightCm:0,temporarilyClosed:false},
{id:'millennium_falcon',name:'Millennium Falcon: Smugglers Run',description:'The most interactive Star Wars attraction ever built — Millennium Falcon: Smugglers Run places guests in the actual cockpit of the full-size Millennium Falcon and gives them a hands-on role as pilot, gunner or flight engineer on a smuggling mission. One of the most unique and replayable ride experiences at any Disney park. Min 97cm.',image:'assets/images/disneyland_park/milennium_falcon.png',category:'family',topPick:true,lat:33.8153,lng:-117.9231,liveWaitMinutes:60,rating:4.7,speedKmh:0,heightM:0,inversions:0,openedYear:2019,minHeightCm:97,temporarilyClosed:false},
{id:'web_slingers',name:'Web Slingers: A Spider-Man Adventure',description:'A thrilling interactive dark ride in Avengers Campus at Disney California Adventure — Web Slingers uses gesture-based technology to allow riders to shoot webs using their own hands without a physical controller, creating one of the most innovative and fun interactive ride experiences at any Disney park. Min 97cm.',image:'assets/images/disneyland_park/web_slingers.png',category:'family',topPick:false,lat:33.8063,lng:-117.9197,liveWaitMinutes:40,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2021,minHeightCm:97,temporarilyClosed:false},
{id:'sleeping_beauty_castle',name:'Sleeping Beauty Castle',description:'The original Disney castle and the most historically significant structure in theme park history — Sleeping Beauty Castle opened with Disneyland in 1955 and inspired every Disney castle that followed. Features the unique walk-through attraction telling the story of Sleeping Beauty in elaborate diorama scenes. Suitable for all ages.',image:'assets/images/disneyland_park/sleeping_beauty_castle.png',category:'family',topPick:true,lat:33.8121,lng:-117.9189,liveWaitMinutes:0,rating:4.9,speedKmh:0,heightM:0,inversions:0,openedYear:1955,minHeightCm:0,temporarilyClosed:false},
{id:'golden_zephyr',name:'Golden Zephyr',description:'A classic and atmospheric spinning rocket ride at Paradise Gardens Park — Golden Zephyr is a beautifully designed retro-futurist attraction that circles gracefully above the water and is one of the most charming and photogenic attractions at the Disneyland Resort. Suitable for all ages.',image:'assets/images/disneyland_park/golden_zephyr.png',category:'family',topPick:false,lat:33.8073,lng:-117.9207,liveWaitMinutes:15,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:2001,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/disneyland_park/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('attractions.json done, entries:',d.length);