const fs=require('fs');
function readJson(p){let r=fs.readFileSync(p,'utf8');if(r.charCodeAt(0)===0xFEFF)r=r.slice(1);return JSON.parse(r);}

const food=[
{id:'food_miners_cook_house',name:"Miner's Cook House",description:'The most popular and beloved dining destination at Six Flags Over Georgia — Miners Cook House serves classic Southern comfort food including fried chicken, mac and cheese and classic Southern sides in a fun and atmospheric mining-themed setting.',topPick:true,type:'Southern Comfort Food',image:'assets/images/six_flags_over_georgia/food_miners_cook_house.png',lat:33.7715,lng:-87.5515,rating:4.3,items:[{name:'Fried Chicken',description:'Classic Southern fried chicken with mac and cheese and biscuit',price:18},{name:'Mac and Cheese',description:'Classic creamy baked mac and cheese',price:12},{name:'Pulled Pork Sandwich',description:'Classic slow-cooked pulled pork with coleslaw',price:16},{name:'Sweet Tea',description:'Classic Southern sweet iced tea',price:4}]},
{id:'food_georgia_sandwich_company',name:'Georgia Sandwich Company',description:'A popular and convenient sandwich restaurant at Six Flags Over Georgia serving classic American sandwiches, wraps and salads. One of the most accessible and frequently visited quick-service dining destinations at the park.',topPick:false,type:'American Sandwiches',image:'assets/images/six_flags_over_georgia/food_georgia_sandwich_company.png',lat:33.7720,lng:-84.5520,rating:4.1,items:[{name:'Club Sandwich',description:'Classic turkey and bacon club sandwich with fries',price:15},{name:'Grilled Chicken Wrap',description:'Grilled chicken wrap with lettuce, tomato and ranch',price:14},{name:'Garden Salad',description:'Classic garden salad with choice of dressing',price:10},{name:'Soft Drink',description:'Large fountain drink',price:4}]},
{id:'food_gotham_city_eatery',name:'Gotham City Eatery',description:'A popular Batman-themed quick-service restaurant at Six Flags Over Georgia serving classic American comfort food including burgers, chicken strips and loaded fries in a fun superhero atmosphere.',topPick:false,type:'American Quick Service',image:'assets/images/six_flags_over_georgia/food_gotham_city_eatery.png',lat:33.7725,lng:-84.5525,rating:4.0,items:[{name:'Classic Burger',description:'Classic beef burger with cheese, lettuce and tomato',price:16},{name:'Chicken Strips',description:'Crispy chicken strips with fries and dipping sauce',price:14},{name:'Loaded Fries',description:'Thick fries with cheese sauce and bacon',price:9},{name:'Soft Drink',description:'Large fountain drink',price:4}]},
{id:'food_hickory_chip',name:'Hickory Chip BBQ',description:'A beloved BBQ restaurant at Six Flags Over Georgia serving classic Southern-style BBQ including smoked ribs, pulled pork and chicken with classic Georgia sides. One of the most authentic and satisfying dining experiences at any Atlanta area theme park.',topPick:true,type:'Southern BBQ',image:'assets/images/six_flags_over_georgia/food_hickory_chip.png',lat:33.7710,lng:-84.5510,rating:4.4,items:[{name:'Smoked Ribs',description:'Classic slow-smoked pork ribs with BBQ sauce and coleslaw',price:22},{name:'Pulled Pork Plate',description:'Classic pulled pork with baked beans and cornbread',price:16},{name:'BBQ Chicken',description:'Classic BBQ chicken half with two sides',price:18},{name:'Peach Cobbler',description:'Classic Georgia peach cobbler with ice cream',price:7}]},
{id:'food_dee_jays_diner',name:"Dee Jay's Diner",description:'A fun and popular classic American diner at Six Flags Over Georgia serving burgers, hot dogs, fries and classic diner milkshakes in a cheerful retro atmosphere.',topPick:false,type:'American Diner',image:'assets/images/six_flags_over_georgia/food_dee_jays_diner.png',lat:33.7718,lng:-84.5518,rating:4.1,items:[{name:'Classic Burger',description:'Classic diner burger with fries',price:15},{name:'Hot Dog',description:'Classic beef hot dog with all the trimmings',price:10},{name:'Milkshake',description:'Classic thick diner milkshake',price:8},{name:'Onion Rings',description:'Classic crispy onion rings',price:7}]}
];
fs.writeFileSync('assets/data/parks/six_flags_over_georgia/food.json',JSON.stringify(food,null,2),'utf8');
console.log('SFOG food done:',food.length);

const hotels=[
{id:'hotel_marriott_marquis',name:'Atlanta Marriott Marquis',description:'The most iconic and prestigious hotel in Atlanta — the Atlanta Marriott Marquis is a magnificent 4-star hotel with a breathtaking 47-storey atrium, outstanding restaurants, a spectacular pool and the finest hotel experience for Six Flags Over Georgia visitors staying in downtown Atlanta.',image:'assets/images/six_flags_over_georgia/hotel_marriott_marquis.png',lat:33.7602,lng:-84.3878,rating:4.7,topPick:true,website:'https://www.marriott.com/hotels/travel/atlmq-atlanta-marriott-marquis/',rooms:[{key:'standard_room',name:'Standard Room',description:'Elegant atrium-view room with free WiFi and pool access.',pricePerNight:280,breakfastIncluded:false},{key:'atrium_room',name:'Atrium View Room',description:'Premium room with stunning 47-storey atrium views.',pricePerNight:340,breakfastIncluded:false},{key:'suite',name:'Suite',description:'Magnificent suite with panoramic Atlanta views.',pricePerNight:580,breakfastIncluded:true}]},
{id:'hotel_renaissance_atlanta',name:'Renaissance Atlanta Waverly Hotel',description:'A magnificent 4-star Renaissance hotel in the Cobb Galleria area closest to Six Flags Over Georgia — offering elegant rooms, a spectacular pool, outstanding dining and the finest hotel experience in the western Atlanta suburbs.',image:'assets/images/six_flags_over_georgia/hotel_renaissance_atlanta.png',lat:33.8837,lng:-84.4677,rating:4.5,topPick:true,website:'https://www.marriott.com/hotels/travel/atlsh-renaissance-atlanta-waverly-hotel-and-convention-center/',rooms:[{key:'standard_room',name:'Standard Room',description:'Elegant room with free WiFi and pool access.',pricePerNight:200,breakfastIncluded:false},{key:'king_room',name:'King Room',description:'Premium king room with upgraded views.',pricePerNight:250,breakfastIncluded:false},{key:'suite',name:'Suite',description:'Spacious suite with living area and breakfast.',pricePerNight:420,breakfastIncluded:true}]},
{id:'hotel_hyatt_place',name:'Hyatt Place Atlanta/Six Flags',description:'A convenient and comfortable Hyatt Place hotel located closest to Six Flags Over Georgia — offering modern rooms, free breakfast and easy access to the park. The best positioned hotel for Six Flags Over Georgia visitors.',image:'assets/images/six_flags_over_georgia/hotel_hyatt_place.png',lat:33.7785,lng:-84.5623,rating:4.2,topPick:false,website:'https://www.hyatt.com',rooms:[{key:'standard_room',name:'Standard Room',description:'Modern room with free WiFi and breakfast.',pricePerNight:140,breakfastIncluded:true},{key:'king_room',name:'King Room',description:'Spacious king room with breakfast.',pricePerNight:165,breakfastIncluded:true},{key:'suite',name:'Suite',description:'Spacious suite with living area and breakfast.',pricePerNight:240,breakfastIncluded:true}]},
{id:'hotel_hilton_marietta',name:'Hilton Atlanta/Marietta Hotel',description:'A comfortable and well-regarded Hilton hotel in Marietta near Six Flags Over Georgia — offering pleasant rooms, a pool and easy access to both the park and downtown Atlanta.',image:'assets/images/six_flags_over_georgia/hotel_hilton_marietta.png',lat:33.9526,lng:-84.5499,rating:4.2,topPick:false,website:'https://www.hilton.com',rooms:[{key:'standard_room',name:'Standard Room',description:'Comfortable room with free WiFi and pool access.',pricePerNight:130,breakfastIncluded:false},{key:'king_room',name:'King Room',description:'Spacious king room with upgraded views.',pricePerNight:155,breakfastIncluded:false},{key:'suite',name:'Suite',description:'Spacious suite with living area.',pricePerNight:230,breakfastIncluded:true}]}
];
fs.writeFileSync('assets/data/parks/six_flags_over_georgia/hotels.json',JSON.stringify(hotels,null,2),'utf8');
console.log('SFOG hotels done:',hotels.length);

const pe={id:"six_flags_over_georgia",thumbnailAsset:"assets/images/six_flags_over_georgia/park_thumbnail.png",tailAsset:"",name:"Six Flags Over Georgia",type:"Theme Park",entryPrice:{child:59,adult:74},currency:"USD",openingHours:"10:30 - 21:00",lng:-84.5513,country:"USA",city:"Austell, Georgia",ticketsUrl:"https://www.sixflags.com/overgeorgia/tickets",queueTimesId:0};
const ie={id:"six_flags_over_georgia",name:"Six Flags Over Georgia",city:"Austell, Georgia",country:"USA",type:"Theme Park",lat:33.7717,lng:-84.5513,thumbnail:"assets/images/six_flags_over_georgia/park_thumbnail.png",website:"https://www.sixflags.com/overgeorgia",ticketsUrl:"https://www.sixflags.com/overgeorgia/tickets",detailAsset:"",openingHours:"10:30 - 21:00",entryPrices:{adult:74,child:59},currency:"USD",queueTimesId:0};
const parks=readJson('assets/data/parks.json');
if(!parks.find(p=>p.id==='six_flags_over_georgia')){parks.push(pe);fs.writeFileSync('assets/data/parks.json',JSON.stringify(parks,null,4),'utf8');console.log('parks.json:',parks.length);}
const index=readJson('assets/data/parks/parks_index.json');
if(!index.find(p=>p.id==='six_flags_over_georgia')){index.push(ie);fs.writeFileSync('assets/data/parks/parks_index.json',JSON.stringify(index,null,4),'utf8');console.log('parks_index.json:',index.length);}