const fs=require('fs');
const d=[
{id:'food_barneys_restaurant',name:"Barney's Restaurant",type:'Family Restaurant',image:'assets/images/gold_reef_city/food_barneys_restaurant.png',lat:-26.2462,lng:27.9943,rating:4.3,description:"The main sit-down dining destination at Gold Reef City — Barney's Restaurant serves generous South African and international meals including grilled meats, burgers, pasta and local favourites in a relaxed family atmosphere. A reliable choice for a substantial meal during your park visit.",topPick:true,items:[{name:'Grilled Chicken',description:'Flame-grilled half chicken with chips, salad and sauce',price:139},{name:'Beef Burger',description:'Handmade beef burger with cheese, lettuce, tomato and chips',price:115},{name:'Pasta Bolognese',description:'Spaghetti with slow-cooked beef bolognese and parmesan',price:109},{name:'Kids Meal',description:'Small chicken strips or burger with chips and juice',price:75}]},
{id:'food_panarottis',name:"Panarottis",type:'Pizza and Pasta',image:'assets/images/gold_reef_city/food_panarottis.png',lat:-26.2463,lng:27.9944,rating:4.1,description:"A well-known South African pizza and pasta chain with a Gold Reef City outlet — serving freshly prepared pizzas, pasta and salads in a fun and casual atmosphere. A popular choice for families wanting reliable Italian-style food during their visit.",topPick:true,items:[{name:'Margherita Pizza',description:'Classic tomato base with mozzarella and fresh basil',price:105},{name:'Pepperoni Pizza',description:'Tomato base with generous pepperoni and mozzarella',price:125},{name:'Pasta Arrabiata',description:'Penne pasta in a spicy tomato and garlic sauce',price:99},{name:'Garlic Bread',description:'Freshly baked garlic bread with herb butter',price:45}]},
{id:'food_calistos',name:"Calisto's",type:'Portuguese Chicken',image:'assets/images/gold_reef_city/food_calistos.png',lat:-26.2464,lng:27.9945,rating:4.2,description:"A popular South African Portuguese-style chicken restaurant serving flame-grilled peri-peri chicken, rolls and sides — one of the most flavourful and satisfying dining options at Gold Reef City.",topPick:true,items:[{name:'Quarter Peri-Peri Chicken',description:'Flame-grilled quarter chicken with peri-peri sauce and roll',price:89},{name:'Half Peri-Peri Chicken',description:'Flame-grilled half chicken with peri-peri sauce and chips',price:129},{name:'Chicken Roll',description:'Flame-grilled chicken in a Portuguese roll with chips',price:79},{name:'Coleslaw',description:'Creamy homemade coleslaw side salad',price:25}]},
{id:'food_oldees_diner',name:"Oldee's Diner",type:'American Diner',image:'assets/images/gold_reef_city/food_oldees_diner.png',lat:-26.2465,lng:27.9946,rating:3.9,description:"A retro American-style diner serving classic diner food including hot dogs, burgers and loaded fries in a fun 1950s atmosphere — ideal for a quick and satisfying snack or light meal between rides.",topPick:false,items:[{name:'Classic Hot Dog',description:'Grilled frankfurter in a toasted bun with mustard and ketchup',price:65},{name:'Diner Burger',description:'Classic beef burger with cheese and fries',price:95},{name:'Loaded Fries',description:'Thick chips topped with cheese sauce and bacon bits',price:55},{name:'Milkshake',description:'Thick American-style milkshake in chocolate or vanilla',price:55}]},
{id:'food_anat',name:"Anat",type:'Middle Eastern',image:'assets/images/gold_reef_city/food_anat.png',lat:-26.2466,lng:27.9947,rating:4.0,description:"A popular South African Middle Eastern food chain serving freshly made falafel, shawarma and pita wraps — a lighter and flavourful alternative to standard theme park fare and one of the most distinctive dining options at Gold Reef City.",topPick:false,items:[{name:'Chicken Shawarma',description:'Marinated chicken shawarma in warm pita with salad and tahini',price:85},{name:'Falafel Wrap',description:'Crispy falafel in warm pita with hummus, salad and pickles',price:75},{name:'Combo Plate',description:'Mixed shawarma and falafel plate with pita, salad and dips',price:110},{name:'Soft Drink',description:'Selection of cold beverages',price:25}]}
];
fs.writeFileSync('assets/data/parks/gold_reef_city/food.json',JSON.stringify(d,null,2),'utf8');
console.log('food.json done, entries:',d.length);