const fs=require('fs');
const d=[
{id:'adrenaline',name:'Adrenaline',description:'The most thrilling and beloved roller coaster at Calaway Park — Adrenaline is a spectacular steel coaster delivering high-speed thrills through a layout of drops, turns and airtime moments in a beautifully landscaped setting. The most popular attraction at Western Canada\'s largest theme park. Min 122cm.',image:'assets/images/calaway_park/adrenaline.png',category:'thrill',topPick:true,lat:51.0862,lng:-114.2108,liveWaitMinutes:45,rating:4.6,speedKmh:85,heightM:28,inversions:0,openedYear:2015,minHeightCm:122,temporarilyClosed:false},
{id:'vortex',name:'Vortex',description:'A classic and thrilling looping coaster at Calaway Park delivering inversions and high-speed thrills — Vortex is one of the most beloved and enduring coaster experiences at Western Canada\'s largest theme park. Min 122cm.',image:'assets/images/calaway_park/vortex.png',category:'thrill',topPick:true,lat:51.0859,lng:-114.2112,liveWaitMinutes:35,rating:4.4,speedKmh:80,heightM:26,inversions:2,openedYear:1996,minHeightCm:122,temporarilyClosed:false},
{id:'timber_falls',name:'Timber Falls',description:'A beloved and refreshing log flume ride at Calaway Park plunging riders down a dramatic waterfall finale — Timber Falls is one of the most popular and rerideable water attractions at any Western Canadian theme park. Min 107cm.',image:'assets/images/calaway_park/timber_falls.png',category:'family',topPick:true,lat:51.0865,lng:-114.2105,liveWaitMinutes:30,rating:4.3,speedKmh:0,heightM:15,inversions:0,openedYear:1989,minHeightCm:107,temporarilyClosed:false},
{id:'free_fallin',name:"Free Fallin'",description:'A thrilling drop tower experience at Calaway Park catapulting riders skyward before a freefall descent from 30 metres — Free Fallin\' is one of the most intense and memorable non-coaster thrill experiences at any Western Canadian theme park. Min 122cm.',image:'assets/images/calaway_park/free_fallin.png',category:'thrill',topPick:true,lat:51.0856,lng:-114.2115,liveWaitMinutes:25,rating:4.4,speedKmh:0,heightM:30,inversions:0,openedYear:2005,minHeightCm:122,temporarilyClosed:false},
{id:'drop_tower',name:'Drop Zone',description:'A classic drop tower attraction at Calaway Park delivering a sudden freefall descent with spectacular views over the Rocky Mountain foothills — Drop Zone is a popular and thrilling non-coaster experience at Calaway Park. Min 107cm.',image:'assets/images/calaway_park/drop_tower.png',category:'thrill',topPick:false,lat:51.0858,lng:-114.2118,liveWaitMinutes:20,rating:4.2,speedKmh:0,heightM:25,inversions:0,openedYear:2000,minHeightCm:107,temporarilyClosed:false},
{id:'dream_machine',name:'Dream Machine',description:'A classic and thrilling enterprise flat ride at Calaway Park rotating riders through a full 360-degree vertical loop — Dream Machine is one of the most popular and exhilarating flat ride experiences at any Western Canadian theme park. Min 122cm.',image:'assets/images/calaway_park/dream_machine.png',category:'thrill',topPick:false,lat:51.0863,lng:-114.2102,liveWaitMinutes:20,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:1998,minHeightCm:122,temporarilyClosed:false},
{id:'chaos',name:'Chaos',description:'A wildly spinning flat ride at Calaway Park delivering disorienting rotations in multiple directions — Chaos is one of the most entertaining and popular flat rides at Western Canada\'s largest theme park. Min 107cm.',image:'assets/images/calaway_park/chaos.png',category:'thrill',topPick:false,lat:51.0861,lng:-114.2120,liveWaitMinutes:15,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:1995,minHeightCm:107,temporarilyClosed:false},
{id:'wave_rider',name:'Wave Rider',description:'A popular and refreshing circular water ride at Calaway Park spinning riders through waves and water jets — Wave Rider is one of the most enjoyable and rerideable water attractions at Calaway Park. Suitable for all ages.',image:'assets/images/calaway_park/wave_rider.png',category:'family',topPick:false,lat:51.0866,lng:-114.2100,liveWaitMinutes:20,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:1992,minHeightCm:0,temporarilyClosed:false},
{id:'bumper_boats',name:'Bumper Boats',description:'A fun and splashy bumper boat experience at Calaway Park — guests pilot individual water vessels and attempt to soak each other with water cannons in one of the most entertaining and family-friendly experiences at any Western Canadian theme park. Suitable for all ages.',image:'assets/images/calaway_park/bumper_boats.png',category:'family',topPick:false,lat:51.0868,lng:-114.2098,liveWaitMinutes:15,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:1988,minHeightCm:0,temporarilyClosed:false},
{id:'ocean_motion',name:'Ocean Motion',description:'A classic giant swinging ship ride at Calaway Park that swings riders back and forth to ever-greater heights — Ocean Motion is one of the most popular and beloved flat ride experiences at Calaway Park. Min 107cm.',image:'assets/images/calaway_park/ocean_motion.png',category:'thrill',topPick:false,lat:51.0854,lng:-114.2122,liveWaitMinutes:20,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:1990,minHeightCm:107,temporarilyClosed:false},
{id:'klondike_mine',name:'Klondike Mine',description:'A charming and entertaining dark ride at Calaway Park themed to the Klondike Gold Rush — Klondike Mine takes guests on a gentle narrated journey through the colourful world of the Canadian gold rush with humorous scenes and characters. Suitable for all ages.',image:'assets/images/calaway_park/klondike_mine.png',category:'family',topPick:false,lat:51.0870,lng:-114.2095,liveWaitMinutes:15,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:1982,minHeightCm:0,temporarilyClosed:false},
{id:'balloon_ascension',name:'Balloon Ascension',description:'A classic hot air balloon-themed tower ride at Calaway Park gently lifting guests for spectacular panoramic views over the park and the Rocky Mountain foothills — Balloon Ascension is the most scenic and atmospheric family attraction at Calaway Park. Suitable for all ages.',image:'assets/images/calaway_park/balloon_ascension.png',category:'family',topPick:true,lat:51.0872,lng:-114.2092,liveWaitMinutes:10,rating:4.2,speedKmh:0,heightM:20,inversions:0,openedYear:1982,minHeightCm:0,temporarilyClosed:false},
{id:'flying_ace',name:'Flying Ace',description:'A classic and popular swinging aeroplane ride at Calaway Park delivering a thrilling aerial spinning experience — Flying Ace is one of the most fun and accessible thrill rides at any Western Canadian theme park. Min 107cm.',image:'assets/images/calaway_park/flying_ace.png',category:'family',topPick:false,lat:51.0855,lng:-114.2125,liveWaitMinutes:15,rating:3.9,speedKmh:0,heightM:0,inversions:0,openedYear:1988,minHeightCm:107,temporarilyClosed:false},
{id:'air_gliders',name:'Air Gliders',description:'A gentle and scenic sky glider ride at Calaway Park carrying guests high above the park in open gondolas for beautiful aerial views over the park and the surrounding Rocky Mountain foothills landscape. Suitable for all ages.',image:'assets/images/calaway_park/air_gliders.png',category:'family',topPick:false,lat:51.0874,lng:-114.2088,liveWaitMinutes:10,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:1982,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/calaway_park/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('Calaway Park attractions done:',d.length);