const fs=require('fs');
const d=[
{id:'worlds_largest_aquarium',name:'World Largest Aquarium',description:'Chimelong Ocean Kingdom is home to the largest aquarium on earth — a Guinness World Record holder with a total water volume of 48.75 million litres and a single viewing panel measuring 39.6 metres wide and 8.3 metres tall. The aquarium houses the world largest collection of whale sharks alongside manta rays, thousands of tropical fish and extraordinary marine biodiversity from every ocean on the planet. Suitable for all ages.',image:'assets/images/chimelong_ocean_kingdom/worlds_largest_aquarium.png',category:'family',topPick:true,lat:22.1100,lng:113.5620,liveWaitMinutes:0,rating:4.9,speedKmh:0,heightM:0,inversions:0,openedYear:2014,minHeightCm:0,temporarilyClosed:false},
{id:'whale_shark_voyage',name:'Whale Shark Voyage',description:'An extraordinary underwater tunnel journey through the world largest aquarium — guests float through a 180-degree transparent tunnel completely surrounded by whale sharks, manta rays and thousands of marine creatures in an immersive experience unlike anything else on earth. One of the most breathtaking wildlife encounters available at any theme park worldwide. Suitable for all ages.',image:'assets/images/chimelong_ocean_kingdom/whale_shark_voyage.png',category:'family',topPick:true,lat:22.1101,lng:113.5621,liveWaitMinutes:25,rating:4.9,speedKmh:0,heightM:0,inversions:0,openedYear:2014,minHeightCm:0,temporarilyClosed:false},
{id:'ocean_kingdom_coaster',name:'Ocean Kingdom Roller Coaster',description:'A spectacular roller coaster that launches riders over and around the ocean kingdom complex delivering thrilling speed, inversions and extraordinary views over the Hengqin Island resort and the South China Sea. The premier thrill ride at Chimelong Ocean Kingdom. Min 130cm.',image:'assets/images/chimelong_ocean_kingdom/ocean_kingdom_coaster.png',category:'thrill',topPick:true,lat:22.1102,lng:113.5622,liveWaitMinutes:50,rating:4.6,speedKmh:100,heightM:38,inversions:2,openedYear:2014,minHeightCm:130,temporarilyClosed:false},
{id:'deep_sea_adventure',name:'Deep Sea Adventure',description:'An immersive submarine-themed dark ride that takes guests on a spectacular voyage to the bottom of the ocean — encountering giant squid, anglerfish, hydrothermal vents and the extraordinary creatures of the deep sea in one of the most atmospheric dark rides in China. Min 100cm.',image:'assets/images/chimelong_ocean_kingdom/deep_sea_adventure.png',category:'family',topPick:true,lat:22.1103,lng:113.5623,liveWaitMinutes:40,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2014,minHeightCm:100,temporarilyClosed:false},
{id:'dolphin_paradise',name:'Dolphin Paradise',description:'A spectacular dolphin show in a purpose-built arena where Chimelong resident bottlenose and Pacific white-sided dolphins perform breathtaking acrobatic sequences with their expert trainers — one of the most impressive marine animal presentations in Asia. Suitable for all ages.',image:'assets/images/chimelong_ocean_kingdom/dolphin_paradise.png',category:'family',topPick:true,lat:22.1104,lng:113.5624,liveWaitMinutes:0,rating:4.7,speedKmh:0,heightM:0,inversions:0,openedYear:2014,minHeightCm:0,temporarilyClosed:false},
{id:'beluga_whale_show',name:'Beluga Whale Show',description:'A uniquely enchanting show featuring Chimelong resident beluga whales in a spectacular performance combining swimming, singing and astonishing behaviour demonstrations with their dedicated trainers — one of the most charming and beloved shows at Chimelong Ocean Kingdom. Suitable for all ages.',image:'assets/images/chimelong_ocean_kingdom/beluga_whale_show.png',category:'family',topPick:true,lat:22.1105,lng:113.5625,liveWaitMinutes:0,rating:4.6,speedKmh:0,heightM:0,inversions:0,openedYear:2014,minHeightCm:0,temporarilyClosed:false},
{id:'penguin_encounter',name:'Penguin Encounter',description:'A remarkable Antarctic-themed habitat housing hundreds of penguins including gentoo, macaroni and king penguins in a temperature-controlled environment replicating the Southern Ocean — one of the largest penguin collections at any attraction in the world. Suitable for all ages.',image:'assets/images/chimelong_ocean_kingdom/penguin_encounter.png',category:'family',topPick:true,lat:22.1106,lng:113.5626,liveWaitMinutes:15,rating:4.6,speedKmh:0,heightM:0,inversions:0,openedYear:2014,minHeightCm:0,temporarilyClosed:false},
{id:'polar_ocean_world',name:'Polar Ocean World',description:'A magnificent polar themed zone featuring beluga whales, walruses and Arctic wildlife in beautifully recreated polar habitats — guests can observe these extraordinary animals through massive underwater viewing windows in one of the finest polar wildlife experiences in China. Suitable for all ages.',image:'assets/images/chimelong_ocean_kingdom/polar_ocean_world.png',category:'family',topPick:false,lat:22.1107,lng:113.5627,liveWaitMinutes:10,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2014,minHeightCm:0,temporarilyClosed:false},
{id:'manta_ray_bay',name:'Manta Ray Bay',description:'A breathtaking open bay habitat where guests can observe giant manta rays gliding through the water in a vast lagoon — one of the most serene and visually stunning wildlife encounters at Chimelong Ocean Kingdom. Suitable for all ages.',image:'assets/images/chimelong_ocean_kingdom/manta_ray_bay.png',category:'family',topPick:false,lat:22.1108,lng:113.5628,liveWaitMinutes:0,rating:4.4,speedKmh:0,heightM:0,inversions:0,openedYear:2014,minHeightCm:0,temporarilyClosed:false},
{id:'ocean_tunnel_walk',name:'Ocean Tunnel Walk',description:'A walk-through underwater tunnel experience completely surrounded by sharks, rays and thousands of tropical fish — guests stroll through a transparent tube at the bottom of a massive aquarium tank in an extraordinarily immersive and peaceful marine encounter. Suitable for all ages.',image:'assets/images/chimelong_ocean_kingdom/ocean_tunnel_walk.png',category:'family',topPick:false,lat:22.1109,lng:113.5629,liveWaitMinutes:5,rating:4.7,speedKmh:0,heightM:0,inversions:0,openedYear:2014,minHeightCm:0,temporarilyClosed:false},
{id:'sea_lion_theater',name:'Sea Lion Theater',description:'A hilarious and charming sea lion show where Chimelong resident California sea lions perform comedy routines and astonishing behaviour demonstrations — one of the most entertaining and family-friendly shows at the park. Suitable for all ages.',image:'assets/images/chimelong_ocean_kingdom/sea_lion_theater.png',category:'family',topPick:false,lat:22.1110,lng:113.5630,liveWaitMinutes:0,rating:4.3,speedKmh:0,heightM:0,inversions:0,openedYear:2014,minHeightCm:0,temporarilyClosed:false},
{id:'walrus_world',name:'Walrus World',description:'A spectacular walrus habitat where guests can observe the enormous and charismatic Pacific walruses of Chimelong Ocean Kingdom — feeding sessions and keeper talks provide extraordinary close encounters with these magnificent Arctic giants. Suitable for all ages.',image:'assets/images/chimelong_ocean_kingdom/walrus_world.png',category:'family',topPick:false,lat:22.1111,lng:113.5631,liveWaitMinutes:0,rating:4.3,speedKmh:0,heightM:0,inversions:0,openedYear:2014,minHeightCm:0,temporarilyClosed:false},
{id:'pirate_galleon_ride',name:'Pirate Galleon Ride',description:'A classic swinging ship ride themed to high-seas pirate adventure — the Pirate Galleon sends riders soaring back and forth at increasing height delivering accessible thrills for older children and adults. Min 120cm.',image:'assets/images/chimelong_ocean_kingdom/pirate_galleon_ride.png',category:'thrill',topPick:false,lat:22.1112,lng:113.5632,liveWaitMinutes:20,rating:4.1,speedKmh:0,heightM:18,inversions:0,openedYear:2014,minHeightCm:120,temporarilyClosed:false},
{id:'aqua_loop_slides',name:'Aqua Loop Slides',description:'A thrilling collection of high-speed water slides including the iconic loop slide that sends riders through a vertical loop in a transparent tube — one of the most exciting water slide attractions in China. Min 120cm.',image:'assets/images/chimelong_ocean_kingdom/aqua_loop_slides.png',category:'thrill',topPick:true,lat:22.1113,lng:113.5633,liveWaitMinutes:35,rating:4.4,speedKmh:0,heightM:20,inversions:0,openedYear:2014,minHeightCm:120,temporarilyClosed:false},
{id:'waterslide_track_of_walrus_mountain',name:'Waterslide Track of Walrus Mountain',description:'A spectacular multi-slide water attraction on the iconic Walrus Mountain structure — guests choose from several thrilling slides of different speeds and intensities descending from the summit of the mountain through twisting tubes and open flumes. Min 110cm.',image:'assets/images/chimelong_ocean_kingdom/waterslide_track_of_walrus_mountain.png',category:'thrill',topPick:false,lat:22.1114,lng:113.5634,liveWaitMinutes:30,rating:4.2,speedKmh:0,heightM:25,inversions:0,openedYear:2014,minHeightCm:110,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/chimelong_ocean_kingdom/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('attractions.json done, entries:',d.length);