const fs=require('fs');
const d=[
{id:'food_mythos_restaurant',name:'Mythos Restaurant',description:'Voted the best theme park restaurant in the world multiple times — Mythos Restaurant is a breathtakingly beautiful fine dining restaurant built inside a natural cave formation overlooking the lagoon at Islands of Adventure, serving outstanding Mediterranean and international cuisine. The single finest restaurant at any theme park in the world. Advance reservations recommended.',topPick:true,type:'Mediterranean Fine Dining',image:'assets/images/islands_of_adventure/food_mythos_restaurant.png',lat:28.4726,lng:-81.4712,rating:4.9,items:[{name:'Pad Thai',description:'Classic pad thai with shrimp, tofu, bean sprouts and crushed peanuts',price:24},{name:'Gorgonzola Filet',description:'Centre-cut beef filet with gorgonzola crust and truffle mashed potatoes',price:42},{name:'Lamb Chops',description:'Grilled lamb chops with mint chimichurri and roasted vegetables',price:38},{name:'Lava Cake',description:'Classic warm chocolate lava cake with vanilla ice cream',price:12}]},
{id:'food_three_broomsticks_ioa',name:'Three Broomsticks',description:'A magnificent Great Hall-style restaurant in Hogsmeade at Islands of Adventure serving hearty traditional British wizarding fare in a spectacular timber-beamed setting. One of the most immersive and popular themed restaurants at any theme park in the world.',topPick:true,type:'Wizarding British',image:'assets/images/islands_of_adventure/food_three_broomsticks_ioa.png',lat:28.4720,lng:-81.4718,rating:4.6,items:[{name:'Great Feast',description:'Whole roasted chicken with roast potatoes, corn and garden salad for 4',price:56},{name:'Butterbeer',description:'Legendary Wizarding World Butterbeer with sweet butterscotch foam',price:8},{name:'Pumpkin Juice',description:'Unique Wizarding World pumpkin and apple juice blend',price:7},{name:'Butterbeer Ice Cream',description:'Exclusive Butterbeer soft serve ice cream',price:6}]},
{id:'food_confisco_grille',name:'Confisco Grille',description:'A classic and atmospheric full-service restaurant at the entrance to Islands of Adventure — Confisco Grille serves a diverse international menu including pasta, burgers, sandwiches and grilled specialities in a fun adventure-themed environment filled with confiscated items from around the world.',topPick:false,type:'International Adventure',image:'assets/images/islands_of_adventure/food_confisco_grille.png',lat:28.4740,lng:-81.4700,rating:4.3,items:[{name:'Tuscan Chicken',description:'Grilled chicken with sun-dried tomato cream sauce and pasta',price:22},{name:'Classic Burger',description:'Angus beef burger with cheese, bacon and fries',price:18},{name:'Chicken Caesar Wrap',description:'Grilled chicken Caesar wrap with fries',price:16},{name:'Craft Beer',description:'Pint of craft beer',price:8}]},
{id:'food_circus_mcgurkus',name:'Circus McGurkus Cafe Stoo-pendous',description:'A wonderfully whimsical Dr. Seuss-themed restaurant in Seuss Landing at Islands of Adventure — Circus McGurkus serves classic American quick-service food including pizza, pasta, fried chicken and burgers under an impossibly colourful circus big top. The most cheerful and family-friendly dining at Islands of Adventure.',topPick:false,type:'Seuss Themed American',image:'assets/images/islands_of_adventure/food_circus_mcgurkus.png',lat:28.4744,lng:-81.4700,rating:4.1,items:[{name:'Pizza',description:'Classic cheese and pepperoni pizza',price:13},{name:'Fried Chicken',description:'Classic crispy fried chicken with fries',price:15},{name:'Mac and Cheese',description:'Classic creamy macaroni and cheese',price:11},{name:'Soft Drink',description:'Large fountain drink',price:4}]},
{id:'food_comic_strip_cafe',name:'Comic Strip Cafe',description:'A classic and convenient quick-service restaurant in Toon Lagoon at Islands of Adventure — Comic Strip Cafe serves a wide variety of fast food options including pizza, burgers, Asian food and American classics in a fun comic strip-themed environment.',topPick:false,type:'Multi-Cuisine Quick Service',image:'assets/images/islands_of_adventure/food_comic_strip_cafe.png',lat:28.4736,lng:-81.4710,rating:3.9,items:[{name:'Cheeseburger',description:'Classic beef cheeseburger with fries',price:15},{name:'Cheese Pizza',description:'Classic cheese pizza slice',price:9},{name:'Chicken Stir Fry',description:'Classic chicken stir fry with rice',price:14},{name:'Soft Drink',description:'Large fountain drink',price:4}]}
];
fs.writeFileSync('assets/data/parks/islands_of_adventure/food.json',JSON.stringify(d,null,2),'utf8');
console.log('IOA food done:',d.length);