const fs=require('fs');
const d=[
{id:'journey_to_the_center_of_the_earth',name:'Journey to the Center of the Earth',description:'The crown jewel of Tokyo DisneySea and one of the greatest theme park rides ever built — Journey to the Center of the Earth is a masterpiece of immersive storytelling that takes guests deep into an extinct volcano aboard a Terra Buggy vehicle, through breathtaking subterranean caverns filled with extraordinary creatures, before a terrifying final encounter and a dramatic high-speed escape that launches riders to the surface at incredible speed. Widely regarded as one of the top five theme park attractions in the world. Min 117cm.',image:'assets/images/tokyo_disneysea/journey_to_the_center_of_the_world.png',category:'thrill',topPick:true,lat:35.6267,lng:139.8855,liveWaitMinutes:120,rating:4.9,speedKmh:75,heightM:28,inversions:0,openedYear:2001,minHeightCm:117,temporarilyClosed:false},
{id:'tower_of_terror',name:'Tower of Terror',description:'The most elaborately themed drop tower ever built — Tokyo DisneySea\'s Tower of Terror features a unique storyline involving the cursed Harrison Hightower III and his stolen idol, delivering guests into a supernatural elevator that plunges in multiple unpredictable drop sequences through beautifully themed environments. The most sophisticated version of the Tower of Terror attraction in the world. Min 102cm.',image:'assets/images/tokyo_disneysea/tower_of_terror.png',category:'thrill',topPick:true,lat:35.6269,lng:139.8857,liveWaitMinutes:90,rating:4.8,speedKmh:0,heightM:45,inversions:0,openedYear:2001,minHeightCm:102,temporarilyClosed:false},
{id:'indiana_jones_adventure',name:'Indiana Jones Adventure: Temple of the Crystal Skull',description:'A spectacular jeep-based adventure ride through the forbidden ruins of the Crystal Skull temple — Indiana Jones Adventure at Tokyo DisneySea features extraordinary practical effects, animatronic figures and a thrilling high-speed chase through elaborate jungle ruins. One of the most beloved and rerideable attractions at any Disney park in the world. Min 117cm.',image:'assets/images/tokyo_disneysea/indiana_jones_adventure.png',category:'thrill',topPick:true,lat:35.6271,lng:139.8859,liveWaitMinutes:100,rating:4.8,speedKmh:0,heightM:0,inversions:0,openedYear:2001,minHeightCm:117,temporarilyClosed:false},
{id:'raging_spirits',name:'Raging Spirits',description:'A unique inversion roller coaster in the Lost River Delta zone — Raging Spirits delivers a single complete loop inversion and high-speed sweeping turns through dramatic ancient ruins and fire effects in the most thrilling traditional coaster experience at Tokyo DisneySea. Min 117cm.',image:'assets/images/tokyo_disneysea/raging_spirits.png',category:'thrill',topPick:false,lat:35.6273,lng:139.8861,liveWaitMinutes:60,rating:4.5,speedKmh:85,heightM:28,inversions:1,openedYear:2006,minHeightCm:117,temporarilyClosed:false},
{id:'soaring_fantastic_flight',name:'Soaring: Fantastic Flight',description:'A breathtaking hang-glider simulation over the world\'s most beautiful natural and man-made wonders — Soaring: Fantastic Flight at Tokyo DisneySea features a uniquely Japanese version of the Soaring experience with sweeping wind, scents and projection of extraordinary global landscapes. One of the most peaceful and beautiful attractions at any Disney park. Min 102cm.',image:'assets/images/tokyo_disneysea/soaring_fantastic_flight.png',category:'family',topPick:true,lat:35.6275,lng:139.8863,liveWaitMinutes:80,rating:4.8,speedKmh:0,heightM:0,inversions:0,openedYear:2019,minHeightCm:102,temporarilyClosed:false},
{id:'fantasy_springs',name:'Fantasy Springs',description:'Tokyo DisneySea\'s newest and most spectacular themed land opened in 2024 — Fantasy Springs is an extraordinary expansion featuring three new attractions including the Frozen Kingdom, Rapunzel\'s Forest and Tinker Bell\'s Fairy Festival, plus the spectacular Fantasy Springs Hotel. The most ambitious Disney park expansion in Asia. Suitable for all ages.',image:'assets/images/tokyo_disneysea/fantasy_springs.png',category:'family',topPick:true,lat:35.6277,lng:139.8865,liveWaitMinutes:90,rating:4.9,speedKmh:0,heightM:0,inversions:0,openedYear:2024,minHeightCm:0,temporarilyClosed:false},
{id:'sindbads_storybook_voyage',name:'Sindbad\'s Storybook Voyage',description:'A gentle and enchanting boat ride through the legendary seven voyages of Sindbad — featuring an original Alan Menken score, elaborate animatronic scenes and some of the most beautiful Audio-Animatronic work in any Disney park. One of the most beloved and uniquely Tokyo DisneySea attractions in the world. Suitable for all ages.',image:'assets/images/tokyo_disneysea/sindbads_storybook_voyage.png',category:'family',topPick:true,lat:35.6265,lng:139.8853,liveWaitMinutes:30,rating:4.7,speedKmh:0,heightM:0,inversions:0,openedYear:2001,minHeightCm:0,temporarilyClosed:false},
{id:'aquatopia',name:'Aquatopia',description:'A uniquely chaotic and unpredictable water dodgem attraction in the Discovery Bay zone — Aquatopia sends guests spinning in water vehicles across a geothermal lagoon with seemingly random movements that create a uniquely joyful and rerideable experience found only at Tokyo DisneySea. Suitable for all ages.',image:'assets/images/tokyo_disneysea/aquatopia.png',category:'family',topPick:false,lat:35.6263,lng:139.8851,liveWaitMinutes:40,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2001,minHeightCm:0,temporarilyClosed:false},
{id:'20000_leagues_under_the_sea',name:'20,000 Leagues Under the Sea',description:'A uniquely atmospheric submarine dark ride based on the Jules Verne classic — 20,000 Leagues Under the Sea takes guests aboard a submarine vessel exploring mysterious underwater caverns with extraordinary lighting effects and animatronic sea creatures in one of the most atmospheric dark rides at any Disney park in Asia. Min 102cm.',image:'assets/images/tokyo_disneysea/20000_leagues_under_the_sea.png',category:'family',topPick:false,lat:35.6261,lng:139.8849,liveWaitMinutes:35,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2001,minHeightCm:102,temporarilyClosed:false},
{id:'stormrider',name:'StormRider',description:'A high-definition flight simulator attraction that plunges guests into the eye of a massive storm aboard an experimental aircraft — StormRider delivers exhilarating physical effects, spectacular projected environments and genuinely thrilling turbulence simulation in one of the most exciting simulator attractions at any Disney park in Asia. Min 117cm.',image:'assets/images/tokyo_disneysea/stormrider.png',category:'thrill',topPick:false,lat:35.6259,lng:139.8847,liveWaitMinutes:45,rating:4.4,speedKmh:0,heightM:0,inversions:0,openedYear:2001,minHeightCm:117,temporarilyClosed:false},
{id:'turtle_talk',name:'Turtle Talk',description:'A magical interactive show where Crush the sea turtle from Finding Nemo holds a real-time conversation with the audience using groundbreaking technology — Turtle Talk is one of the most charming, funny and technically impressive family shows at any Disney park worldwide. Suitable for all ages.',image:'assets/images/tokyo_disneysea/turtle_talk.png',category:'family',topPick:false,lat:35.6257,lng:139.8845,liveWaitMinutes:20,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2009,minHeightCm:0,temporarilyClosed:false},
{id:'mediterranean_harbour',name:'Mediterranean Harbour',description:'The breathtaking centrepiece of Tokyo DisneySea — the Mediterranean Harbour is a stunning recreation of a southern European waterfront port with Mount Prometheus rising dramatically above it, gondolas gliding across the water and elaborately detailed Italian and Venetian architecture. The most beautiful themed area of any Disney park in the world. Suitable for all ages.',image:'assets/images/tokyo_disneysea/mediterranean_harbour.png',category:'family',topPick:true,lat:35.6255,lng:139.8843,liveWaitMinutes:0,rating:4.9,speedKmh:0,heightM:0,inversions:0,openedYear:2001,minHeightCm:0,temporarilyClosed:false},
{id:'mount_prometheus',name:'Mount Prometheus',description:'The iconic active volcano that dominates the Tokyo DisneySea skyline — Mount Prometheus is the centerpiece of the park and houses Journey to the Center of the Earth within its interior. The volcano creates fire and smoke effects and is the most photographed and recognised symbol of Tokyo DisneySea. Suitable for all ages.',image:'assets/images/tokyo_disneysea/mount_prometheus.png',category:'family',topPick:true,lat:35.6253,lng:139.8841,liveWaitMinutes:0,rating:4.8,speedKmh:0,heightM:0,inversions:0,openedYear:2001,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/tokyo_disneysea/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('attractions.json done, entries:',d.length);