const fs=require('fs');
const d=[
{id:'leviathan',name:'Leviathan',description:'The most intense roller coaster on the Gold Coast — Leviathan is a world-class inverted coaster that sends riders through a spectacular layout of inversions, loops and high-speed turns. One of the finest coasters in Australian theme park history and the undisputed crown jewel of Sea World Gold Coast. Min 130cm.',image:'assets/images/sea_world_gold_coast/leviathan.png',category:'thrill',topPick:true,lat:-27.9625,lng:153.4283,liveWaitMinutes:65,rating:4.8,speedKmh:95,heightM:35,inversions:4,openedYear:2023,minHeightCm:130,temporarilyClosed:false},
{id:'jet_rescue',name:'Jet Rescue',description:'A thrilling launched coaster themed to rescue jets speeding over ocean waves — Jet Rescue blasts riders along a high-speed coastal layout at 72 km/h with banks and airtime hills that make it one of the most exciting family-thrill coasters in Australia. Min 110cm.',image:'assets/images/sea_world_gold_coast/jet_rescue.png',category:'thrill',topPick:true,lat:-27.9627,lng:153.4285,liveWaitMinutes:50,rating:4.5,speedKmh:72,heightM:18,inversions:0,openedYear:2009,minHeightCm:110,temporarilyClosed:false},
{id:'storm_coaster',name:'Storm Coaster',description:'A unique water coaster that combines the thrill of a roller coaster with the soaking of a water ride — Storm Coaster propels riders uphill using powerful water jets before releasing them in a dramatic plunge back down. One of the most original ride concepts at any Australian theme park. Min 110cm.',image:'assets/images/sea_world_gold_coast/storm_coaster.png',category:'thrill',topPick:true,lat:-27.9629,lng:153.4287,liveWaitMinutes:40,rating:4.4,speedKmh:60,heightM:20,inversions:0,openedYear:2006,minHeightCm:110,temporarilyClosed:false},
{id:'vortex',name:'Vortex',description:'A suspended looping coaster where riders hang beneath the track through a series of inversions at speed — one of the most classic and enduring thrill coasters in Australian theme park history and a Sea World institution. Min 130cm.',image:'assets/images/sea_world_gold_coast/vortex.png',category:'thrill',topPick:false,lat:-27.9631,lng:153.4289,liveWaitMinutes:35,rating:4.2,speedKmh:80,heightM:28,inversions:3,openedYear:1995,minHeightCm:130,temporarilyClosed:false},
{id:'sky_flyer',name:'Sky Flyer',description:'A thrilling giant swing ride that launches riders high above the Gold Coast coastline delivering breathtaking views of the ocean, the Sea World lagoon and the Broadwater before a terrifying free swing. One of the most spectacular flat rides on the Gold Coast. Min 120cm.',image:'assets/images/sea_world_gold_coast/sky_flyer.png',category:'thrill',topPick:false,lat:-27.9623,lng:153.4281,liveWaitMinutes:25,rating:4.3,speedKmh:0,heightM:40,inversions:0,openedYear:2005,minHeightCm:120,temporarilyClosed:false},
{id:'vikings_revenge',name:'Vikings Revenge',description:'A classic pendulum swing ride themed to ferocious Viking longships — Vikings Revenge sends riders soaring back and forth at increasing height in a crowd-pleasing and accessible thrill experience. Min 120cm.',image:'assets/images/sea_world_gold_coast/vikings_revenge.png',category:'thrill',topPick:false,lat:-27.9633,lng:153.4291,liveWaitMinutes:20,rating:4.1,speedKmh:0,heightM:20,inversions:0,openedYear:1998,minHeightCm:120,temporarilyClosed:false},
{id:'castaway_bay',name:'Castaway Bay',description:'A spectacular water play area and family water park within Sea World — featuring water slides, splash zones, wave effects and a beautifully themed tropical shipwreck environment. The most popular area for families with younger children at Sea World Gold Coast. Min 90cm for slides.',image:'assets/images/sea_world_gold_coast/castaway_bay.png',category:'family',topPick:true,lat:-27.9635,lng:153.4293,liveWaitMinutes:0,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2014,minHeightCm:90,temporarilyClosed:false},
{id:'dolphin_show',name:'Dolphin Show',description:'The iconic Sea World dolphin show — one of the most spectacular and beloved marine animal presentations in the Southern Hemisphere. Watch the park resident bottlenose dolphins perform extraordinary behaviours alongside their expert trainers in the magnificent 3000-seat Sea World Theatre. Suitable for all ages.',image:'assets/images/sea_world_gold_coast/dolphin_show.png',category:'family',topPick:true,lat:-27.9620,lng:153.4278,liveWaitMinutes:0,rating:4.7,speedKmh:0,heightM:0,inversions:0,openedYear:1971,minHeightCm:0,temporarilyClosed:false},
{id:'penguin_encounter',name:'Penguin Encounter',description:'A uniquely immersive Antarctic environment housing a colony of gentoo and king penguins — guests walk through a temperature-controlled indoor habitat and watch the penguins swim, play and interact in conditions that replicate their natural Southern Ocean environment. One of the finest penguin exhibits in the world. Suitable for all ages.',image:'assets/images/sea_world_gold_coast/penguin_encounter.png',category:'family',topPick:true,lat:-27.9622,lng:153.4280,liveWaitMinutes:15,rating:4.6,speedKmh:0,heightM:0,inversions:0,openedYear:1995,minHeightCm:0,temporarilyClosed:false},
{id:'polar_bear_shores',name:'Polar Bear Shores',description:'A remarkable polar bear habitat where guests can observe two resident polar bears in a beautifully landscaped environment with underwater viewing windows — one of only a handful of places in the Southern Hemisphere where you can see polar bears. A unique and unforgettable wildlife experience. Suitable for all ages.',image:'assets/images/sea_world_gold_coast/polar_bear_shores.png',category:'family',topPick:true,lat:-27.9624,lng:153.4282,liveWaitMinutes:10,rating:4.5,speedKmh:0,heightM:0,inversions:0,openedYear:2012,minHeightCm:0,temporarilyClosed:false},
{id:'shark_bay',name:'Shark Bay',description:'An extraordinary open lagoon where guests can snorkel alongside nurse sharks, rays and tropical fish in a unique swim-with-sharks experience — one of the most exciting and memorable wildlife encounters available at any theme park in Australia. Bookings required.',image:'assets/images/sea_world_gold_coast/shark_bay.png',category:'family',topPick:true,lat:-27.9619,lng:153.4277,liveWaitMinutes:0,rating:4.6,speedKmh:0,heightM:0,inversions:0,openedYear:1985,minHeightCm:0,temporarilyClosed:false},
{id:'ray_touch_pool',name:'Ray Touch Pool',description:'A popular interactive touch pool where guests can gently touch and feed stingrays in a shallow lagoon — one of the most charming and memorable family wildlife encounters at Sea World. A wonderful tactile experience for children of all ages. Suitable for all ages.',image:'assets/images/sea_world_gold_coast/ray_touch_pool.png',category:'family',topPick:false,lat:-27.9621,lng:153.4279,liveWaitMinutes:0,rating:4.4,speedKmh:0,heightM:0,inversions:0,openedYear:1990,minHeightCm:0,temporarilyClosed:false},
{id:'donatellos_ninja_flyers',name:'Donatello\'s Ninja Flyers',description:'A fun interactive flying ride themed to the Teenage Mutant Ninja Turtles where guests control the height of their own flying vehicle as they circle above the park — perfect for families with younger children. Min 90cm.',image:'assets/images/sea_world_gold_coast/donatellos_ninja_flyers.png',category:'family',topPick:false,lat:-27.9636,lng:153.4294,liveWaitMinutes:20,rating:4.1,speedKmh:0,heightM:15,inversions:0,openedYear:2020,minHeightCm:90,temporarilyClosed:false},
{id:'sea_world_live_show',name:'Sea World Live Show',description:'A spectacular live entertainment show at Sea World featuring professional performers, music and sea-themed theatrical sequences in the Sea World Amphitheatre. One of the most entertaining and family-friendly live shows on the Gold Coast. Suitable for all ages.',image:'assets/images/sea_world_gold_coast/sea_world_live_show.png',category:'family',topPick:false,lat:-27.9618,lng:153.4276,liveWaitMinutes:0,rating:4.3,speedKmh:0,heightM:0,inversions:0,openedYear:1971,minHeightCm:0,temporarilyClosed:false},
{id:'sea_world_helicopter',name:'Sea World Helicopters',description:'A breathtaking scenic helicopter flight over the Gold Coast, the Broadwater and the stunning Queensland coastline — one of the most extraordinary and memorable experiences available at any theme park in Australia. Multiple flight options available.',image:'assets/images/sea_world_gold_coast/sea_world_helicopter.png',category:'family',topPick:true,lat:-27.9617,lng:153.4275,liveWaitMinutes:0,rating:4.9,speedKmh:0,heightM:0,inversions:0,openedYear:1990,minHeightCm:0,temporarilyClosed:false},
{id:'sea_world_live_show2',name:'Nickelodeon Slime Time',description:'A hilarious live show featuring Nickelodeon characters including SpongeBob, Dora and the Teenage Mutant Ninja Turtles with spectacular slime sequences and audience participation. One of the most entertaining family shows at Sea World. Suitable for all ages.',image:'assets/images/sea_world_gold_coast/sea_world_live_show.png',category:'family',topPick:false,lat:-27.9616,lng:153.4274,liveWaitMinutes:0,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:2015,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/sea_world_gold_coast/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('attractions.json done, entries:',d.length);