const fs=require('fs');
const d=[
{id:'tower_of_terror',name:'Tower of Terror',description:'One of the tallest and most intense drop towers in Africa — Tower of Terror hoists riders to a terrifying height before releasing them in a stomach-dropping free fall. A Gold Reef City icon and the most recognisable ride on the Johannesburg skyline. Min 130cm.',image:'assets/images/gold_reef_city/tower_of_terror.png',category:'thrill',topPick:true,lat:-26.2461,lng:27.9942,liveWaitMinutes:45,rating:4.7,speedKmh:0,heightM:80,inversions:0,openedYear:1999,minHeightCm:130,temporarilyClosed:false},
{id:'anaconda',name:'Anaconda',description:'A thrilling steel roller coaster that winds and twists through inversions at speed — the premier coaster experience at Gold Reef City and a firm favourite with thrill-seekers visiting Johannesburg. Min 120cm.',image:'assets/images/gold_reef_city/anaconda.png',category:'thrill',topPick:true,lat:-26.2463,lng:27.9944,liveWaitMinutes:40,rating:4.5,speedKmh:80,heightM:28,inversions:2,openedYear:2000,minHeightCm:120,temporarilyClosed:false},
{id:'storm_chaser',name:'Storm Chaser',description:'A high-energy spinning coaster that sends riders through unpredictable twists and turns in freely rotating vehicles — no two rides are the same. One of the most popular attractions for families and thrill-seekers at Gold Reef City. Min 110cm.',image:'assets/images/gold_reef_city/storm_chaser.png',category:'thrill',topPick:true,lat:-26.2462,lng:27.9943,liveWaitMinutes:35,rating:4.4,speedKmh:65,heightM:18,inversions:0,openedYear:2008,minHeightCm:110,temporarilyClosed:false},
{id:'tornado',name:'Tornado',description:'A classic inverted swing ride that sends riders soaring and spinning at height — delivering excellent thrills in a compact and accessible format. Popular with older children and adults at Gold Reef City. Min 120cm.',image:'assets/images/gold_reef_city/tornado.png',category:'thrill',topPick:false,lat:-26.2465,lng:27.9946,liveWaitMinutes:25,rating:4.2,speedKmh:0,heightM:22,inversions:0,openedYear:2003,minHeightCm:120,temporarilyClosed:false},
{id:'raging_river',name:'Raging River',description:'A circular river rapids ride that sweeps guests through churning white water channels with unexpected splashes and soakings — the best water attraction at Gold Reef City and perfect for hot Johannesburg days. Min 100cm.',image:'assets/images/gold_reef_city/raging_river.png',category:'family',topPick:true,lat:-26.2466,lng:27.9947,liveWaitMinutes:30,rating:4.3,speedKmh:0,heightM:0,inversions:0,openedYear:1997,minHeightCm:100,temporarilyClosed:false},
{id:'mine_tour',name:'Gold Reef City Mine Tour',description:'A fascinating underground guided tour through a genuine 19th century gold mine shaft — the most historically significant attraction at Gold Reef City offering an authentic glimpse into the Witwatersrand gold rush that built Johannesburg. One of the must-do experiences. Suitable for all ages.',image:'assets/images/gold_reef_city/mine_tour.png',category:'family',topPick:true,lat:-26.2460,lng:27.9941,liveWaitMinutes:20,rating:4.6,speedKmh:0,heightM:0,inversions:0,openedYear:1987,minHeightCm:0,temporarilyClosed:false},
{id:'mine_train',name:'Mine Train',description:'A classic family roller coaster themed to the gold mining heritage of Johannesburg — gentle hills and turns make this the ideal first coaster for children and families. Min 90cm.',image:'assets/images/gold_reef_city/mine_train.png',category:'family',topPick:false,lat:-26.2464,lng:27.9945,liveWaitMinutes:20,rating:4.1,speedKmh:45,heightM:10,inversions:0,openedYear:1993,minHeightCm:90,temporarilyClosed:false},
{id:'jozi_express',name:'Jozi Express',description:'A scenic train ride around the Gold Reef City park offering beautiful views of the entire resort and surrounding Johannesburg landscape — a relaxing way to see the park and rest between thrill rides. Suitable for all ages.',image:'assets/images/gold_reef_city/jozi_express.png',category:'family',topPick:false,lat:-26.2468,lng:27.9949,liveWaitMinutes:15,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:1993,minHeightCm:0,temporarilyClosed:false},
{id:'ferris_wheel',name:'Ferris Wheel',description:'A classic Ferris wheel offering panoramic views over the Gold Reef City resort and the Johannesburg skyline — a perfect attraction for families wanting a relaxed and beautiful elevated experience. Suitable for all ages.',image:'assets/images/gold_reef_city/ferris_wheel.png',category:'family',topPick:false,lat:-26.2467,lng:27.9948,liveWaitMinutes:15,rating:4.0,speedKmh:0,heightM:30,inversions:0,openedYear:1993,minHeightCm:0,temporarilyClosed:false},
{id:'balloon_wheel',name:'Balloon Wheel',description:'A fun and colourful hot air balloon themed Ferris wheel that is one of the most photographed and iconic visual landmarks of Gold Reef City. Beloved by families and perfect for younger children. Suitable for all ages.',image:'assets/images/gold_reef_city/balloon_wheel.png',category:'family',topPick:false,lat:-26.2469,lng:27.9950,liveWaitMinutes:10,rating:4.0,speedKmh:0,heightM:20,inversions:0,openedYear:1993,minHeightCm:0,temporarilyClosed:false},
{id:'high_flyer',name:'High Flyer',description:'A soaring swing ride that lifts riders high above the park and spins them outward delivering beautiful views of Johannesburg alongside genuine thrills. A popular flat ride at Gold Reef City. Min 120cm.',image:'assets/images/gold_reef_city/high_flyer.png',category:'thrill',topPick:false,lat:-26.2464,lng:27.9945,liveWaitMinutes:20,rating:4.1,speedKmh:0,heightM:35,inversions:0,openedYear:2002,minHeightCm:120,temporarilyClosed:false},
{id:'bumper_cars',name:'Bumper Cars',description:'Classic dodgem bumper cars — endlessly entertaining for all ages and one of the most popular family attractions at Gold Reef City. Perfect fun for families with children of all ages.',image:'assets/images/gold_reef_city/bumper_cars.png',category:'family',topPick:false,lat:-26.2470,lng:27.9951,liveWaitMinutes:15,rating:4.0,speedKmh:0,heightM:0,inversions:0,openedYear:1993,minHeightCm:0,temporarilyClosed:false},
{id:'carousel',name:'Carousel',description:'A beautifully decorated classic carousel — a beloved Gold Reef City icon that has delighted generations of South African families. Perfect for young children on their first theme park visit. Suitable for all ages.',image:'assets/images/gold_reef_city/carousel.png',category:'family',topPick:false,lat:-26.2471,lng:27.9952,liveWaitMinutes:10,rating:4.1,speedKmh:0,heightM:0,inversions:0,openedYear:1987,minHeightCm:0,temporarilyClosed:false},
{id:'kids_corner',name:'Kids Corner',description:'A dedicated children\'s play area with age-appropriate rides, climbing structures and activities designed specifically for younger children visiting Gold Reef City. The ideal area for families with toddlers and young children. Suitable for all ages.',image:'assets/images/gold_reef_city/kids_corner.png',category:'family',topPick:false,lat:-26.2472,lng:27.9953,liveWaitMinutes:0,rating:4.2,speedKmh:0,heightM:0,inversions:0,openedYear:1993,minHeightCm:0,temporarilyClosed:false}
];
fs.writeFileSync('assets/data/parks/gold_reef_city/attractions.json',JSON.stringify(d,null,2),'utf8');
console.log('attractions.json done, entries:',d.length);